# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from pydantic_cpd.client import CDPClient

from .commands import (
    AddPrivacySandboxCoordinatorKeyConfigParams,
    AddPrivacySandboxEnrollmentOverrideParams,
    CancelDownloadParams,
    ExecuteBrowserCommandParams,
    GetBrowserCommandLineResult,
    GetHistogramParams,
    GetHistogramResult,
    GetHistogramsParams,
    GetHistogramsResult,
    GetVersionResult,
    GetWindowBoundsParams,
    GetWindowBoundsResult,
    GetWindowForTargetParams,
    GetWindowForTargetResult,
    GrantPermissionsParams,
    ResetPermissionsParams,
    SetContentsSizeParams,
    SetDockTileParams,
    SetDownloadBehaviorParams,
    SetPermissionParams,
    SetWindowBoundsParams,
)
from .types import (
    Bounds,
    BrowserCommandId,
    BrowserContextID,
    PermissionDescriptor,
    PermissionSetting,
    PermissionType,
    PrivacySandboxAPI,
    WindowID,
)


class BrowserClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def set_permission(
        self,
        *,
        permission: PermissionDescriptor,
        setting: PermissionSetting,
        origin: str | None = None,
        embedded_origin: str | None = None,
        browser_context_id: BrowserContextID | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetPermissionParams(
            permission=permission,
            setting=setting,
            origin=origin,
            embeddedOrigin=embedded_origin,
            browserContextId=browser_context_id,
        )

        result = await self._client.send_raw(
            method="Browser.setPermission",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def grant_permissions(
        self,
        *,
        permissions: list[PermissionType],
        origin: str | None = None,
        browser_context_id: BrowserContextID | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = GrantPermissionsParams(
            permissions=permissions, origin=origin, browserContextId=browser_context_id
        )

        result = await self._client.send_raw(
            method="Browser.grantPermissions",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def reset_permissions(
        self,
        *,
        browser_context_id: BrowserContextID | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ResetPermissionsParams(browserContextId=browser_context_id)

        result = await self._client.send_raw(
            method="Browser.resetPermissions",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_download_behavior(
        self,
        *,
        behavior: Literal["deny", "allow", "allowAndName", "default"],
        browser_context_id: BrowserContextID | None = None,
        download_path: str | None = None,
        events_enabled: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDownloadBehaviorParams(
            behavior=behavior,
            browserContextId=browser_context_id,
            downloadPath=download_path,
            eventsEnabled=events_enabled,
        )

        result = await self._client.send_raw(
            method="Browser.setDownloadBehavior",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def cancel_download(
        self,
        *,
        guid: str,
        browser_context_id: BrowserContextID | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = CancelDownloadParams(guid=guid, browserContextId=browser_context_id)

        result = await self._client.send_raw(
            method="Browser.cancelDownload",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def close(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Browser.close",
            params=None,
            session_id=session_id,
        )
        return result

    async def crash(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Browser.crash",
            params=None,
            session_id=session_id,
        )
        return result

    async def crash_gpu_process(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Browser.crashGpuProcess",
            params=None,
            session_id=session_id,
        )
        return result

    async def get_version(
        self,
        session_id: str | None = None,
    ) -> GetVersionResult:
        result = await self._client.send_raw(
            method="Browser.getVersion",
            params=None,
            session_id=session_id,
        )
        return GetVersionResult.model_validate(result)

    async def get_browser_command_line(
        self,
        session_id: str | None = None,
    ) -> GetBrowserCommandLineResult:
        result = await self._client.send_raw(
            method="Browser.getBrowserCommandLine",
            params=None,
            session_id=session_id,
        )
        return GetBrowserCommandLineResult.model_validate(result)

    async def get_histograms(
        self,
        *,
        query: str | None = None,
        delta: bool | None = None,
        session_id: str | None = None,
    ) -> GetHistogramsResult:
        params = GetHistogramsParams(query=query, delta=delta)

        result = await self._client.send_raw(
            method="Browser.getHistograms",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetHistogramsResult.model_validate(result)

    async def get_histogram(
        self,
        *,
        name: str,
        delta: bool | None = None,
        session_id: str | None = None,
    ) -> GetHistogramResult:
        params = GetHistogramParams(name=name, delta=delta)

        result = await self._client.send_raw(
            method="Browser.getHistogram",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetHistogramResult.model_validate(result)

    async def get_window_bounds(
        self,
        *,
        window_id: WindowID,
        session_id: str | None = None,
    ) -> GetWindowBoundsResult:
        params = GetWindowBoundsParams(windowId=window_id)

        result = await self._client.send_raw(
            method="Browser.getWindowBounds",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetWindowBoundsResult.model_validate(result)

    async def get_window_for_target(
        self,
        *,
        target_id: Target.TargetID | None = None,
        session_id: str | None = None,
    ) -> GetWindowForTargetResult:
        params = GetWindowForTargetParams(targetId=target_id)

        result = await self._client.send_raw(
            method="Browser.getWindowForTarget",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetWindowForTargetResult.model_validate(result)

    async def set_window_bounds(
        self,
        *,
        window_id: WindowID,
        bounds: Bounds,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetWindowBoundsParams(windowId=window_id, bounds=bounds)

        result = await self._client.send_raw(
            method="Browser.setWindowBounds",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_contents_size(
        self,
        *,
        window_id: WindowID,
        width: int | None = None,
        height: int | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetContentsSizeParams(windowId=window_id, width=width, height=height)

        result = await self._client.send_raw(
            method="Browser.setContentsSize",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_dock_tile(
        self,
        *,
        badge_label: str | None = None,
        image: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDockTileParams(badgeLabel=badge_label, image=image)

        result = await self._client.send_raw(
            method="Browser.setDockTile",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def execute_browser_command(
        self,
        *,
        command_id: BrowserCommandId,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ExecuteBrowserCommandParams(commandId=command_id)

        result = await self._client.send_raw(
            method="Browser.executeBrowserCommand",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def add_privacy_sandbox_enrollment_override(
        self,
        *,
        url: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = AddPrivacySandboxEnrollmentOverrideParams(url=url)

        result = await self._client.send_raw(
            method="Browser.addPrivacySandboxEnrollmentOverride",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def add_privacy_sandbox_coordinator_key_config(
        self,
        *,
        api: PrivacySandboxAPI,
        coordinator_origin: str,
        key_config: str,
        browser_context_id: BrowserContextID | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = AddPrivacySandboxCoordinatorKeyConfigParams(
            api=api,
            coordinatorOrigin=coordinator_origin,
            keyConfig=key_config,
            browserContextId=browser_context_id,
        )

        result = await self._client.send_raw(
            method="Browser.addPrivacySandboxCoordinatorKeyConfig",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
