# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class TetheringCommand(StrEnum):
    BIND = "Tethering.bind"
    UNBIND = "Tethering.unbind"


@dataclass(kw_only=True, slots=True)
class BindParams:
    """
    Request browser port binding.
    """

    port: int = field(metadata={"cdp_name": "port"})


@dataclass(kw_only=True, slots=True)
class UnbindParams:
    """
    Request browser port unbinding.
    """

    port: int = field(metadata={"cdp_name": "port"})
