# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from .types import (
    ExtensionInfo,
    StorageArea,
)


class ExtensionsCommand(StrEnum):
    TRIGGER_ACTION = "Extensions.triggerAction"
    LOAD_UNPACKED = "Extensions.loadUnpacked"
    GET_EXTENSIONS = "Extensions.getExtensions"
    UNINSTALL = "Extensions.uninstall"
    GET_STORAGE_ITEMS = "Extensions.getStorageItems"
    REMOVE_STORAGE_ITEMS = "Extensions.removeStorageItems"
    CLEAR_STORAGE_ITEMS = "Extensions.clearStorageItems"
    SET_STORAGE_ITEMS = "Extensions.setStorageItems"


@dataclass(kw_only=True, slots=True)
class TriggerActionParams:
    """
    Runs an extension default action.
    """

    id: str = field(metadata={"cdp_name": "id"})
    target_id: str = field(metadata={"cdp_name": "targetId"})


@dataclass(kw_only=True, slots=True)
class LoadUnpackedParams:
    """
    Installs an unpacked extension from the filesystem similar to --load-extension CLI
    flags. Returns extension ID once the extension has been installed.
    """

    path: str = field(metadata={"cdp_name": "path"})
    enable_in_incognito: bool | None = field(
        default=None, metadata={"cdp_name": "enableInIncognito"}
    )


@dataclass(kw_only=True, slots=True)
class LoadUnpackedResult:
    id: str = field(metadata={"cdp_name": "id"})


@dataclass(kw_only=True, slots=True)
class GetExtensionsResult:
    extensions: list[ExtensionInfo] = field(metadata={"cdp_name": "extensions"})


@dataclass(kw_only=True, slots=True)
class UninstallParams:
    """
    Uninstalls an unpacked extension (others not supported) from the profile.
    """

    id: str = field(metadata={"cdp_name": "id"})


@dataclass(kw_only=True, slots=True)
class GetStorageItemsParams:
    """
    Gets data from extension storage in the given `storageArea`. If `keys` is
    specified, these are used to filter the result.
    """

    id: str = field(metadata={"cdp_name": "id"})
    storage_area: StorageArea = field(metadata={"cdp_name": "storageArea"})
    keys: list[str] | None = field(default=None, metadata={"cdp_name": "keys"})


@dataclass(kw_only=True, slots=True)
class GetStorageItemsResult:
    data: dict[str, Any] = field(metadata={"cdp_name": "data"})


@dataclass(kw_only=True, slots=True)
class RemoveStorageItemsParams:
    """
    Removes `keys` from extension storage in the given `storageArea`.
    """

    id: str = field(metadata={"cdp_name": "id"})
    storage_area: StorageArea = field(metadata={"cdp_name": "storageArea"})
    keys: list[str] = field(metadata={"cdp_name": "keys"})


@dataclass(kw_only=True, slots=True)
class ClearStorageItemsParams:
    """
    Clears extension storage in the given `storageArea`.
    """

    id: str = field(metadata={"cdp_name": "id"})
    storage_area: StorageArea = field(metadata={"cdp_name": "storageArea"})


@dataclass(kw_only=True, slots=True)
class SetStorageItemsParams:
    """
    Sets `values` in extension storage in the given `storageArea`. The provided
    `values` will be merged with existing values in the storage area.
    """

    id: str = field(metadata={"cdp_name": "id"})
    storage_area: StorageArea = field(metadata={"cdp_name": "storageArea"})
    values: dict[str, Any] = field(metadata={"cdp_name": "values"})
