# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from cdpify.domains import page


class WebMCPCommand(StrEnum):
    ENABLE = "WebMCP.enable"
    DISABLE = "WebMCP.disable"
    INVOKE_TOOL = "WebMCP.invokeTool"
    CANCEL_INVOCATION = "WebMCP.cancelInvocation"


@dataclass(kw_only=True, slots=True)
class InvokeToolParams:
    """
    Invokes a registered tool.
    """

    frame_id: page.FrameId = field(metadata={"cdp_name": "frameId"})
    tool_name: str = field(metadata={"cdp_name": "toolName"})
    input: dict[str, Any] = field(metadata={"cdp_name": "input"})


@dataclass(kw_only=True, slots=True)
class InvokeToolResult:
    invocation_id: str = field(metadata={"cdp_name": "invocationId"})


@dataclass(kw_only=True, slots=True)
class CancelInvocationParams:
    """
    Cancels a pending tool invocation.
    """

    invocation_id: str = field(metadata={"cdp_name": "invocationId"})
