# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from cdpify.domains import page, runtime
from cdpify.shared.models import CDPEvent

from .types import (
    InvocationStatus,
    RemovedTool,
    Tool,
)


class WebMCPEvent(StrEnum):
    TOOLS_ADDED = "WebMCP.toolsAdded"
    TOOLS_REMOVED = "WebMCP.toolsRemoved"
    TOOL_INVOKED = "WebMCP.toolInvoked"
    TOOL_RESPONDED = "WebMCP.toolResponded"


@dataclass(kw_only=True, slots=True)
class ToolsAddedEvent(CDPEvent):
    """
    Event fired when new tools are added.
    """

    tools: list[Tool]


@dataclass(kw_only=True, slots=True)
class ToolsRemovedEvent(CDPEvent):
    """
    Event fired when tools are removed.
    """

    tools: list[RemovedTool]


@dataclass(kw_only=True, slots=True)
class ToolInvokedEvent(CDPEvent):
    """
    Event fired when a tool invocation starts.
    """

    tool_name: str
    frame_id: page.FrameId
    invocation_id: str
    input: str


@dataclass(kw_only=True, slots=True)
class ToolRespondedEvent(CDPEvent):
    """
    Event fired when a tool invocation completes or fails.
    """

    invocation_id: str
    status: InvocationStatus
    output: Any | None = None
    error_text: str | None = None
    exception: runtime.RemoteObject | None = None
