# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from .types import (
    AddressUI,
    FilledField,
)


class AutofillEvent(StrEnum):
    ADDRESS_FORM_FILLED = "Autofill.addressFormFilled"


@dataclass(kw_only=True, slots=True)
class AddressFormFilledEvent:
    """
    Emitted when an address form is filled.
    """

    filled_fields: list[FilledField] = field(metadata={"cdp_name": "filledFields"})
    address_ui: AddressUI = field(metadata={"cdp_name": "addressUi"})
    cdp_session_id: str | None = field(
        default=None,
        repr=False,
        compare=False,
        metadata={"cdp": False},
    )
