# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.shared.models import CDPModel

from .types import (
    AccountUrlType,
    DialogButton,
)


class FedCmCommand(StrEnum):
    ENABLE = "FedCm.enable"
    DISABLE = "FedCm.disable"
    SELECT_ACCOUNT = "FedCm.selectAccount"
    CLICK_DIALOG_BUTTON = "FedCm.clickDialogButton"
    OPEN_URL = "FedCm.openUrl"
    DISMISS_DIALOG = "FedCm.dismissDialog"
    RESET_COOLDOWN = "FedCm.resetCooldown"


@dataclass(kw_only=True, slots=True)
class EnableParams(CDPModel):
    disable_rejection_delay: bool | None = None


@dataclass(kw_only=True, slots=True)
class SelectAccountParams(CDPModel):
    dialog_id: str
    account_index: int


@dataclass(kw_only=True, slots=True)
class ClickDialogButtonParams(CDPModel):
    dialog_id: str
    dialog_button: DialogButton


@dataclass(kw_only=True, slots=True)
class OpenUrlParams(CDPModel):
    dialog_id: str
    account_index: int
    account_url_type: AccountUrlType


@dataclass(kw_only=True, slots=True)
class DismissDialogParams(CDPModel):
    dialog_id: str
    trigger_cooldown: bool | None = None
