# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from .types import (
    AccountUrlType,
    DialogButton,
)


class FedCmCommand(StrEnum):
    ENABLE = "FedCm.enable"
    DISABLE = "FedCm.disable"
    SELECT_ACCOUNT = "FedCm.selectAccount"
    CLICK_DIALOG_BUTTON = "FedCm.clickDialogButton"
    OPEN_URL = "FedCm.openUrl"
    DISMISS_DIALOG = "FedCm.dismissDialog"
    RESET_COOLDOWN = "FedCm.resetCooldown"


@dataclass(kw_only=True, slots=True)
class EnableParams:
    disable_rejection_delay: bool | None = field(
        default=None, metadata={"cdp_name": "disableRejectionDelay"}
    )


@dataclass(kw_only=True, slots=True)
class SelectAccountParams:
    dialog_id: str = field(metadata={"cdp_name": "dialogId"})
    account_index: int = field(metadata={"cdp_name": "accountIndex"})


@dataclass(kw_only=True, slots=True)
class ClickDialogButtonParams:
    dialog_id: str = field(metadata={"cdp_name": "dialogId"})
    dialog_button: DialogButton = field(metadata={"cdp_name": "dialogButton"})


@dataclass(kw_only=True, slots=True)
class OpenUrlParams:
    dialog_id: str = field(metadata={"cdp_name": "dialogId"})
    account_index: int = field(metadata={"cdp_name": "accountIndex"})
    account_url_type: AccountUrlType = field(metadata={"cdp_name": "accountUrlType"})


@dataclass(kw_only=True, slots=True)
class DismissDialogParams:
    dialog_id: str = field(metadata={"cdp_name": "dialogId"})
    trigger_cooldown: bool | None = field(
        default=None, metadata={"cdp_name": "triggerCooldown"}
    )
