# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    ClickDialogButtonParams,
    DismissDialogParams,
    EnableParams,
    FedCmCommand,
    OpenUrlParams,
    SelectAccountParams,
)
from .types import (
    AccountUrlType,
    DialogButton,
)


class FedCm:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def enable(
        self,
        *,
        disable_rejection_delay: bool | None = None,
        session_id: str | None = None,
    ) -> None:
        params = EnableParams(disable_rejection_delay=disable_rejection_delay)

        await self._command_sender.send_raw(
            method=FedCmCommand.ENABLE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def disable(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._command_sender.send_raw(
            method=FedCmCommand.DISABLE,
            params=None,
            session_id=session_id,
        )

    async def select_account(
        self,
        *,
        dialog_id: str,
        account_index: int,
        session_id: str | None = None,
    ) -> None:
        params = SelectAccountParams(dialog_id=dialog_id, account_index=account_index)

        await self._command_sender.send_raw(
            method=FedCmCommand.SELECT_ACCOUNT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def click_dialog_button(
        self,
        *,
        dialog_id: str,
        dialog_button: DialogButton,
        session_id: str | None = None,
    ) -> None:
        params = ClickDialogButtonParams(
            dialog_id=dialog_id, dialog_button=dialog_button
        )

        await self._command_sender.send_raw(
            method=FedCmCommand.CLICK_DIALOG_BUTTON,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def open_url(
        self,
        *,
        dialog_id: str,
        account_index: int,
        account_url_type: AccountUrlType,
        session_id: str | None = None,
    ) -> None:
        params = OpenUrlParams(
            dialog_id=dialog_id,
            account_index=account_index,
            account_url_type=account_url_type,
        )

        await self._command_sender.send_raw(
            method=FedCmCommand.OPEN_URL,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def dismiss_dialog(
        self,
        *,
        dialog_id: str,
        trigger_cooldown: bool | None = None,
        session_id: str | None = None,
    ) -> None:
        params = DismissDialogParams(
            dialog_id=dialog_id, trigger_cooldown=trigger_cooldown
        )

        await self._command_sender.send_raw(
            method=FedCmCommand.DISMISS_DIALOG,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def reset_cooldown(
        self,
        session_id: str | None = None,
    ) -> None:
        """
        Resets the cooldown time, if any, to allow the next FedCM call to show a dialog
        even if one was recently dismissed by the user.
        """
        await self._command_sender.send_raw(
            method=FedCmCommand.RESET_COOLDOWN,
            params=None,
            session_id=session_id,
        )
