# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from cdpify.shared.models import CDPModel

"""
Whether this is a sign-up or sign-in action for this account, i.e. whether this account
has ever been used to sign in to this RP before.
"""
type LoginState = Literal["SignIn", "SignUp"]

"""
The types of FedCM dialogs.
"""
type DialogType = Literal["AccountChooser", "AutoReauthn", "ConfirmIdpLogin", "Error"]

"""
The buttons on the FedCM dialog.
"""
type DialogButton = Literal["ConfirmIdpLoginContinue", "ErrorGotIt", "ErrorMoreDetails"]

"""
The URLs that each account has
"""
type AccountUrlType = Literal["TermsOfService", "PrivacyPolicy"]


@dataclass(kw_only=True, slots=True)
class Account(CDPModel):
    """
    Corresponds to IdentityRequestAccount
    """

    account_id: str
    email: str
    name: str
    given_name: str
    picture_url: str
    idp_config_url: str
    idp_login_url: str
    login_state: LoginState
    terms_of_service_url: str | None = None
    privacy_policy_url: str | None = None
