# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import Any, Literal
from dataclasses import dataclass
from cdpify.shared.models import CDPModel

"""
Unique script identifier.
"""
ScriptId = str


@dataclass(kw_only=True)
class SerializationOptions(CDPModel):
    """
    Represents options for serialization. Overrides `generatePreview` and
    `returnByValue`.
    """

    serialization: Literal["deep", "json", "idOnly"]
    max_depth: int | None = None
    additional_parameters: dict[str, Any] | None = None


@dataclass(kw_only=True)
class DeepSerializedValue(CDPModel):
    """
    Represents deep serialized value.
    """

    type: Literal[
        "undefined",
        "null",
        "string",
        "number",
        "boolean",
        "bigint",
        "regexp",
        "date",
        "symbol",
        "array",
        "object",
        "function",
        "map",
        "set",
        "weakmap",
        "weakset",
        "error",
        "proxy",
        "promise",
        "typedarray",
        "arraybuffer",
        "node",
        "window",
        "generator",
    ]
    value: Any | None = None
    object_id: str | None = None
    weak_local_object_reference: int | None = None


"""
Unique object identifier.
"""
RemoteObjectId = str

"""
Primitive value which cannot be JSON-stringified. Includes values `-0`, `NaN`,
`Infinity`, `-Infinity`, and bigint literals.
"""
UnserializableValue = str


@dataclass(kw_only=True)
class RemoteObject(CDPModel):
    """
    Mirror object referencing original JavaScript object.
    """

    type: Literal[
        "object",
        "function",
        "undefined",
        "string",
        "number",
        "boolean",
        "symbol",
        "bigint",
    ]
    subtype: (
        Literal[
            "array",
            "null",
            "node",
            "regexp",
            "date",
            "map",
            "set",
            "weakmap",
            "weakset",
            "iterator",
            "generator",
            "error",
            "proxy",
            "promise",
            "typedarray",
            "arraybuffer",
            "dataview",
            "webassemblymemory",
            "wasmvalue",
            "trustedtype",
        ]
        | None
    ) = None
    class_name: str | None = None
    value: Any | None = None
    unserializable_value: UnserializableValue | None = None
    description: str | None = None
    deep_serialized_value: DeepSerializedValue | None = None
    object_id: RemoteObjectId | None = None
    preview: ObjectPreview | None = None
    custom_preview: CustomPreview | None = None


@dataclass(kw_only=True)
class CustomPreview(CDPModel):
    header: str
    body_getter_id: RemoteObjectId | None = None


@dataclass(kw_only=True)
class ObjectPreview(CDPModel):
    """
    Object containing abbreviated remote object value.
    """

    type: Literal[
        "object",
        "function",
        "undefined",
        "string",
        "number",
        "boolean",
        "symbol",
        "bigint",
    ]
    subtype: (
        Literal[
            "array",
            "null",
            "node",
            "regexp",
            "date",
            "map",
            "set",
            "weakmap",
            "weakset",
            "iterator",
            "generator",
            "error",
            "proxy",
            "promise",
            "typedarray",
            "arraybuffer",
            "dataview",
            "webassemblymemory",
            "wasmvalue",
            "trustedtype",
        ]
        | None
    ) = None
    description: str | None = None
    overflow: bool
    properties: list[PropertyPreview]
    entries: list[EntryPreview] | None = None


@dataclass(kw_only=True)
class PropertyPreview(CDPModel):
    name: str
    type: Literal[
        "object",
        "function",
        "undefined",
        "string",
        "number",
        "boolean",
        "symbol",
        "accessor",
        "bigint",
    ]
    value: str | None = None
    value_preview: ObjectPreview | None = None
    subtype: (
        Literal[
            "array",
            "null",
            "node",
            "regexp",
            "date",
            "map",
            "set",
            "weakmap",
            "weakset",
            "iterator",
            "generator",
            "error",
            "proxy",
            "promise",
            "typedarray",
            "arraybuffer",
            "dataview",
            "webassemblymemory",
            "wasmvalue",
            "trustedtype",
        ]
        | None
    ) = None


@dataclass(kw_only=True)
class EntryPreview(CDPModel):
    key: ObjectPreview | None = None
    value: ObjectPreview


@dataclass(kw_only=True)
class PropertyDescriptor(CDPModel):
    """
    Object property descriptor.
    """

    name: str
    value: RemoteObject | None = None
    writable: bool | None = None
    get: RemoteObject | None = None
    set: RemoteObject | None = None
    configurable: bool
    enumerable: bool
    was_thrown: bool | None = None
    is_own: bool | None = None
    symbol: RemoteObject | None = None


@dataclass(kw_only=True)
class InternalPropertyDescriptor(CDPModel):
    """
    Object internal property descriptor. This property isn't normally visible in
    JavaScript code.
    """

    name: str
    value: RemoteObject | None = None


@dataclass(kw_only=True)
class PrivatePropertyDescriptor(CDPModel):
    """
    Object private field descriptor.
    """

    name: str
    value: RemoteObject | None = None
    get: RemoteObject | None = None
    set: RemoteObject | None = None


@dataclass(kw_only=True)
class CallArgument(CDPModel):
    """
    Represents function call argument. Either remote object id `objectId`, primitive
    `value`, unserializable primitive value or neither of (for undefined) them should be
    specified.
    """

    value: Any | None = None
    unserializable_value: UnserializableValue | None = None
    object_id: RemoteObjectId | None = None


"""
Id of an execution context.
"""
ExecutionContextId = int


@dataclass(kw_only=True)
class ExecutionContextDescription(CDPModel):
    """
    Description of an isolated world.
    """

    id: ExecutionContextId
    origin: str
    name: str
    unique_id: str
    aux_data: dict[str, Any] | None = None


@dataclass(kw_only=True)
class ExceptionDetails(CDPModel):
    """
    Detailed information about exception (or error) that was thrown during script
    compilation or execution.
    """

    exception_id: int
    text: str
    line_number: int
    column_number: int
    script_id: ScriptId | None = None
    url: str | None = None
    stack_trace: StackTrace | None = None
    exception: RemoteObject | None = None
    execution_context_id: ExecutionContextId | None = None
    exception_meta_data: dict[str, Any] | None = None


"""
Number of milliseconds since epoch.
"""
Timestamp = float

"""
Number of milliseconds.
"""
TimeDelta = float


@dataclass(kw_only=True)
class CallFrame(CDPModel):
    """
    Stack entry for runtime errors and assertions.
    """

    function_name: str
    script_id: ScriptId
    url: str
    line_number: int
    column_number: int


@dataclass(kw_only=True)
class StackTrace(CDPModel):
    """
    Call frames for assertions or error messages.
    """

    description: str | None = None
    call_frames: list[CallFrame]
    parent: StackTrace | None = None
    parent_id: StackTraceId | None = None


"""
Unique identifier of current debugger.
"""
UniqueDebuggerId = str


@dataclass(kw_only=True)
class StackTraceId(CDPModel):
    """
    If `debuggerId` is set stack trace comes from another debugger and can be resolved
    there. This allows to track cross-debugger calls. See `Runtime.StackTrace` and
    `Debugger.paused` for usages.
    """

    id: str
    debugger_id: UniqueDebuggerId | None = None
