# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from cdpify.domains import storage

from .types import (
    DatabaseWithObjectStores,
    DataEntry,
    KeyRange,
)


class IndexedDBCommand(StrEnum):
    CLEAR_OBJECT_STORE = "IndexedDB.clearObjectStore"
    DELETE_DATABASE = "IndexedDB.deleteDatabase"
    DELETE_OBJECT_STORE_ENTRIES = "IndexedDB.deleteObjectStoreEntries"
    DISABLE = "IndexedDB.disable"
    ENABLE = "IndexedDB.enable"
    REQUEST_DATA = "IndexedDB.requestData"
    GET_METADATA = "IndexedDB.getMetadata"
    REQUEST_DATABASE = "IndexedDB.requestDatabase"
    REQUEST_DATABASE_NAMES = "IndexedDB.requestDatabaseNames"


@dataclass(kw_only=True, slots=True)
class ClearObjectStoreParams:
    """
    Clears all entries from an object store.
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )
    database_name: str = field(metadata={"cdp_name": "databaseName"})
    object_store_name: str = field(metadata={"cdp_name": "objectStoreName"})


@dataclass(kw_only=True, slots=True)
class DeleteDatabaseParams:
    """
    Deletes a database.
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )
    database_name: str = field(metadata={"cdp_name": "databaseName"})


@dataclass(kw_only=True, slots=True)
class DeleteObjectStoreEntriesParams:
    """
    Delete a range of entries from an object store
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )
    database_name: str = field(metadata={"cdp_name": "databaseName"})
    object_store_name: str = field(metadata={"cdp_name": "objectStoreName"})
    key_range: KeyRange = field(metadata={"cdp_name": "keyRange"})


@dataclass(kw_only=True, slots=True)
class RequestDataParams:
    """
    Requests data from object store or index.
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )
    database_name: str = field(metadata={"cdp_name": "databaseName"})
    object_store_name: str = field(metadata={"cdp_name": "objectStoreName"})
    index_name: str | None = field(default=None, metadata={"cdp_name": "indexName"})
    skip_count: int = field(metadata={"cdp_name": "skipCount"})
    page_size: int = field(metadata={"cdp_name": "pageSize"})
    key_range: KeyRange | None = field(default=None, metadata={"cdp_name": "keyRange"})


@dataclass(kw_only=True, slots=True)
class RequestDataResult:
    object_store_data_entries: list[DataEntry] = field(
        metadata={"cdp_name": "objectStoreDataEntries"}
    )
    has_more: bool = field(metadata={"cdp_name": "hasMore"})


@dataclass(kw_only=True, slots=True)
class GetMetadataParams:
    """
    Gets metadata of an object store.
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )
    database_name: str = field(metadata={"cdp_name": "databaseName"})
    object_store_name: str = field(metadata={"cdp_name": "objectStoreName"})


@dataclass(kw_only=True, slots=True)
class GetMetadataResult:
    entries_count: float = field(metadata={"cdp_name": "entriesCount"})
    key_generator_value: float = field(metadata={"cdp_name": "keyGeneratorValue"})


@dataclass(kw_only=True, slots=True)
class RequestDatabaseParams:
    """
    Requests database with given name in given frame.
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )
    database_name: str = field(metadata={"cdp_name": "databaseName"})


@dataclass(kw_only=True, slots=True)
class RequestDatabaseResult:
    database_with_object_stores: DatabaseWithObjectStores = field(
        metadata={"cdp_name": "databaseWithObjectStores"}
    )


@dataclass(kw_only=True, slots=True)
class RequestDatabaseNamesParams:
    """
    Requests database names for given security origin.
    """

    security_origin: str | None = field(
        default=None, metadata={"cdp_name": "securityOrigin"}
    )
    storage_key: str | None = field(default=None, metadata={"cdp_name": "storageKey"})
    storage_bucket: storage.StorageBucket | None = field(
        default=None, metadata={"cdp_name": "storageBucket"}
    )


@dataclass(kw_only=True, slots=True)
class RequestDatabaseNamesResult:
    database_names: list[str] = field(metadata={"cdp_name": "databaseNames"})
