# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    MediaCommand,
)


class Media:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def enable(
        self,
        session_id: str | None = None,
    ) -> None:
        """
        Enables the Media domain
        """
        await self._command_sender.send_raw(
            method=MediaCommand.ENABLE,
            params=None,
            session_id=session_id,
        )

    async def disable(
        self,
        session_id: str | None = None,
    ) -> None:
        """
        Disables the Media domain.
        """
        await self._command_sender.send_raw(
            method=MediaCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
