# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Literal

from .types import (
    MemoryDumpLevelOfDetail,
    StreamCompression,
    StreamFormat,
    TraceConfig,
    TracingBackend,
)


class TracingCommand(StrEnum):
    END = "Tracing.end"
    GET_CATEGORIES = "Tracing.getCategories"
    GET_TRACK_EVENT_DESCRIPTOR = "Tracing.getTrackEventDescriptor"
    RECORD_CLOCK_SYNC_MARKER = "Tracing.recordClockSyncMarker"
    REQUEST_MEMORY_DUMP = "Tracing.requestMemoryDump"
    START = "Tracing.start"


@dataclass(kw_only=True, slots=True)
class GetCategoriesResult:
    categories: list[str] = field(metadata={"cdp_name": "categories"})


@dataclass(kw_only=True, slots=True)
class GetTrackEventDescriptorResult:
    descriptor: str = field(metadata={"cdp_name": "descriptor"})


@dataclass(kw_only=True, slots=True)
class RecordClockSyncMarkerParams:
    """
    Record a clock sync marker in the trace.
    """

    sync_id: str = field(metadata={"cdp_name": "syncId"})


@dataclass(kw_only=True, slots=True)
class RequestMemoryDumpParams:
    """
    Request a global memory dump.
    """

    deterministic: bool | None = field(
        default=None, metadata={"cdp_name": "deterministic"}
    )
    level_of_detail: MemoryDumpLevelOfDetail | None = field(
        default=None, metadata={"cdp_name": "levelOfDetail"}
    )


@dataclass(kw_only=True, slots=True)
class RequestMemoryDumpResult:
    dump_guid: str = field(metadata={"cdp_name": "dumpGuid"})
    success: bool = field(metadata={"cdp_name": "success"})


@dataclass(kw_only=True, slots=True)
class StartParams:
    """
    Start trace events collection.
    """

    categories: str | None = field(default=None, metadata={"cdp_name": "categories"})
    options: str | None = field(default=None, metadata={"cdp_name": "options"})
    buffer_usage_reporting_interval: float | None = field(
        default=None, metadata={"cdp_name": "bufferUsageReportingInterval"}
    )
    transfer_mode: Literal["ReportEvents", "ReturnAsStream"] | None = field(
        default=None, metadata={"cdp_name": "transferMode"}
    )
    stream_format: StreamFormat | None = field(
        default=None, metadata={"cdp_name": "streamFormat"}
    )
    stream_compression: StreamCompression | None = field(
        default=None, metadata={"cdp_name": "streamCompression"}
    )
    trace_config: TraceConfig | None = field(
        default=None, metadata={"cdp_name": "traceConfig"}
    )
    perfetto_config: str | None = field(
        default=None, metadata={"cdp_name": "perfettoConfig"}
    )
    tracing_backend: TracingBackend | None = field(
        default=None, metadata={"cdp_name": "tracingBackend"}
    )
    screenshot_max_size: int | None = field(
        default=None, metadata={"cdp_name": "screenshotMaxSize"}
    )
    screenshot_max_count: int | None = field(
        default=None, metadata={"cdp_name": "screenshotMaxCount"}
    )
