# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import Any, Literal, TYPE_CHECKING
from dataclasses import dataclass
from cdpify.shared.models import CDPModel

if TYPE_CHECKING:
    from cdpify.domains import network

"""
Unique frame identifier.
"""
FrameId = str

"""
Indicates whether a frame has been identified as an ad.
"""
AdFrameType = Literal["none", "child", "root"]

AdFrameExplanation = Literal["ParentIsAd", "CreatedByAdScript", "MatchedBlockingRule"]


@dataclass(kw_only=True)
class AdFrameStatus(CDPModel):
    """
    Indicates whether a frame has been identified as an ad and why.
    """

    ad_frame_type: AdFrameType
    explanations: list[Any] | None = None


"""
Indicates whether the frame is a secure context and why it is the case.
"""
SecureContextType = Literal[
    "Secure", "SecureLocalhost", "InsecureScheme", "InsecureAncestor"
]

"""
Indicates whether the frame is cross-origin isolated and why it is the case.
"""
CrossOriginIsolatedContextType = Literal[
    "Isolated", "NotIsolated", "NotIsolatedFeatureDisabled"
]

GatedAPIFeatures = Literal[
    "SharedArrayBuffers",
    "SharedArrayBuffersTransferAllowed",
    "PerformanceMeasureMemory",
    "PerformanceProfile",
]

"""
All Permissions Policy features. This enum should match the one defined in
services/network/public/cpp/permissions_policy/permissions_policy_features.json5.
LINT.IfChange(PermissionsPolicyFeature)
"""
PermissionsPolicyFeature = Literal[
    "accelerometer",
    "all-screens-capture",
    "ambient-light-sensor",
    "aria-notify",
    "attribution-reporting",
    "autofill",
    "autoplay",
    "bluetooth",
    "browsing-topics",
    "camera",
    "captured-surface-control",
    "ch-dpr",
    "ch-device-memory",
    "ch-downlink",
    "ch-ect",
    "ch-prefers-color-scheme",
    "ch-prefers-reduced-motion",
    "ch-prefers-reduced-transparency",
    "ch-rtt",
    "ch-save-data",
    "ch-ua",
    "ch-ua-arch",
    "ch-ua-bitness",
    "ch-ua-high-entropy-values",
    "ch-ua-platform",
    "ch-ua-model",
    "ch-ua-mobile",
    "ch-ua-form-factors",
    "ch-ua-full-version",
    "ch-ua-full-version-list",
    "ch-ua-platform-version",
    "ch-ua-wow64",
    "ch-viewport-height",
    "ch-viewport-width",
    "ch-width",
    "clipboard-read",
    "clipboard-write",
    "compute-pressure",
    "controlled-frame",
    "cross-origin-isolated",
    "deferred-fetch",
    "deferred-fetch-minimal",
    "device-attributes",
    "digital-credentials-create",
    "digital-credentials-get",
    "direct-sockets",
    "direct-sockets-multicast",
    "direct-sockets-private",
    "display-capture",
    "document-domain",
    "encrypted-media",
    "execution-while-out-of-viewport",
    "execution-while-not-rendered",
    "fenced-unpartitioned-storage-read",
    "focus-without-user-activation",
    "fullscreen",
    "frobulate",
    "gamepad",
    "geolocation",
    "gyroscope",
    "hid",
    "identity-credentials-get",
    "idle-detection",
    "interest-cohort",
    "join-ad-interest-group",
    "keyboard-map",
    "language-detector",
    "language-model",
    "local-fonts",
    "local-network",
    "local-network-access",
    "loopback-network",
    "magnetometer",
    "manual-text",
    "media-playback-while-not-visible",
    "microphone",
    "midi",
    "on-device-speech-recognition",
    "otp-credentials",
    "payment",
    "picture-in-picture",
    "private-aggregation",
    "private-state-token-issuance",
    "private-state-token-redemption",
    "publickey-credentials-create",
    "publickey-credentials-get",
    "record-ad-auction-events",
    "rewriter",
    "run-ad-auction",
    "screen-wake-lock",
    "serial",
    "shared-storage",
    "shared-storage-select-url",
    "smart-card",
    "speaker-selection",
    "storage-access",
    "sub-apps",
    "summarizer",
    "sync-xhr",
    "translator",
    "unload",
    "usb",
    "usb-unrestricted",
    "vertical-scroll",
    "web-app-installation",
    "web-printing",
    "web-share",
    "window-management",
    "writer",
    "xr-spatial-tracking",
]

"""
Reason for a permissions policy feature to be disabled.
"""
PermissionsPolicyBlockReason = Literal[
    "Header", "IframeAttribute", "InFencedFrameTree", "InIsolatedApp"
]


@dataclass(kw_only=True)
class PermissionsPolicyBlockLocator(CDPModel):
    frame_id: FrameId
    block_reason: PermissionsPolicyBlockReason


@dataclass(kw_only=True)
class PermissionsPolicyFeatureState(CDPModel):
    feature: PermissionsPolicyFeature
    allowed: bool
    locator: PermissionsPolicyBlockLocator | None = None


"""
Origin Trial(https://www.chromium.org/blink/origin-trials) support. Status for an
Origin Trial token.
"""
OriginTrialTokenStatus = Literal[
    "Success",
    "NotSupported",
    "Insecure",
    "Expired",
    "WrongOrigin",
    "InvalidSignature",
    "Malformed",
    "WrongVersion",
    "FeatureDisabled",
    "TokenDisabled",
    "FeatureDisabledForUser",
    "UnknownTrial",
]

"""
Status for an Origin Trial.
"""
OriginTrialStatus = Literal[
    "Enabled", "ValidTokenNotProvided", "OSNotSupported", "TrialNotAllowed"
]

OriginTrialUsageRestriction = Literal["None", "Subset"]


@dataclass(kw_only=True)
class OriginTrialToken(CDPModel):
    origin: str
    match_sub_domains: bool
    trial_name: str
    expiry_time: network.TimeSinceEpoch
    is_third_party: bool
    usage_restriction: OriginTrialUsageRestriction


@dataclass(kw_only=True)
class OriginTrialTokenWithStatus(CDPModel):
    raw_token_text: str
    parsed_token: OriginTrialToken | None = None
    status: OriginTrialTokenStatus


@dataclass(kw_only=True)
class OriginTrial(CDPModel):
    trial_name: str
    status: OriginTrialStatus
    tokens_with_status: list[Any]


@dataclass(kw_only=True)
class SecurityOriginDetails(CDPModel):
    """
    Additional information about the frame document's security origin.
    """

    is_localhost: bool


@dataclass(kw_only=True)
class Frame(CDPModel):
    """
    Information about the Frame on the page.
    """

    id: FrameId
    parent_id: FrameId | None = None
    loader_id: network.LoaderId
    name: str | None = None
    url: str
    url_fragment: str | None = None
    domain_and_registry: str
    security_origin: str
    security_origin_details: SecurityOriginDetails | None = None
    mime_type: str
    unreachable_url: str | None = None
    ad_frame_status: AdFrameStatus | None = None
    secure_context_type: SecureContextType
    cross_origin_isolated_context_type: CrossOriginIsolatedContextType
    gated_api_features: list[Any]


@dataclass(kw_only=True)
class FrameResource(CDPModel):
    """
    Information about the Resource on the page.
    """

    url: str
    type: network.ResourceType
    mime_type: str
    last_modified: network.TimeSinceEpoch | None = None
    content_size: float | None = None
    failed: bool | None = None
    canceled: bool | None = None


@dataclass(kw_only=True)
class FrameResourceTree(CDPModel):
    """
    Information about the Frame hierarchy along with their cached resources.
    """

    frame: Frame
    child_frames: list[Any] | None = None
    resources: list[Any]


@dataclass(kw_only=True)
class FrameTree(CDPModel):
    """
    Information about the Frame hierarchy.
    """

    frame: Frame
    child_frames: list[Any] | None = None


"""
Unique script identifier.
"""
ScriptIdentifier = str

"""
Transition type.
"""
TransitionType = Literal[
    "link",
    "typed",
    "address_bar",
    "auto_bookmark",
    "auto_subframe",
    "manual_subframe",
    "generated",
    "auto_toplevel",
    "form_submit",
    "reload",
    "keyword",
    "keyword_generated",
    "other",
]


@dataclass(kw_only=True)
class NavigationEntry(CDPModel):
    """
    Navigation history entry.
    """

    id: int
    url: str
    user_typed_url: str
    title: str
    transition_type: TransitionType


@dataclass(kw_only=True)
class ScreencastFrameMetadata(CDPModel):
    """
    Screencast frame metadata.
    """

    offset_top: float
    page_scale_factor: float
    device_width: float
    device_height: float
    scroll_offset_x: float
    scroll_offset_y: float
    timestamp: network.TimeSinceEpoch | None = None


"""
Javascript dialog type.
"""
DialogType = Literal["alert", "confirm", "prompt", "beforeunload"]


@dataclass(kw_only=True)
class AppManifestError(CDPModel):
    """
    Error while paring app manifest.
    """

    message: str
    critical: int
    line: int
    column: int


@dataclass(kw_only=True)
class AppManifestParsedProperties(CDPModel):
    """
    Parsed app manifest properties.
    """

    scope: str


@dataclass(kw_only=True)
class LayoutViewport(CDPModel):
    """
    Layout viewport position and dimensions.
    """

    page_x: int
    page_y: int
    client_width: int
    client_height: int


@dataclass(kw_only=True)
class VisualViewport(CDPModel):
    """
    Visual viewport position, dimensions, and scale.
    """

    offset_x: float
    offset_y: float
    page_x: float
    page_y: float
    client_width: float
    client_height: float
    scale: float
    zoom: float | None = None


@dataclass(kw_only=True)
class Viewport(CDPModel):
    """
    Viewport for capturing screenshot.
    """

    x: float
    y: float
    width: float
    height: float
    scale: float


@dataclass(kw_only=True)
class FontFamilies(CDPModel):
    """
    Generic font families collection.
    """

    standard: str | None = None
    fixed: str | None = None
    serif: str | None = None
    sans_serif: str | None = None
    cursive: str | None = None
    fantasy: str | None = None
    math: str | None = None


@dataclass(kw_only=True)
class ScriptFontFamilies(CDPModel):
    """
    Font families collection for a script.
    """

    script: str
    font_families: FontFamilies


@dataclass(kw_only=True)
class FontSizes(CDPModel):
    """
    Default font sizes.
    """

    standard: int | None = None
    fixed: int | None = None


ClientNavigationReason = Literal[
    "anchorClick",
    "formSubmissionGet",
    "formSubmissionPost",
    "httpHeaderRefresh",
    "initialFrameNavigation",
    "metaTagRefresh",
    "other",
    "pageBlockInterstitial",
    "reload",
    "scriptInitiated",
]

ClientNavigationDisposition = Literal["currentTab", "newTab", "newWindow", "download"]


@dataclass(kw_only=True)
class InstallabilityErrorArgument(CDPModel):
    name: str
    value: str


@dataclass(kw_only=True)
class InstallabilityError(CDPModel):
    """
    The installability error
    """

    error_id: str
    error_arguments: list[Any]


"""
The referring-policy used for the navigation.
"""
ReferrerPolicy = Literal[
    "noReferrer",
    "noReferrerWhenDowngrade",
    "origin",
    "originWhenCrossOrigin",
    "sameOrigin",
    "strictOrigin",
    "strictOriginWhenCrossOrigin",
    "unsafeUrl",
]


@dataclass(kw_only=True)
class CompilationCacheParams(CDPModel):
    """
    Per-script compilation cache parameters for `Page.produceCompilationCache`
    """

    url: str
    eager: bool | None = None


@dataclass(kw_only=True)
class FileFilter(CDPModel):
    name: str | None = None
    accepts: list[Any] | None = None


@dataclass(kw_only=True)
class FileHandler(CDPModel):
    action: str
    name: str
    icons: list[Any] | None = None
    accepts: list[Any] | None = None
    launch_type: str


@dataclass(kw_only=True)
class ImageResource(CDPModel):
    """
    The image definition used in both icon and screenshot.
    """

    url: str
    sizes: str | None = None
    type: str | None = None


@dataclass(kw_only=True)
class LaunchHandler(CDPModel):
    client_mode: str


@dataclass(kw_only=True)
class ProtocolHandler(CDPModel):
    protocol: str
    url: str


@dataclass(kw_only=True)
class RelatedApplication(CDPModel):
    id: str | None = None
    url: str


@dataclass(kw_only=True)
class ScopeExtension(CDPModel):
    origin: str
    has_origin_wildcard: bool


@dataclass(kw_only=True)
class Screenshot(CDPModel):
    image: ImageResource
    form_factor: str
    label: str | None = None


@dataclass(kw_only=True)
class ShareTarget(CDPModel):
    action: str
    method: str
    enctype: str
    title: str | None = None
    text: str | None = None
    url: str | None = None
    files: list[Any] | None = None


@dataclass(kw_only=True)
class Shortcut(CDPModel):
    name: str
    url: str


@dataclass(kw_only=True)
class WebAppManifest(CDPModel):
    background_color: str | None = None
    description: str | None = None
    dir: str | None = None
    display: str | None = None
    display_overrides: list[Any] | None = None
    file_handlers: list[Any] | None = None
    icons: list[Any] | None = None
    id: str | None = None
    lang: str | None = None
    launch_handler: LaunchHandler | None = None
    name: str | None = None
    orientation: str | None = None
    prefer_related_applications: bool | None = None
    protocol_handlers: list[Any] | None = None
    related_applications: list[Any] | None = None
    scope: str | None = None
    scope_extensions: list[Any] | None = None
    screenshots: list[Any] | None = None
    share_target: ShareTarget | None = None
    short_name: str | None = None
    shortcuts: list[Any] | None = None
    start_url: str | None = None
    theme_color: str | None = None


"""
The type of a frameNavigated event.
"""
NavigationType = Literal["Navigation", "BackForwardCacheRestore"]

"""
List of not restored reasons for back-forward cache.
"""
BackForwardCacheNotRestoredReason = Literal[
    "NotPrimaryMainFrame",
    "BackForwardCacheDisabled",
    "RelatedActiveContentsExist",
    "HTTPStatusNotOK",
    "SchemeNotHTTPOrHTTPS",
    "Loading",
    "WasGrantedMediaAccess",
    "DisableForRenderFrameHostCalled",
    "DomainNotAllowed",
    "HTTPMethodNotGET",
    "SubframeIsNavigating",
    "Timeout",
    "CacheLimit",
    "JavaScriptExecution",
    "RendererProcessKilled",
    "RendererProcessCrashed",
    "SchedulerTrackedFeatureUsed",
    "ConflictingBrowsingInstance",
    "CacheFlushed",
    "ServiceWorkerVersionActivation",
    "SessionRestored",
    "ServiceWorkerPostMessage",
    "EnteredBackForwardCacheBeforeServiceWorkerHostAdded",
    "RenderFrameHostReused_SameSite",
    "RenderFrameHostReused_CrossSite",
    "ServiceWorkerClaim",
    "IgnoreEventAndEvict",
    "HaveInnerContents",
    "TimeoutPuttingInCache",
    "BackForwardCacheDisabledByLowMemory",
    "BackForwardCacheDisabledByCommandLine",
    "NetworkRequestDatapipeDrainedAsBytesConsumer",
    "NetworkRequestRedirected",
    "NetworkRequestTimeout",
    "NetworkExceedsBufferLimit",
    "NavigationCancelledWhileRestoring",
    "NotMostRecentNavigationEntry",
    "BackForwardCacheDisabledForPrerender",
    "UserAgentOverrideDiffers",
    "ForegroundCacheLimit",
    "ForwardCacheDisabled",
    "BrowsingInstanceNotSwapped",
    "BackForwardCacheDisabledForDelegate",
    "UnloadHandlerExistsInMainFrame",
    "UnloadHandlerExistsInSubFrame",
    "ServiceWorkerUnregistration",
    "CacheControlNoStore",
    "CacheControlNoStoreCookieModified",
    "CacheControlNoStoreHTTPOnlyCookieModified",
    "NoResponseHead",
    "Unknown",
    "ActivationNavigationsDisallowedForBug1234857",
    "ErrorDocument",
    "FencedFramesEmbedder",
    "CookieDisabled",
    "HTTPAuthRequired",
    "CookieFlushed",
    "BroadcastChannelOnMessage",
    "WebViewSettingsChanged",
    "WebViewJavaScriptObjectChanged",
    "WebViewMessageListenerInjected",
    "WebViewSafeBrowsingAllowlistChanged",
    "WebViewDocumentStartJavascriptChanged",
    "WebSocket",
    "WebTransport",
    "WebRTC",
    "MainResourceHasCacheControlNoStore",
    "MainResourceHasCacheControlNoCache",
    "SubresourceHasCacheControlNoStore",
    "SubresourceHasCacheControlNoCache",
    "ContainsPlugins",
    "DocumentLoaded",
    "OutstandingNetworkRequestOthers",
    "RequestedMIDIPermission",
    "RequestedAudioCapturePermission",
    "RequestedVideoCapturePermission",
    "RequestedBackForwardCacheBlockedSensors",
    "RequestedBackgroundWorkPermission",
    "BroadcastChannel",
    "WebXR",
    "SharedWorker",
    "SharedWorkerMessage",
    "SharedWorkerWithNoActiveClient",
    "WebLocks",
    "WebLocksContention",
    "WebHID",
    "WebBluetooth",
    "WebShare",
    "RequestedStorageAccessGrant",
    "WebNfc",
    "OutstandingNetworkRequestFetch",
    "OutstandingNetworkRequestXHR",
    "AppBanner",
    "Printing",
    "WebDatabase",
    "PictureInPicture",
    "SpeechRecognizer",
    "IdleManager",
    "PaymentManager",
    "SpeechSynthesis",
    "KeyboardLock",
    "WebOTPService",
    "OutstandingNetworkRequestDirectSocket",
    "InjectedJavascript",
    "InjectedStyleSheet",
    "KeepaliveRequest",
    "IndexedDBEvent",
    "Dummy",
    "JsNetworkRequestReceivedCacheControlNoStoreResource",
    "WebRTCUsedWithCCNS",
    "WebTransportUsedWithCCNS",
    "WebSocketUsedWithCCNS",
    "SmartCard",
    "LiveMediaStreamTrack",
    "UnloadHandler",
    "ParserAborted",
    "ContentSecurityHandler",
    "ContentWebAuthenticationAPI",
    "ContentFileChooser",
    "ContentSerial",
    "ContentFileSystemAccess",
    "ContentMediaDevicesDispatcherHost",
    "ContentWebBluetooth",
    "ContentWebUSB",
    "ContentMediaSessionService",
    "ContentScreenReader",
    "ContentDiscarded",
    "EmbedderPopupBlockerTabHelper",
    "EmbedderSafeBrowsingTriggeredPopupBlocker",
    "EmbedderSafeBrowsingThreatDetails",
    "EmbedderAppBannerManager",
    "EmbedderDomDistillerViewerSource",
    "EmbedderDomDistillerSelfDeletingRequestDelegate",
    "EmbedderOomInterventionTabHelper",
    "EmbedderOfflinePage",
    "EmbedderChromePasswordManagerClientBindCredentialManager",
    "EmbedderPermissionRequestManager",
    "EmbedderModalDialog",
    "EmbedderExtensions",
    "EmbedderExtensionMessaging",
    "EmbedderExtensionMessagingForOpenPort",
    "EmbedderExtensionSentMessageToCachedFrame",
    "RequestedByWebViewClient",
    "PostMessageByWebViewClient",
    "CacheControlNoStoreDeviceBoundSessionTerminated",
    "CacheLimitPrunedOnModerateMemoryPressure",
    "CacheLimitPrunedOnCriticalMemoryPressure",
]

"""
Types of not restored reasons for back-forward cache.
"""
BackForwardCacheNotRestoredReasonType = Literal[
    "SupportPending", "PageSupportNeeded", "Circumstantial"
]


@dataclass(kw_only=True)
class BackForwardCacheBlockingDetails(CDPModel):
    url: str | None = None
    function: str | None = None
    line_number: int
    column_number: int


@dataclass(kw_only=True)
class BackForwardCacheNotRestoredExplanation(CDPModel):
    type: BackForwardCacheNotRestoredReasonType
    reason: BackForwardCacheNotRestoredReason
    context: str | None = None
    details: list[Any] | None = None


@dataclass(kw_only=True)
class BackForwardCacheNotRestoredExplanationTree(CDPModel):
    url: str
    explanations: list[Any]
    children: list[Any]
