# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from cdpify.domains import dom
from cdpify.shared.models import CDPModel

from .types import (
    LayerId,
    PaintProfile,
    PictureTile,
    SnapshotId,
)


class LayerTreeCommand(StrEnum):
    COMPOSITING_REASONS = "LayerTree.compositingReasons"
    DISABLE = "LayerTree.disable"
    ENABLE = "LayerTree.enable"
    LOAD_SNAPSHOT = "LayerTree.loadSnapshot"
    MAKE_SNAPSHOT = "LayerTree.makeSnapshot"
    PROFILE_SNAPSHOT = "LayerTree.profileSnapshot"
    RELEASE_SNAPSHOT = "LayerTree.releaseSnapshot"
    REPLAY_SNAPSHOT = "LayerTree.replaySnapshot"
    SNAPSHOT_COMMAND_LOG = "LayerTree.snapshotCommandLog"


@dataclass(kw_only=True, slots=True)
class CompositingReasonsParams(CDPModel):
    """
    Provides the reasons why the given layer was composited.
    """

    layer_id: LayerId


@dataclass(kw_only=True, slots=True)
class CompositingReasonsResult(CDPModel):
    compositing_reasons: list[str]
    compositing_reason_ids: list[str]


@dataclass(kw_only=True, slots=True)
class LoadSnapshotParams(CDPModel):
    """
    Returns the snapshot identifier.
    """

    tiles: list[PictureTile]


@dataclass(kw_only=True, slots=True)
class LoadSnapshotResult(CDPModel):
    snapshot_id: SnapshotId


@dataclass(kw_only=True, slots=True)
class MakeSnapshotParams(CDPModel):
    """
    Returns the layer snapshot identifier.
    """

    layer_id: LayerId


@dataclass(kw_only=True, slots=True)
class MakeSnapshotResult(CDPModel):
    snapshot_id: SnapshotId


@dataclass(kw_only=True, slots=True)
class ProfileSnapshotParams(CDPModel):
    snapshot_id: SnapshotId
    min_repeat_count: int | None = None
    min_duration: float | None = None
    clip_rect: dom.Rect | None = None


@dataclass(kw_only=True, slots=True)
class ProfileSnapshotResult(CDPModel):
    timings: list[PaintProfile]


@dataclass(kw_only=True, slots=True)
class ReleaseSnapshotParams(CDPModel):
    """
    Releases layer snapshot captured by the back-end.
    """

    snapshot_id: SnapshotId


@dataclass(kw_only=True, slots=True)
class ReplaySnapshotParams(CDPModel):
    """
    Replays the layer snapshot and returns the resulting bitmap.
    """

    snapshot_id: SnapshotId
    from_step: int | None = None
    to_step: int | None = None
    scale: float | None = None


@dataclass(kw_only=True, slots=True)
class ReplaySnapshotResult(CDPModel):
    data_url: str


@dataclass(kw_only=True, slots=True)
class SnapshotCommandLogParams(CDPModel):
    """
    Replays the layer snapshot and returns canvas log.
    """

    snapshot_id: SnapshotId


@dataclass(kw_only=True, slots=True)
class SnapshotCommandLogResult(CDPModel):
    command_log: list[dict[str, Any]]
