# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.executor import CommandExecutor

from .commands import (
    CompositingReasonsParams,
    CompositingReasonsResult,
    LayerTreeCommand,
    LoadSnapshotParams,
    LoadSnapshotResult,
    MakeSnapshotParams,
    MakeSnapshotResult,
    ProfileSnapshotParams,
    ProfileSnapshotResult,
    ReleaseSnapshotParams,
    ReplaySnapshotParams,
    ReplaySnapshotResult,
    SnapshotCommandLogParams,
    SnapshotCommandLogResult,
)
from .types import (
    LayerId,
    PictureTile,
    SnapshotId,
)

if TYPE_CHECKING:
    from cdpify.domains import dom


class LayerTree:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    async def compositing_reasons(
        self,
        *,
        layer_id: LayerId,
    ) -> CompositingReasonsResult:
        """
        Provides the reasons why the given layer was composited.
        """
        params = CompositingReasonsParams(layer_id=layer_id)

        result = await self._executor.execute(
            method=LayerTreeCommand.COMPOSITING_REASONS,
            params=encode_cdp(params),
        )
        return decode_cdp(CompositingReasonsResult, result)

    async def disable(
        self,
    ) -> None:
        """
        Disables compositing tree inspection.
        """
        await self._executor.execute(
            method=LayerTreeCommand.DISABLE,
            params=None,
        )

    async def enable(
        self,
    ) -> None:
        """
        Enables compositing tree inspection.
        """
        await self._executor.execute(
            method=LayerTreeCommand.ENABLE,
            params=None,
        )

    async def load_snapshot(
        self,
        *,
        tiles: list[PictureTile],
    ) -> LoadSnapshotResult:
        """
        Returns the snapshot identifier.
        """
        params = LoadSnapshotParams(tiles=tiles)

        result = await self._executor.execute(
            method=LayerTreeCommand.LOAD_SNAPSHOT,
            params=encode_cdp(params),
        )
        return decode_cdp(LoadSnapshotResult, result)

    async def make_snapshot(
        self,
        *,
        layer_id: LayerId,
    ) -> MakeSnapshotResult:
        """
        Returns the layer snapshot identifier.
        """
        params = MakeSnapshotParams(layer_id=layer_id)

        result = await self._executor.execute(
            method=LayerTreeCommand.MAKE_SNAPSHOT,
            params=encode_cdp(params),
        )
        return decode_cdp(MakeSnapshotResult, result)

    async def profile_snapshot(
        self,
        *,
        snapshot_id: SnapshotId,
        min_repeat_count: int | None = None,
        min_duration: float | None = None,
        clip_rect: dom.Rect | None = None,
    ) -> ProfileSnapshotResult:
        params = ProfileSnapshotParams(
            snapshot_id=snapshot_id,
            min_repeat_count=min_repeat_count,
            min_duration=min_duration,
            clip_rect=clip_rect,
        )

        result = await self._executor.execute(
            method=LayerTreeCommand.PROFILE_SNAPSHOT,
            params=encode_cdp(params),
        )
        return decode_cdp(ProfileSnapshotResult, result)

    async def release_snapshot(
        self,
        *,
        snapshot_id: SnapshotId,
    ) -> None:
        """
        Releases layer snapshot captured by the back-end.
        """
        params = ReleaseSnapshotParams(snapshot_id=snapshot_id)

        await self._executor.execute(
            method=LayerTreeCommand.RELEASE_SNAPSHOT,
            params=encode_cdp(params),
        )

    async def replay_snapshot(
        self,
        *,
        snapshot_id: SnapshotId,
        from_step: int | None = None,
        to_step: int | None = None,
        scale: float | None = None,
    ) -> ReplaySnapshotResult:
        """
        Replays the layer snapshot and returns the resulting bitmap.
        """
        params = ReplaySnapshotParams(
            snapshot_id=snapshot_id, from_step=from_step, to_step=to_step, scale=scale
        )

        result = await self._executor.execute(
            method=LayerTreeCommand.REPLAY_SNAPSHOT,
            params=encode_cdp(params),
        )
        return decode_cdp(ReplaySnapshotResult, result)

    async def snapshot_command_log(
        self,
        *,
        snapshot_id: SnapshotId,
    ) -> SnapshotCommandLogResult:
        """
        Replays the layer snapshot and returns canvas log.
        """
        params = SnapshotCommandLogParams(snapshot_id=snapshot_id)

        result = await self._executor.execute(
            method=LayerTreeCommand.SNAPSHOT_COMMAND_LOG,
            params=encode_cdp(params),
        )
        return decode_cdp(SnapshotCommandLogResult, result)
