# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.domains import dom
from cdpify.shared.models import CDPEvent

from .types import (
    Layer,
    LayerId,
)


class LayerTreeEvent(StrEnum):
    LAYER_PAINTED = "LayerTree.layerPainted"
    LAYER_TREE_DID_CHANGE = "LayerTree.layerTreeDidChange"


@dataclass(kw_only=True, slots=True)
class LayerPaintedEvent(CDPEvent):
    layer_id: LayerId
    clip: dom.Rect


@dataclass(kw_only=True, slots=True)
class LayerTreeDidChangeEvent(CDPEvent):
    layers: list[Layer] | None = None
