# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP SystemInfo Domain."""

from .commands import (
    GetFeatureStateParams,
    GetFeatureStateResult,
    GetInfoResult,
    GetProcessInfoResult,
    SystemInfoCommand,
)
from .domain import SystemInfo
from .types import (
    GPUDevice,
    GPUInfo,
    ImageType,
    ProcessInfo,
    Size,
    SubsamplingFormat,
    VideoDecodeAcceleratorCapability,
    VideoEncodeAcceleratorCapability,
)

__all__ = [
    "GPUDevice",
    "GPUInfo",
    "GetFeatureStateParams",
    "GetFeatureStateResult",
    "GetInfoResult",
    "GetProcessInfoResult",
    "ImageType",
    "ProcessInfo",
    "Size",
    "SubsamplingFormat",
    "SystemInfo",
    "SystemInfoCommand",
    "VideoDecodeAcceleratorCapability",
    "VideoEncodeAcceleratorCapability",
]
