# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from .accessibility import Accessibility
from .accessors import CDPDomains
from .ads import Ads
from .animation import Animation
from .audits import Audits
from .autofill import Autofill
from .backgroundservice import BackgroundService
from .bluetoothemulation import BluetoothEmulation
from .browser import Browser
from .cachestorage import CacheStorage
from .cast import Cast
from .console import Console
from .crashreportcontext import CrashReportContext
from .css import CSS
from .debugger import Debugger
from .deviceaccess import DeviceAccess
from .deviceorientation import DeviceOrientation
from .digitalcredentials import DigitalCredentials
from .dom import DOM
from .domdebugger import DOMDebugger
from .domsnapshot import DOMSnapshot
from .domstorage import DOMStorage
from .emulation import Emulation
from .eventbreakpoints import EventBreakpoints
from .extensions import Extensions
from .fedcm import FedCm
from .fetch import Fetch
from .filesystem import FileSystem
from .headlessexperimental import HeadlessExperimental
from .heapprofiler import HeapProfiler
from .indexeddb import IndexedDB
from .input import Input
from .inspector import Inspector
from .io import IO
from .layertree import LayerTree
from .log import Log
from .media import Media
from .memory import Memory
from .network import Network
from .overlay import Overlay
from .page import Page
from .performance import Performance
from .performancetimeline import PerformanceTimeline
from .preload import Preload
from .profiler import Profiler
from .pwa import PWA
from .runtime import Runtime
from .schema import Schema
from .security import Security
from .serviceworker import ServiceWorker
from .smartcardemulation import SmartCardEmulation
from .storage import Storage
from .systeminfo import SystemInfo
from .target import Target
from .tethering import Tethering
from .tracing import Tracing
from .webaudio import WebAudio
from .webauthn import WebAuthn
from .webmcp import WebMCP

__all__ = [
    "CDPDomains",
    "Accessibility",
    "Ads",
    "Animation",
    "Audits",
    "Autofill",
    "BackgroundService",
    "BluetoothEmulation",
    "Browser",
    "CSS",
    "CacheStorage",
    "Cast",
    "CrashReportContext",
    "DOM",
    "DOMDebugger",
    "DOMSnapshot",
    "DOMStorage",
    "DeviceAccess",
    "DeviceOrientation",
    "DigitalCredentials",
    "Emulation",
    "EventBreakpoints",
    "Extensions",
    "FedCm",
    "Fetch",
    "FileSystem",
    "HeadlessExperimental",
    "IO",
    "IndexedDB",
    "Input",
    "Inspector",
    "LayerTree",
    "Log",
    "Media",
    "Memory",
    "Network",
    "Overlay",
    "PWA",
    "Page",
    "Performance",
    "PerformanceTimeline",
    "Preload",
    "Security",
    "ServiceWorker",
    "SmartCardEmulation",
    "Storage",
    "SystemInfo",
    "Target",
    "Tethering",
    "Tracing",
    "WebAudio",
    "WebAuthn",
    "WebMCP",
    "Console",
    "Debugger",
    "HeapProfiler",
    "Profiler",
    "Runtime",
    "Schema",
]
