# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from cdpify.domains import browser, network, page
from cdpify.shared.models import CDPModel

from .types import (
    RelatedWebsiteSet,
    SerializedStorageKey,
    SharedStorageEntry,
    SharedStorageMetadata,
    StorageBucket,
    TrustTokens,
    UsageForType,
)


class StorageCommand(StrEnum):
    GET_STORAGE_KEY_FOR_FRAME = "Storage.getStorageKeyForFrame"
    GET_STORAGE_KEY = "Storage.getStorageKey"
    CLEAR_DATA_FOR_ORIGIN = "Storage.clearDataForOrigin"
    CLEAR_DATA_FOR_STORAGE_KEY = "Storage.clearDataForStorageKey"
    GET_COOKIES = "Storage.getCookies"
    SET_COOKIES = "Storage.setCookies"
    CLEAR_COOKIES = "Storage.clearCookies"
    GET_USAGE_AND_QUOTA = "Storage.getUsageAndQuota"
    OVERRIDE_QUOTA_FOR_ORIGIN = "Storage.overrideQuotaForOrigin"
    TRACK_CACHE_STORAGE_FOR_ORIGIN = "Storage.trackCacheStorageForOrigin"
    TRACK_CACHE_STORAGE_FOR_STORAGE_KEY = "Storage.trackCacheStorageForStorageKey"
    TRACK_INDEXED_DB_FOR_ORIGIN = "Storage.trackIndexedDBForOrigin"
    TRACK_INDEXED_DB_FOR_STORAGE_KEY = "Storage.trackIndexedDBForStorageKey"
    UNTRACK_CACHE_STORAGE_FOR_ORIGIN = "Storage.untrackCacheStorageForOrigin"
    UNTRACK_CACHE_STORAGE_FOR_STORAGE_KEY = "Storage.untrackCacheStorageForStorageKey"
    UNTRACK_INDEXED_DB_FOR_ORIGIN = "Storage.untrackIndexedDBForOrigin"
    UNTRACK_INDEXED_DB_FOR_STORAGE_KEY = "Storage.untrackIndexedDBForStorageKey"
    GET_TRUST_TOKENS = "Storage.getTrustTokens"
    CLEAR_TRUST_TOKENS = "Storage.clearTrustTokens"
    GET_INTEREST_GROUP_DETAILS = "Storage.getInterestGroupDetails"
    SET_INTEREST_GROUP_TRACKING = "Storage.setInterestGroupTracking"
    SET_INTEREST_GROUP_AUCTION_TRACKING = "Storage.setInterestGroupAuctionTracking"
    GET_SHARED_STORAGE_METADATA = "Storage.getSharedStorageMetadata"
    GET_SHARED_STORAGE_ENTRIES = "Storage.getSharedStorageEntries"
    SET_SHARED_STORAGE_ENTRY = "Storage.setSharedStorageEntry"
    DELETE_SHARED_STORAGE_ENTRY = "Storage.deleteSharedStorageEntry"
    CLEAR_SHARED_STORAGE_ENTRIES = "Storage.clearSharedStorageEntries"
    RESET_SHARED_STORAGE_BUDGET = "Storage.resetSharedStorageBudget"
    SET_SHARED_STORAGE_TRACKING = "Storage.setSharedStorageTracking"
    SET_STORAGE_BUCKET_TRACKING = "Storage.setStorageBucketTracking"
    DELETE_STORAGE_BUCKET = "Storage.deleteStorageBucket"
    RUN_BOUNCE_TRACKING_MITIGATIONS = "Storage.runBounceTrackingMitigations"
    GET_RELATED_WEBSITE_SETS = "Storage.getRelatedWebsiteSets"
    SET_PROTECTED_AUDIENCE_K_ANONYMITY = "Storage.setProtectedAudienceKAnonymity"


@dataclass(kw_only=True, slots=True)
class GetStorageKeyForFrameParams(CDPModel):
    """
    Returns a storage key given a frame id. Deprecated. Please use
    Storage.getStorageKey instead.
    """

    frame_id: page.FrameId


@dataclass(kw_only=True, slots=True)
class GetStorageKeyForFrameResult(CDPModel):
    storage_key: SerializedStorageKey


@dataclass(kw_only=True, slots=True)
class GetStorageKeyParams(CDPModel):
    """
    Returns storage key for the given frame. If no frame ID is provided, the storage
    key of the target executing this command is returned.
    """

    frame_id: page.FrameId | None = None


@dataclass(kw_only=True, slots=True)
class GetStorageKeyResult(CDPModel):
    storage_key: SerializedStorageKey


@dataclass(kw_only=True, slots=True)
class ClearDataForOriginParams(CDPModel):
    """
    Clears storage for origin.
    """

    origin: str
    storage_types: str


@dataclass(kw_only=True, slots=True)
class ClearDataForStorageKeyParams(CDPModel):
    """
    Clears storage for storage key.
    """

    storage_key: str
    storage_types: str


@dataclass(kw_only=True, slots=True)
class GetCookiesParams(CDPModel):
    """
    Returns all browser cookies.
    """

    browser_context_id: browser.BrowserContextID | None = None


@dataclass(kw_only=True, slots=True)
class GetCookiesResult(CDPModel):
    cookies: list[network.Cookie]


@dataclass(kw_only=True, slots=True)
class SetCookiesParams(CDPModel):
    """
    Sets given cookies.
    """

    cookies: list[network.CookieParam]
    browser_context_id: browser.BrowserContextID | None = None


@dataclass(kw_only=True, slots=True)
class ClearCookiesParams(CDPModel):
    """
    Clears cookies.
    """

    browser_context_id: browser.BrowserContextID | None = None


@dataclass(kw_only=True, slots=True)
class GetUsageAndQuotaParams(CDPModel):
    """
    Returns usage and quota in bytes.
    """

    origin: str


@dataclass(kw_only=True, slots=True)
class GetUsageAndQuotaResult(CDPModel):
    usage: float
    quota: float
    override_active: bool
    usage_breakdown: list[UsageForType]


@dataclass(kw_only=True, slots=True)
class OverrideQuotaForOriginParams(CDPModel):
    """
    Override quota for the specified origin
    """

    origin: str
    quota_size: float | None = None


@dataclass(kw_only=True, slots=True)
class TrackCacheStorageForOriginParams(CDPModel):
    """
    Registers origin to be notified when an update occurs to its cache storage list.
    """

    origin: str


@dataclass(kw_only=True, slots=True)
class TrackCacheStorageForStorageKeyParams(CDPModel):
    """
    Registers storage key to be notified when an update occurs to its cache storage
    list.
    """

    storage_key: str


@dataclass(kw_only=True, slots=True)
class TrackIndexedDBForOriginParams(CDPModel):
    """
    Registers origin to be notified when an update occurs to its IndexedDB.
    """

    origin: str


@dataclass(kw_only=True, slots=True)
class TrackIndexedDBForStorageKeyParams(CDPModel):
    """
    Registers storage key to be notified when an update occurs to its IndexedDB.
    """

    storage_key: str


@dataclass(kw_only=True, slots=True)
class UntrackCacheStorageForOriginParams(CDPModel):
    """
    Unregisters origin from receiving notifications for cache storage.
    """

    origin: str


@dataclass(kw_only=True, slots=True)
class UntrackCacheStorageForStorageKeyParams(CDPModel):
    """
    Unregisters storage key from receiving notifications for cache storage.
    """

    storage_key: str


@dataclass(kw_only=True, slots=True)
class UntrackIndexedDBForOriginParams(CDPModel):
    """
    Unregisters origin from receiving notifications for IndexedDB.
    """

    origin: str


@dataclass(kw_only=True, slots=True)
class UntrackIndexedDBForStorageKeyParams(CDPModel):
    """
    Unregisters storage key from receiving notifications for IndexedDB.
    """

    storage_key: str


@dataclass(kw_only=True, slots=True)
class GetTrustTokensResult(CDPModel):
    tokens: list[TrustTokens]


@dataclass(kw_only=True, slots=True)
class ClearTrustTokensParams(CDPModel):
    """
    Removes all Trust Tokens issued by the provided issuerOrigin. Leaves other stored
    data, including the issuer's Redemption Records, intact.
    """

    issuer_origin: str


@dataclass(kw_only=True, slots=True)
class ClearTrustTokensResult(CDPModel):
    did_delete_tokens: bool


@dataclass(kw_only=True, slots=True)
class GetInterestGroupDetailsParams(CDPModel):
    """
    Gets details for a named interest group.
    """

    owner_origin: str
    name: str


@dataclass(kw_only=True, slots=True)
class GetInterestGroupDetailsResult(CDPModel):
    details: dict[str, Any]


@dataclass(kw_only=True, slots=True)
class SetInterestGroupTrackingParams(CDPModel):
    """
    Enables/Disables issuing of interestGroupAccessed events.
    """

    enable: bool


@dataclass(kw_only=True, slots=True)
class SetInterestGroupAuctionTrackingParams(CDPModel):
    """
    Enables/Disables issuing of interestGroupAuctionEventOccurred and
    interestGroupAuctionNetworkRequestCreated.
    """

    enable: bool


@dataclass(kw_only=True, slots=True)
class GetSharedStorageMetadataParams(CDPModel):
    """
    Gets metadata for an origin's shared storage.
    """

    owner_origin: str


@dataclass(kw_only=True, slots=True)
class GetSharedStorageMetadataResult(CDPModel):
    metadata: SharedStorageMetadata


@dataclass(kw_only=True, slots=True)
class GetSharedStorageEntriesParams(CDPModel):
    """
    Gets the entries in an given origin's shared storage.
    """

    owner_origin: str


@dataclass(kw_only=True, slots=True)
class GetSharedStorageEntriesResult(CDPModel):
    entries: list[SharedStorageEntry]


@dataclass(kw_only=True, slots=True)
class SetSharedStorageEntryParams(CDPModel):
    """
    Sets entry with `key` and `value` for a given origin's shared storage.
    """

    owner_origin: str
    key: str
    value: str
    ignore_if_present: bool | None = None


@dataclass(kw_only=True, slots=True)
class DeleteSharedStorageEntryParams(CDPModel):
    """
    Deletes entry for `key` (if it exists) for a given origin's shared storage.
    """

    owner_origin: str
    key: str


@dataclass(kw_only=True, slots=True)
class ClearSharedStorageEntriesParams(CDPModel):
    """
    Clears all entries for a given origin's shared storage.
    """

    owner_origin: str


@dataclass(kw_only=True, slots=True)
class ResetSharedStorageBudgetParams(CDPModel):
    """
    Resets the budget for `ownerOrigin` by clearing all budget withdrawals.
    """

    owner_origin: str


@dataclass(kw_only=True, slots=True)
class SetSharedStorageTrackingParams(CDPModel):
    """
    Enables/disables issuing of sharedStorageAccessed events.
    """

    enable: bool


@dataclass(kw_only=True, slots=True)
class SetStorageBucketTrackingParams(CDPModel):
    """
    Set tracking for a storage key's buckets.
    """

    storage_key: str
    enable: bool


@dataclass(kw_only=True, slots=True)
class DeleteStorageBucketParams(CDPModel):
    """
    Deletes the Storage Bucket with the given storage key and bucket name.
    """

    bucket: StorageBucket


@dataclass(kw_only=True, slots=True)
class RunBounceTrackingMitigationsResult(CDPModel):
    deleted_sites: list[str]


@dataclass(kw_only=True, slots=True)
class GetRelatedWebsiteSetsResult(CDPModel):
    sets: list[RelatedWebsiteSet]


@dataclass(kw_only=True, slots=True)
class SetProtectedAudienceKAnonymityParams(CDPModel):
    owner: str
    name: str
    hashes: list[str]
