# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from .types import (
    StorageBucketInfo,
)


class StorageEvent(StrEnum):
    CACHE_STORAGE_CONTENT_UPDATED = "Storage.cacheStorageContentUpdated"
    CACHE_STORAGE_LIST_UPDATED = "Storage.cacheStorageListUpdated"
    INDEXED_DB_CONTENT_UPDATED = "Storage.indexedDBContentUpdated"
    INDEXED_DB_LIST_UPDATED = "Storage.indexedDBListUpdated"
    STORAGE_BUCKET_CREATED_OR_UPDATED = "Storage.storageBucketCreatedOrUpdated"
    STORAGE_BUCKET_DELETED = "Storage.storageBucketDeleted"


@dataclass(kw_only=True, slots=True)
class CacheStorageContentUpdatedEvent:
    """
    A cache's contents have been modified.
    """

    origin: str = field(metadata={"cdp_name": "origin"})
    storage_key: str = field(metadata={"cdp_name": "storageKey"})
    bucket_id: str = field(metadata={"cdp_name": "bucketId"})
    cache_name: str = field(metadata={"cdp_name": "cacheName"})


@dataclass(kw_only=True, slots=True)
class CacheStorageListUpdatedEvent:
    """
    A cache has been added/deleted.
    """

    origin: str = field(metadata={"cdp_name": "origin"})
    storage_key: str = field(metadata={"cdp_name": "storageKey"})
    bucket_id: str = field(metadata={"cdp_name": "bucketId"})


@dataclass(kw_only=True, slots=True)
class IndexedDBContentUpdatedEvent:
    """
    The origin's IndexedDB object store has been modified.
    """

    origin: str = field(metadata={"cdp_name": "origin"})
    storage_key: str = field(metadata={"cdp_name": "storageKey"})
    bucket_id: str = field(metadata={"cdp_name": "bucketId"})
    database_name: str = field(metadata={"cdp_name": "databaseName"})
    object_store_name: str = field(metadata={"cdp_name": "objectStoreName"})


@dataclass(kw_only=True, slots=True)
class IndexedDBListUpdatedEvent:
    """
    The origin's IndexedDB database list has been modified.
    """

    origin: str = field(metadata={"cdp_name": "origin"})
    storage_key: str = field(metadata={"cdp_name": "storageKey"})
    bucket_id: str = field(metadata={"cdp_name": "bucketId"})


@dataclass(kw_only=True, slots=True)
class StorageBucketCreatedOrUpdatedEvent:
    bucket_info: StorageBucketInfo = field(metadata={"cdp_name": "bucketInfo"})


@dataclass(kw_only=True, slots=True)
class StorageBucketDeletedEvent:
    bucket_id: str = field(metadata={"cdp_name": "bucketId"})
