# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from cdpify.domains import network
from cdpify.shared.models import CDPModel

SerializedStorageKey = str

"""
Enum of possible storage types.
"""
type StorageType = Literal[
    "cookies",
    "file_systems",
    "indexeddb",
    "local_storage",
    "shader_cache",
    "websql",
    "service_workers",
    "cache_storage",
    "storage_buckets",
    "all",
    "other",
]


@dataclass(kw_only=True, slots=True)
class UsageForType(CDPModel):
    """
    Usage for a storage type.
    """

    storage_type: StorageType
    usage: float


@dataclass(kw_only=True, slots=True)
class TrustTokens(CDPModel):
    """
    Pair of issuer origin and number of available (signed, but not used) Trust Tokens
    from that issuer.
    """

    issuer_origin: str
    count: float


type StorageBucketsDurability = Literal["relaxed", "strict"]


@dataclass(kw_only=True, slots=True)
class StorageBucket(CDPModel):
    storage_key: SerializedStorageKey
    name: str | None = None


@dataclass(kw_only=True, slots=True)
class StorageBucketInfo(CDPModel):
    bucket: StorageBucket
    id: str
    expiration: network.TimeSinceEpoch
    quota: float
    persistent: bool
    durability: StorageBucketsDurability


@dataclass(kw_only=True, slots=True)
class RelatedWebsiteSet(CDPModel):
    """
    A single Related Website Set object.
    """

    primary_sites: list[str]
    associated_sites: list[str]
    service_sites: list[str]
