# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.codec import encode_cdp
from cdpify.executor import CommandExecutor

from .commands import (
    DeliverPushMessageParams,
    DispatchPeriodicSyncEventParams,
    DispatchSyncEventParams,
    ServiceWorkerCommand,
    SetForceUpdateOnPageLoadParams,
    SkipWaitingParams,
    StartWorkerParams,
    StopWorkerParams,
    UnregisterParams,
    UpdateRegistrationParams,
)
from .types import (
    RegistrationID,
)


class ServiceWorker:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    async def deliver_push_message(
        self,
        *,
        origin: str,
        registration_id: RegistrationID,
        data: str,
    ) -> None:
        params = DeliverPushMessageParams(
            origin=origin, registration_id=registration_id, data=data
        )

        await self._executor.execute(
            method=ServiceWorkerCommand.DELIVER_PUSH_MESSAGE,
            params=encode_cdp(params),
        )

    async def disable(
        self,
    ) -> None:
        await self._executor.execute(
            method=ServiceWorkerCommand.DISABLE,
            params=None,
        )

    async def dispatch_sync_event(
        self,
        *,
        origin: str,
        registration_id: RegistrationID,
        tag: str,
        last_chance: bool,
    ) -> None:
        params = DispatchSyncEventParams(
            origin=origin,
            registration_id=registration_id,
            tag=tag,
            last_chance=last_chance,
        )

        await self._executor.execute(
            method=ServiceWorkerCommand.DISPATCH_SYNC_EVENT,
            params=encode_cdp(params),
        )

    async def dispatch_periodic_sync_event(
        self,
        *,
        origin: str,
        registration_id: RegistrationID,
        tag: str,
    ) -> None:
        params = DispatchPeriodicSyncEventParams(
            origin=origin, registration_id=registration_id, tag=tag
        )

        await self._executor.execute(
            method=ServiceWorkerCommand.DISPATCH_PERIODIC_SYNC_EVENT,
            params=encode_cdp(params),
        )

    async def enable(
        self,
    ) -> None:
        await self._executor.execute(
            method=ServiceWorkerCommand.ENABLE,
            params=None,
        )

    async def set_force_update_on_page_load(
        self,
        *,
        force_update_on_page_load: bool,
    ) -> None:
        params = SetForceUpdateOnPageLoadParams(
            force_update_on_page_load=force_update_on_page_load
        )

        await self._executor.execute(
            method=ServiceWorkerCommand.SET_FORCE_UPDATE_ON_PAGE_LOAD,
            params=encode_cdp(params),
        )

    async def skip_waiting(
        self,
        *,
        scope_url: str,
    ) -> None:
        params = SkipWaitingParams(scope_url=scope_url)

        await self._executor.execute(
            method=ServiceWorkerCommand.SKIP_WAITING,
            params=encode_cdp(params),
        )

    async def start_worker(
        self,
        *,
        scope_url: str,
    ) -> None:
        params = StartWorkerParams(scope_url=scope_url)

        await self._executor.execute(
            method=ServiceWorkerCommand.START_WORKER,
            params=encode_cdp(params),
        )

    async def stop_all_workers(
        self,
    ) -> None:
        await self._executor.execute(
            method=ServiceWorkerCommand.STOP_ALL_WORKERS,
            params=None,
        )

    async def stop_worker(
        self,
        *,
        version_id: str,
    ) -> None:
        params = StopWorkerParams(version_id=version_id)

        await self._executor.execute(
            method=ServiceWorkerCommand.STOP_WORKER,
            params=encode_cdp(params),
        )

    async def unregister(
        self,
        *,
        scope_url: str,
    ) -> None:
        params = UnregisterParams(scope_url=scope_url)

        await self._executor.execute(
            method=ServiceWorkerCommand.UNREGISTER,
            params=encode_cdp(params),
        )

    async def update_registration(
        self,
        *,
        scope_url: str,
    ) -> None:
        params = UpdateRegistrationParams(scope_url=scope_url)

        await self._executor.execute(
            method=ServiceWorkerCommand.UPDATE_REGISTRATION,
            params=encode_cdp(params),
        )
