# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    DeliverPushMessageParams,
    DispatchPeriodicSyncEventParams,
    DispatchSyncEventParams,
    ServiceWorkerCommand,
    SetForceUpdateOnPageLoadParams,
    SkipWaitingParams,
    StartWorkerParams,
    StopWorkerParams,
    UnregisterParams,
    UpdateRegistrationParams,
)
from .types import (
    RegistrationID,
)


class ServiceWorker:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def deliver_push_message(
        self,
        *,
        origin: str,
        registration_id: RegistrationID,
        data: str,
        session_id: str | None = None,
    ) -> None:
        params = DeliverPushMessageParams(
            origin=origin, registration_id=registration_id, data=data
        )

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.DELIVER_PUSH_MESSAGE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def disable(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.DISABLE,
            params=None,
            session_id=session_id,
        )

    async def dispatch_sync_event(
        self,
        *,
        origin: str,
        registration_id: RegistrationID,
        tag: str,
        last_chance: bool,
        session_id: str | None = None,
    ) -> None:
        params = DispatchSyncEventParams(
            origin=origin,
            registration_id=registration_id,
            tag=tag,
            last_chance=last_chance,
        )

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.DISPATCH_SYNC_EVENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def dispatch_periodic_sync_event(
        self,
        *,
        origin: str,
        registration_id: RegistrationID,
        tag: str,
        session_id: str | None = None,
    ) -> None:
        params = DispatchPeriodicSyncEventParams(
            origin=origin, registration_id=registration_id, tag=tag
        )

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.DISPATCH_PERIODIC_SYNC_EVENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def enable(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.ENABLE,
            params=None,
            session_id=session_id,
        )

    async def set_force_update_on_page_load(
        self,
        *,
        force_update_on_page_load: bool,
        session_id: str | None = None,
    ) -> None:
        params = SetForceUpdateOnPageLoadParams(
            force_update_on_page_load=force_update_on_page_load
        )

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.SET_FORCE_UPDATE_ON_PAGE_LOAD,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def skip_waiting(
        self,
        *,
        scope_url: str,
        session_id: str | None = None,
    ) -> None:
        params = SkipWaitingParams(scope_url=scope_url)

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.SKIP_WAITING,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def start_worker(
        self,
        *,
        scope_url: str,
        session_id: str | None = None,
    ) -> None:
        params = StartWorkerParams(scope_url=scope_url)

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.START_WORKER,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def stop_all_workers(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.STOP_ALL_WORKERS,
            params=None,
            session_id=session_id,
        )

    async def stop_worker(
        self,
        *,
        version_id: str,
        session_id: str | None = None,
    ) -> None:
        params = StopWorkerParams(version_id=version_id)

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.STOP_WORKER,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def unregister(
        self,
        *,
        scope_url: str,
        session_id: str | None = None,
    ) -> None:
        params = UnregisterParams(scope_url=scope_url)

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.UNREGISTER,
            params=params.to_cdp_params(),
            session_id=session_id,
        )

    async def update_registration(
        self,
        *,
        scope_url: str,
        session_id: str | None = None,
    ) -> None:
        params = UpdateRegistrationParams(scope_url=scope_url)

        await self._command_sender.send_raw(
            method=ServiceWorkerCommand.UPDATE_REGISTRATION,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
