# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.shared.models import CDPEvent

from .types import (
    ServiceWorkerErrorMessage,
    ServiceWorkerRegistration,
    ServiceWorkerVersion,
)


class ServiceWorkerEvent(StrEnum):
    WORKER_ERROR_REPORTED = "ServiceWorker.workerErrorReported"
    WORKER_REGISTRATION_UPDATED = "ServiceWorker.workerRegistrationUpdated"
    WORKER_VERSION_UPDATED = "ServiceWorker.workerVersionUpdated"


@dataclass(kw_only=True, slots=True)
class WorkerErrorReportedEvent(CDPEvent):
    error_message: ServiceWorkerErrorMessage


@dataclass(kw_only=True, slots=True)
class WorkerRegistrationUpdatedEvent(CDPEvent):
    registrations: list[ServiceWorkerRegistration]


@dataclass(kw_only=True, slots=True)
class WorkerVersionUpdatedEvent(CDPEvent):
    versions: list[ServiceWorkerVersion]
