# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from cdpify.shared.models import CDPModel

"""
Indicates the various states of Central.
"""
type CentralState = Literal["absent", "powered-off", "powered-on"]

"""
Indicates the various types of GATT event.
"""
type GATTOperationType = Literal["connection", "discovery"]

"""
Indicates the various types of characteristic write.
"""
type CharacteristicWriteType = Literal[
    "write-default-deprecated", "write-with-response", "write-without-response"
]

"""
Indicates the various types of characteristic operation.
"""
type CharacteristicOperationType = Literal[
    "read", "write", "subscribe-to-notifications", "unsubscribe-from-notifications"
]

"""
Indicates the various types of descriptor operation.
"""
type DescriptorOperationType = Literal["read", "write"]


@dataclass(kw_only=True, slots=True)
class ManufacturerData(CDPModel):
    """
    Stores the manufacturer data
    """

    key: int
    data: str


@dataclass(kw_only=True, slots=True)
class ScanRecord(CDPModel):
    """
    Stores the byte data of the advertisement packet sent by a Bluetooth device.
    """

    name: str | None = None
    uuids: list[str] | None = None
    appearance: int | None = None
    tx_power: int | None = None
    manufacturer_data: list[ManufacturerData] | None = None


@dataclass(kw_only=True, slots=True)
class ScanEntry(CDPModel):
    """
    Stores the advertisement packet information that is sent by a Bluetooth device.
    """

    device_address: str
    rssi: int
    scan_record: ScanRecord


@dataclass(kw_only=True, slots=True)
class CharacteristicProperties(CDPModel):
    """
    Describes the properties of a characteristic. This follows Bluetooth Core
    Specification BT 4.2 Vol 3 Part G 3.3.1. Characteristic Properties.
    """

    broadcast: bool | None = None
    read: bool | None = None
    write_without_response: bool | None = None
    write: bool | None = None
    notify: bool | None = None
    indicate: bool | None = None
    authenticated_signed_writes: bool | None = None
    extended_properties: bool | None = None
