# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

"""
Indicates the various states of Central.
"""
type CentralState = Literal["absent", "powered-off", "powered-on"]

"""
Indicates the various types of GATT event.
"""
type GATTOperationType = Literal["connection", "discovery"]

"""
Indicates the various types of characteristic write.
"""
type CharacteristicWriteType = Literal[
    "write-default-deprecated", "write-with-response", "write-without-response"
]

"""
Indicates the various types of characteristic operation.
"""
type CharacteristicOperationType = Literal[
    "read", "write", "subscribe-to-notifications", "unsubscribe-from-notifications"
]

"""
Indicates the various types of descriptor operation.
"""
type DescriptorOperationType = Literal["read", "write"]


@dataclass(kw_only=True, slots=True)
class ManufacturerData:
    """
    Stores the manufacturer data
    """

    key: int = field(metadata={"cdp_name": "key"})
    data: str = field(metadata={"cdp_name": "data"})


@dataclass(kw_only=True, slots=True)
class ScanRecord:
    """
    Stores the byte data of the advertisement packet sent by a Bluetooth device.
    """

    name: str | None = field(default=None, metadata={"cdp_name": "name"})
    uuids: list[str] | None = field(default=None, metadata={"cdp_name": "uuids"})
    appearance: int | None = field(default=None, metadata={"cdp_name": "appearance"})
    tx_power: int | None = field(default=None, metadata={"cdp_name": "txPower"})
    manufacturer_data: list[ManufacturerData] | None = field(
        default=None, metadata={"cdp_name": "manufacturerData"}
    )


@dataclass(kw_only=True, slots=True)
class ScanEntry:
    """
    Stores the advertisement packet information that is sent by a Bluetooth device.
    """

    device_address: str = field(metadata={"cdp_name": "deviceAddress"})
    rssi: int = field(metadata={"cdp_name": "rssi"})
    scan_record: ScanRecord = field(metadata={"cdp_name": "scanRecord"})


@dataclass(kw_only=True, slots=True)
class CharacteristicProperties:
    """
    Describes the properties of a characteristic. This follows Bluetooth Core
    Specification BT 4.2 Vol 3 Part G 3.3.1. Characteristic Properties.
    """

    broadcast: bool | None = field(default=None, metadata={"cdp_name": "broadcast"})
    read: bool | None = field(default=None, metadata={"cdp_name": "read"})
    write_without_response: bool | None = field(
        default=None, metadata={"cdp_name": "writeWithoutResponse"}
    )
    write: bool | None = field(default=None, metadata={"cdp_name": "write"})
    notify: bool | None = field(default=None, metadata={"cdp_name": "notify"})
    indicate: bool | None = field(default=None, metadata={"cdp_name": "indicate"})
    authenticated_signed_writes: bool | None = field(
        default=None, metadata={"cdp_name": "authenticatedSignedWrites"}
    )
    extended_properties: bool | None = field(
        default=None, metadata={"cdp_name": "extendedProperties"}
    )
