# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from .types import (
    AuthenticatorId,
    Credential,
    VirtualAuthenticatorOptions,
)


class WebAuthnCommand(StrEnum):
    ENABLE = "WebAuthn.enable"
    DISABLE = "WebAuthn.disable"
    ADD_VIRTUAL_AUTHENTICATOR = "WebAuthn.addVirtualAuthenticator"
    SET_RESPONSE_OVERRIDE_BITS = "WebAuthn.setResponseOverrideBits"
    REMOVE_VIRTUAL_AUTHENTICATOR = "WebAuthn.removeVirtualAuthenticator"
    ADD_CREDENTIAL = "WebAuthn.addCredential"
    GET_CREDENTIAL = "WebAuthn.getCredential"
    GET_CREDENTIALS = "WebAuthn.getCredentials"
    REMOVE_CREDENTIAL = "WebAuthn.removeCredential"
    CLEAR_CREDENTIALS = "WebAuthn.clearCredentials"
    SET_USER_VERIFIED = "WebAuthn.setUserVerified"
    SET_AUTOMATIC_PRESENCE_SIMULATION = "WebAuthn.setAutomaticPresenceSimulation"
    SET_CREDENTIAL_PROPERTIES = "WebAuthn.setCredentialProperties"


@dataclass(kw_only=True, slots=True)
class EnableParams:
    """
    Enable the WebAuthn domain and start intercepting credential storage and retrieval
    with a virtual authenticator.
    """

    enable_ui: bool | None = field(default=None, metadata={"cdp_name": "enableUI"})


@dataclass(kw_only=True, slots=True)
class AddVirtualAuthenticatorParams:
    """
    Creates and adds a virtual authenticator.
    """

    options: VirtualAuthenticatorOptions = field(metadata={"cdp_name": "options"})


@dataclass(kw_only=True, slots=True)
class AddVirtualAuthenticatorResult:
    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})


@dataclass(kw_only=True, slots=True)
class SetResponseOverrideBitsParams:
    """
    Resets parameters isBogusSignature, isBadUV, isBadUP to false if they are not
    present.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    is_bogus_signature: bool | None = field(
        default=None, metadata={"cdp_name": "isBogusSignature"}
    )
    is_bad_uv: bool | None = field(default=None, metadata={"cdp_name": "isBadUV"})
    is_bad_up: bool | None = field(default=None, metadata={"cdp_name": "isBadUP"})


@dataclass(kw_only=True, slots=True)
class RemoveVirtualAuthenticatorParams:
    """
    Removes the given authenticator.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})


@dataclass(kw_only=True, slots=True)
class AddCredentialParams:
    """
    Adds the credential to the specified authenticator.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    credential: Credential = field(metadata={"cdp_name": "credential"})


@dataclass(kw_only=True, slots=True)
class GetCredentialParams:
    """
    Returns a single credential stored in the given virtual authenticator that matches
    the credential ID.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    credential_id: str = field(metadata={"cdp_name": "credentialId"})


@dataclass(kw_only=True, slots=True)
class GetCredentialResult:
    credential: Credential = field(metadata={"cdp_name": "credential"})


@dataclass(kw_only=True, slots=True)
class GetCredentialsParams:
    """
    Returns all the credentials stored in the given virtual authenticator.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})


@dataclass(kw_only=True, slots=True)
class GetCredentialsResult:
    credentials: list[Credential] = field(metadata={"cdp_name": "credentials"})


@dataclass(kw_only=True, slots=True)
class RemoveCredentialParams:
    """
    Removes a credential from the authenticator.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    credential_id: str = field(metadata={"cdp_name": "credentialId"})


@dataclass(kw_only=True, slots=True)
class ClearCredentialsParams:
    """
    Clears all the credentials from the specified device.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})


@dataclass(kw_only=True, slots=True)
class SetUserVerifiedParams:
    """
    Sets whether User Verification succeeds or fails for an authenticator. The default
    is true.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    is_user_verified: bool = field(metadata={"cdp_name": "isUserVerified"})


@dataclass(kw_only=True, slots=True)
class SetAutomaticPresenceSimulationParams:
    """
    Sets whether tests of user presence will succeed immediately (if true) or fail to
    resolve (if false) for an authenticator. The default is true.
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    enabled: bool = field(metadata={"cdp_name": "enabled"})


@dataclass(kw_only=True, slots=True)
class SetCredentialPropertiesParams:
    """
    Allows setting credential properties.
    https://w3c.github.io/webauthn/#sctn-automation-set-credential-properties
    """

    authenticator_id: AuthenticatorId = field(metadata={"cdp_name": "authenticatorId"})
    credential_id: str = field(metadata={"cdp_name": "credentialId"})
    backup_eligibility: bool | None = field(
        default=None, metadata={"cdp_name": "backupEligibility"}
    )
    backup_state: bool | None = field(
        default=None, metadata={"cdp_name": "backupState"}
    )
    active_cmtg_key_index: int | None = field(
        default=None, metadata={"cdp_name": "activeCmtgKeyIndex"}
    )
    generate_cmtg_key_on_next_operation: bool | None = field(
        default=None, metadata={"cdp_name": "generateCmtgKeyOnNextOperation"}
    )
    sign_count: float | None = field(default=None, metadata={"cdp_name": "signCount"})
