# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from cdpify.client import CDPClient

from .commands import (
    DOMStorageCommand,
    ClearParams,
    GetDOMStorageItemsParams,
    GetDOMStorageItemsResult,
    RemoveDOMStorageItemParams,
    SetDOMStorageItemParams,
)

from .types import (
    StorageId,
)


class DOMStorageClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def clear(
        self,
        *,
        storage_id: StorageId,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ClearParams(storage_id=storage_id)

        result = await self._client.send_raw(
            method=DOMStorageCommand.CLEAR,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=DOMStorageCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def enable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=DOMStorageCommand.ENABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def get_d_o_m_storage_items(
        self,
        *,
        storage_id: StorageId,
        session_id: str | None = None,
    ) -> GetDOMStorageItemsResult:
        params = GetDOMStorageItemsParams(storage_id=storage_id)

        result = await self._client.send_raw(
            method=DOMStorageCommand.GET_D_O_M_STORAGE_ITEMS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetDOMStorageItemsResult.from_cdp(result)

    async def remove_d_o_m_storage_item(
        self,
        *,
        storage_id: StorageId,
        key: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = RemoveDOMStorageItemParams(storage_id=storage_id, key=key)

        result = await self._client.send_raw(
            method=DOMStorageCommand.REMOVE_D_O_M_STORAGE_ITEM,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_d_o_m_storage_item(
        self,
        *,
        storage_id: StorageId,
        key: str,
        value: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDOMStorageItemParams(storage_id=storage_id, key=key, value=value)

        result = await self._client.send_raw(
            method=DOMStorageCommand.SET_D_O_M_STORAGE_ITEM,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
