# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from .types import (
    Item,
    StorageId,
)


class DOMStorageCommand(StrEnum):
    CLEAR = "DOMStorage.clear"
    DISABLE = "DOMStorage.disable"
    ENABLE = "DOMStorage.enable"
    GET_DOM_STORAGE_ITEMS = "DOMStorage.getDOMStorageItems"
    REMOVE_DOM_STORAGE_ITEM = "DOMStorage.removeDOMStorageItem"
    SET_DOM_STORAGE_ITEM = "DOMStorage.setDOMStorageItem"


@dataclass(kw_only=True, slots=True)
class ClearParams:
    storage_id: StorageId = field(metadata={"cdp_name": "storageId"})


@dataclass(kw_only=True, slots=True)
class GetDOMStorageItemsParams:
    storage_id: StorageId = field(metadata={"cdp_name": "storageId"})


@dataclass(kw_only=True, slots=True)
class GetDOMStorageItemsResult:
    entries: list[Item] = field(metadata={"cdp_name": "entries"})


@dataclass(kw_only=True, slots=True)
class RemoveDOMStorageItemParams:
    storage_id: StorageId = field(metadata={"cdp_name": "storageId"})
    key: str = field(metadata={"cdp_name": "key"})


@dataclass(kw_only=True, slots=True)
class SetDOMStorageItemParams:
    storage_id: StorageId = field(metadata={"cdp_name": "storageId"})
    key: str = field(metadata={"cdp_name": "key"})
    value: str = field(metadata={"cdp_name": "value"})
