# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DigitalCredentials Domain."""

from .client import DigitalCredentialsClient
from .commands import DigitalCredentialsCommand, SetVirtualWalletBehaviorParams
from .types import VirtualWalletAction

__all__ = [
    "DigitalCredentialsClient",
    "DigitalCredentialsCommand",
    "SetVirtualWalletBehaviorParams",
    "VirtualWalletAction",
]
