# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from cdpify.domains import network, runtime
from cdpify.shared.models import CDPModel


@dataclass(kw_only=True, slots=True)
class LogEntry(CDPModel):
    """
    Log entry.
    """

    source: Literal[
        "xml",
        "javascript",
        "network",
        "storage",
        "appcache",
        "rendering",
        "security",
        "deprecation",
        "worker",
        "violation",
        "intervention",
        "recommendation",
        "other",
    ]
    level: Literal["verbose", "info", "warning", "error"]
    text: str
    category: Literal["cors"] | None = None
    timestamp: runtime.Timestamp
    url: str | None = None
    line_number: int | None = None
    stack_trace: runtime.StackTrace | None = None
    network_request_id: network.RequestId | None = None
    worker_id: str | None = None
    args: list[runtime.RemoteObject] | None = None


@dataclass(kw_only=True, slots=True)
class ViolationSetting(CDPModel):
    """
    Violation configuration setting.
    """

    name: Literal[
        "longTask",
        "longLayout",
        "blockedEvent",
        "blockedParser",
        "discouragedAPIUse",
        "handler",
        "recurringHandler",
    ]
    threshold: float
