# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from cdpify.domains import network, runtime


@dataclass(kw_only=True, slots=True)
class LogEntry:
    """
    Log entry.
    """

    source: Literal[
        "xml",
        "javascript",
        "network",
        "storage",
        "appcache",
        "rendering",
        "security",
        "deprecation",
        "worker",
        "violation",
        "intervention",
        "recommendation",
        "other",
    ] = field(  # noqa: E501
        metadata={"cdp_name": "source"},
    )
    level: Literal["verbose", "info", "warning", "error"] = field(
        metadata={"cdp_name": "level"}
    )
    text: str = field(metadata={"cdp_name": "text"})
    category: Literal["cors"] | None = field(
        default=None, metadata={"cdp_name": "category"}
    )
    timestamp: runtime.Timestamp = field(metadata={"cdp_name": "timestamp"})
    url: str | None = field(default=None, metadata={"cdp_name": "url"})
    line_number: int | None = field(default=None, metadata={"cdp_name": "lineNumber"})
    stack_trace: runtime.StackTrace | None = field(
        default=None, metadata={"cdp_name": "stackTrace"}
    )
    network_request_id: network.RequestId | None = field(
        default=None, metadata={"cdp_name": "networkRequestId"}
    )
    worker_id: str | None = field(default=None, metadata={"cdp_name": "workerId"})
    args: list[runtime.RemoteObject] | None = field(
        default=None, metadata={"cdp_name": "args"}
    )


@dataclass(kw_only=True, slots=True)
class ViolationSetting:
    """
    Violation configuration setting.
    """

    name: Literal[
        "longTask",
        "longLayout",
        "blockedEvent",
        "blockedParser",
        "discouragedAPIUse",
        "handler",
        "recurringHandler",
    ] = field(  # noqa: E501
        metadata={"cdp_name": "name"},
    )
    threshold: float = field(metadata={"cdp_name": "threshold"})
