# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.transport import Transport

from .commands import (
    AddInspectedHeapObjectParams,
    GetHeapObjectIdParams,
    GetHeapObjectIdResult,
    GetObjectByHeapObjectIdParams,
    GetObjectByHeapObjectIdResult,
    GetSamplingProfileResult,
    HeapProfilerCommand,
    StartSamplingParams,
    StartTrackingHeapObjectsParams,
    StopSamplingResult,
    StopTrackingHeapObjectsParams,
    TakeHeapSnapshotParams,
)
from .types import (
    HeapSnapshotObjectId,
)

if TYPE_CHECKING:
    from cdpify.domains import runtime


class HeapProfiler:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def add_inspected_heap_object(
        self,
        *,
        heap_object_id: HeapSnapshotObjectId,
        session_id: str | None = None,
    ) -> None:
        """
        Enables console to refer to the node with given id via $x (see Command Line API
        for more details $x functions).
        """
        params = AddInspectedHeapObjectParams(heap_object_id=heap_object_id)

        await self._transport.execute(
            method=HeapProfilerCommand.ADD_INSPECTED_HEAP_OBJECT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def collect_garbage(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._transport.execute(
            method=HeapProfilerCommand.COLLECT_GARBAGE,
            params=None,
            session_id=session_id,
        )

    async def disable(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._transport.execute(
            method=HeapProfilerCommand.DISABLE,
            params=None,
            session_id=session_id,
        )

    async def enable(
        self,
        session_id: str | None = None,
    ) -> None:
        await self._transport.execute(
            method=HeapProfilerCommand.ENABLE,
            params=None,
            session_id=session_id,
        )

    async def get_heap_object_id(
        self,
        *,
        object_id: runtime.RemoteObjectId,
        session_id: str | None = None,
    ) -> GetHeapObjectIdResult:
        params = GetHeapObjectIdParams(object_id=object_id)

        result = await self._transport.execute(
            method=HeapProfilerCommand.GET_HEAP_OBJECT_ID,
            params=encode_cdp(params),
            session_id=session_id,
        )
        return decode_cdp(GetHeapObjectIdResult, result)

    async def get_object_by_heap_object_id(
        self,
        *,
        object_id: HeapSnapshotObjectId,
        object_group: str | None = None,
        session_id: str | None = None,
    ) -> GetObjectByHeapObjectIdResult:
        params = GetObjectByHeapObjectIdParams(
            object_id=object_id, object_group=object_group
        )

        result = await self._transport.execute(
            method=HeapProfilerCommand.GET_OBJECT_BY_HEAP_OBJECT_ID,
            params=encode_cdp(params),
            session_id=session_id,
        )
        return decode_cdp(GetObjectByHeapObjectIdResult, result)

    async def get_sampling_profile(
        self,
        session_id: str | None = None,
    ) -> GetSamplingProfileResult:
        result = await self._transport.execute(
            method=HeapProfilerCommand.GET_SAMPLING_PROFILE,
            params=None,
            session_id=session_id,
        )
        return decode_cdp(GetSamplingProfileResult, result)

    async def start_sampling(
        self,
        *,
        sampling_interval: float | None = None,
        stack_depth: float | None = None,
        include_objects_collected_by_major_gc: bool | None = None,
        include_objects_collected_by_minor_gc: bool | None = None,
        session_id: str | None = None,
    ) -> None:
        params = StartSamplingParams(
            sampling_interval=sampling_interval,
            stack_depth=stack_depth,
            include_objects_collected_by_major_gc=include_objects_collected_by_major_gc,
            include_objects_collected_by_minor_gc=include_objects_collected_by_minor_gc,
        )

        await self._transport.execute(
            method=HeapProfilerCommand.START_SAMPLING,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def start_tracking_heap_objects(
        self,
        *,
        track_allocations: bool | None = None,
        session_id: str | None = None,
    ) -> None:
        params = StartTrackingHeapObjectsParams(track_allocations=track_allocations)

        await self._transport.execute(
            method=HeapProfilerCommand.START_TRACKING_HEAP_OBJECTS,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def stop_sampling(
        self,
        session_id: str | None = None,
    ) -> StopSamplingResult:
        result = await self._transport.execute(
            method=HeapProfilerCommand.STOP_SAMPLING,
            params=None,
            session_id=session_id,
        )
        return decode_cdp(StopSamplingResult, result)

    async def stop_tracking_heap_objects(
        self,
        *,
        report_progress: bool | None = None,
        treat_global_objects_as_roots: bool | None = None,
        capture_numeric_value: bool | None = None,
        expose_internals: bool | None = None,
        session_id: str | None = None,
    ) -> None:
        params = StopTrackingHeapObjectsParams(
            report_progress=report_progress,
            treat_global_objects_as_roots=treat_global_objects_as_roots,
            capture_numeric_value=capture_numeric_value,
            expose_internals=expose_internals,
        )

        await self._transport.execute(
            method=HeapProfilerCommand.STOP_TRACKING_HEAP_OBJECTS,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def take_heap_snapshot(
        self,
        *,
        report_progress: bool | None = None,
        treat_global_objects_as_roots: bool | None = None,
        capture_numeric_value: bool | None = None,
        expose_internals: bool | None = None,
        session_id: str | None = None,
    ) -> None:
        params = TakeHeapSnapshotParams(
            report_progress=report_progress,
            treat_global_objects_as_roots=treat_global_objects_as_roots,
            capture_numeric_value=capture_numeric_value,
            expose_internals=expose_internals,
        )

        await self._transport.execute(
            method=HeapProfilerCommand.TAKE_HEAP_SNAPSHOT,
            params=encode_cdp(params),
            session_id=session_id,
        )
