# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.executor import CommandExecutor

from .commands import (
    GetBestEffortCoverageResult,
    ProfilerCommand,
    SetSamplingIntervalParams,
    StartPreciseCoverageParams,
    StartPreciseCoverageResult,
    StopResult,
    TakePreciseCoverageResult,
)


class Profiler:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    async def disable(
        self,
    ) -> None:
        await self._executor.execute(
            method=ProfilerCommand.DISABLE,
            params=None,
        )

    async def enable(
        self,
    ) -> None:
        await self._executor.execute(
            method=ProfilerCommand.ENABLE,
            params=None,
        )

    async def get_best_effort_coverage(
        self,
    ) -> GetBestEffortCoverageResult:
        """
        Collect coverage data for the current isolate. The coverage data may be
        incomplete due to garbage collection.
        """
        result = await self._executor.execute(
            method=ProfilerCommand.GET_BEST_EFFORT_COVERAGE,
            params=None,
        )
        return decode_cdp(GetBestEffortCoverageResult, result)

    async def set_sampling_interval(
        self,
        *,
        interval: int,
    ) -> None:
        """
        Changes CPU profiler sampling interval. Must be called before CPU profiles
        recording started.
        """
        params = SetSamplingIntervalParams(interval=interval)

        await self._executor.execute(
            method=ProfilerCommand.SET_SAMPLING_INTERVAL,
            params=encode_cdp(params),
        )

    async def start(
        self,
    ) -> None:
        await self._executor.execute(
            method=ProfilerCommand.START,
            params=None,
        )

    async def start_precise_coverage(
        self,
        *,
        call_count: bool | None = None,
        detailed: bool | None = None,
        allow_triggered_updates: bool | None = None,
    ) -> StartPreciseCoverageResult:
        """
        Enable precise code coverage. Coverage data for JavaScript executed before
        enabling precise code coverage may be incomplete. Enabling prevents running
        optimized code and resets execution counters.
        """
        params = StartPreciseCoverageParams(
            call_count=call_count,
            detailed=detailed,
            allow_triggered_updates=allow_triggered_updates,
        )

        result = await self._executor.execute(
            method=ProfilerCommand.START_PRECISE_COVERAGE,
            params=encode_cdp(params),
        )
        return decode_cdp(StartPreciseCoverageResult, result)

    async def stop(
        self,
    ) -> StopResult:
        result = await self._executor.execute(
            method=ProfilerCommand.STOP,
            params=None,
        )
        return decode_cdp(StopResult, result)

    async def stop_precise_coverage(
        self,
    ) -> None:
        """
        Disable precise code coverage. Disabling releases unnecessary execution count
        records and allows executing optimized code.
        """
        await self._executor.execute(
            method=ProfilerCommand.STOP_PRECISE_COVERAGE,
            params=None,
        )

    async def take_precise_coverage(
        self,
    ) -> TakePreciseCoverageResult:
        """
        Collect coverage data for the current isolate, and resets execution counters.
        Precise code coverage needs to have started.
        """
        result = await self._executor.execute(
            method=ProfilerCommand.TAKE_PRECISE_COVERAGE,
            params=None,
        )
        return decode_cdp(TakePreciseCoverageResult, result)
