# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.domains import debugger
from cdpify.shared.models import CDPEvent

from .types import (
    Profile,
    ScriptCoverage,
)


class ProfilerEvent(StrEnum):
    CONSOLE_PROFILE_FINISHED = "Profiler.consoleProfileFinished"
    CONSOLE_PROFILE_STARTED = "Profiler.consoleProfileStarted"
    PRECISE_COVERAGE_DELTA_UPDATE = "Profiler.preciseCoverageDeltaUpdate"


@dataclass(kw_only=True, slots=True)
class ConsoleProfileFinishedEvent(CDPEvent):
    id: str
    location: debugger.Location
    profile: Profile
    title: str | None = None


@dataclass(kw_only=True, slots=True)
class ConsoleProfileStartedEvent(CDPEvent):
    """
    Sent when new profile recording is started using console.profile() call.
    """

    id: str
    location: debugger.Location
    title: str | None = None


@dataclass(kw_only=True, slots=True)
class PreciseCoverageDeltaUpdateEvent(CDPEvent):
    """
    Reports coverage delta since the last poll (either from an event like this, or from
    `takePreciseCoverage` for the current isolate. May only be sent if precise code
    coverage has been started. This event can be trigged by the embedder to, for
    example, trigger collection of coverage data immediately at a certain point in time.
    """

    timestamp: float
    occasion: str
    result: list[ScriptCoverage]
