# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import TYPE_CHECKING

from pydantic_cpd.cdp.base import CDPModel

if TYPE_CHECKING:
    from pydantic_cpd.cdp import runtime


class ProfileNode(CDPModel):
    """
    Profile node. Holds callsite information, execution statistics and child nodes.
    """

    id: int
    call_frame: runtime.CallFrame
    hit_count: int | None = None
    children: list[int] | None = None
    deopt_reason: str | None = None
    position_ticks: list[PositionTickInfo] | None = None


class Profile(CDPModel):
    """
    Profile.
    """

    nodes: list[ProfileNode]
    start_time: float
    end_time: float
    samples: list[int] | None = None
    time_deltas: list[int] | None = None


class PositionTickInfo(CDPModel):
    """
    Specifies a number of samples attributed to a certain source position.
    """

    line: int
    ticks: int


class CoverageRange(CDPModel):
    """
    Coverage data for a source range.
    """

    start_offset: int
    end_offset: int
    count: int


class FunctionCoverage(CDPModel):
    """
    Coverage data for a JavaScript function.
    """

    function_name: str
    ranges: list[CoverageRange]
    is_block_coverage: bool


class ScriptCoverage(CDPModel):
    """
    Coverage data for a JavaScript script.
    """

    script_id: runtime.ScriptId
    url: str
    functions: list[FunctionCoverage]
