# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import Any

from cdpify.shared.command_sender import CDPCommandSender
from cdpify.shared.decorators import deprecated

from .commands import (
    BeginFrameParams,
    BeginFrameResult,
    HeadlessExperimentalCommand,
)
from .types import (
    ScreenshotParams,
)


class HeadlessExperimental:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def begin_frame(
        self,
        *,
        frame_time_ticks: float | None = None,
        interval: float | None = None,
        no_display_updates: bool | None = None,
        screenshot: ScreenshotParams | None = None,
        session_id: str | None = None,
    ) -> BeginFrameResult:
        """
        Sends a BeginFrame to the target and returns when the frame was completed.
        Optionally captures a screenshot from the resulting frame. Requires that the
        target was created with enabled BeginFrameControl. Designed for use with
        --run-all-compositor-stages-before-draw, see also
        https://goo.gle/chrome-headless-rendering for more background.
        """
        params = BeginFrameParams(
            frame_time_ticks=frame_time_ticks,
            interval=interval,
            no_display_updates=no_display_updates,
            screenshot=screenshot,
        )

        result = await self._command_sender.send_raw(
            method=HeadlessExperimentalCommand.BEGIN_FRAME,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return BeginFrameResult.from_cdp(result)

    @deprecated()
    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Disables headless events for the target.
        """
        result = await self._command_sender.send_raw(
            method=HeadlessExperimentalCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    @deprecated()
    async def enable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Enables headless events for the target.
        """
        result = await self._command_sender.send_raw(
            method=HeadlessExperimentalCommand.ENABLE,
            params=None,
            session_id=session_id,
        )
        return result
