# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass(kw_only=True, slots=True)
class ScreenshotParams:
    """
    Encoding options for a screenshot.
    """

    format: Literal["jpeg", "png", "webp"] | None = field(
        default=None, metadata={"cdp_name": "format"}
    )
    quality: int | None = field(default=None, metadata={"cdp_name": "quality"})
    optimize_for_speed: bool | None = field(
        default=None, metadata={"cdp_name": "optimizeForSpeed"}
    )
