# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from cdpify.shared.models import CDPModel


@dataclass(kw_only=True, slots=True)
class ScreenshotParams(CDPModel):
    """
    Encoding options for a screenshot.
    """

    format: Literal["jpeg", "png", "webp"] | None = None
    quality: int | None = None
    optimize_for_speed: bool | None = None
