# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum

from pydantic_cpd.domains.base import CDPModel

from .types import *


class PerformanceEvent(StrEnum):
    METRICS = "Performance.metrics"


class MetricsEvent(CDPModel):
    """
    Current values of the metrics.
    """

    metrics: list[Metric]
    title: str
