# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class SetDeviceOrientationOverrideParams(CDPModel):
    """
    Overrides the Device Orientation.
    """

    alpha: float
    beta: float
    gamma: float
