# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from typing import TYPE_CHECKING

from pydantic_cpd.domains.base import CDPModel

from .types import *

if TYPE_CHECKING:
    from pydantic_cpd.cdp import dom, page


class OverlayEvent(StrEnum):
    INSPECT_NODE_REQUESTED = "Overlay.inspectNodeRequested"
    NODE_HIGHLIGHT_REQUESTED = "Overlay.nodeHighlightRequested"
    SCREENSHOT_REQUESTED = "Overlay.screenshotRequested"
    INSPECT_MODE_CANCELED = "Overlay.inspectModeCanceled"


class InspectNodeRequestedEvent(CDPModel):
    """
    Fired when the node should be inspected. This happens after call to
    `setInspectMode` or when user manually inspects an element.
    """

    backend_node_id: dom.BackendNodeId


class NodeHighlightRequestedEvent(CDPModel):
    """
    Fired when the node should be highlighted. This happens after call to
    `setInspectMode`.
    """

    node_id: dom.NodeId


class ScreenshotRequestedEvent(CDPModel):
    """
    Fired when user asks to capture screenshot of some area on the page.
    """

    viewport: page.Viewport


class InspectModeCanceledEvent(CDPModel):
    """
    Fired when user cancels the inspect mode.
    """

    pass
