# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pydantic_cpd.client import CDPClient

from pydantic_cpd.cdp import dom

from .commands import (
    GetGridHighlightObjectsForTestParams,
    GetGridHighlightObjectsForTestResult,
    GetHighlightObjectForTestParams,
    GetHighlightObjectForTestResult,
    GetSourceOrderHighlightObjectForTestParams,
    GetSourceOrderHighlightObjectForTestResult,
    HighlightFrameParams,
    HighlightNodeParams,
    HighlightQuadParams,
    HighlightRectParams,
    HighlightSourceOrderParams,
    SetInspectModeParams,
    SetPausedInDebuggerMessageParams,
    SetShowAdHighlightsParams,
    SetShowContainerQueryOverlaysParams,
    SetShowDebugBordersParams,
    SetShowFlexOverlaysParams,
    SetShowFPSCounterParams,
    SetShowGridOverlaysParams,
    SetShowHingeParams,
    SetShowHitTestBordersParams,
    SetShowIsolatedElementsParams,
    SetShowLayoutShiftRegionsParams,
    SetShowPaintRectsParams,
    SetShowScrollBottleneckRectsParams,
    SetShowScrollSnapOverlaysParams,
    SetShowViewportSizeOnResizeParams,
    SetShowWebVitalsParams,
    SetShowWindowControlsOverlayParams,
)
from .types import (
    ColorFormat,
    ContainerQueryHighlightConfig,
    FlexNodeHighlightConfig,
    GridNodeHighlightConfig,
    HighlightConfig,
    HingeConfig,
    InspectMode,
    IsolatedElementHighlightConfig,
    ScrollSnapHighlightConfig,
    SourceOrderConfig,
    WindowControlsOverlayConfig,
)


class OverlayClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Overlay.disable",
            params=None,
            session_id=session_id,
        )
        return result

    async def enable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Overlay.enable",
            params=None,
            session_id=session_id,
        )
        return result

    async def get_highlight_object_for_test(
        self,
        *,
        node_id: DOM.NodeId,
        include_distance: bool | None = None,
        include_style: bool | None = None,
        color_format: ColorFormat | None = None,
        show_accessibility_info: bool | None = None,
        session_id: str | None = None,
    ) -> GetHighlightObjectForTestResult:
        params = GetHighlightObjectForTestParams(
            nodeId=node_id,
            includeDistance=include_distance,
            includeStyle=include_style,
            colorFormat=color_format,
            showAccessibilityInfo=show_accessibility_info,
        )

        result = await self._client.send_raw(
            method="Overlay.getHighlightObjectForTest",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetHighlightObjectForTestResult.model_validate(result)

    async def get_grid_highlight_objects_for_test(
        self,
        *,
        node_ids: list[dom.NodeId],
        session_id: str | None = None,
    ) -> GetGridHighlightObjectsForTestResult:
        params = GetGridHighlightObjectsForTestParams(nodeIds=node_ids)

        result = await self._client.send_raw(
            method="Overlay.getGridHighlightObjectsForTest",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetGridHighlightObjectsForTestResult.model_validate(result)

    async def get_source_order_highlight_object_for_test(
        self,
        *,
        node_id: DOM.NodeId,
        session_id: str | None = None,
    ) -> GetSourceOrderHighlightObjectForTestResult:
        params = GetSourceOrderHighlightObjectForTestParams(nodeId=node_id)

        result = await self._client.send_raw(
            method="Overlay.getSourceOrderHighlightObjectForTest",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetSourceOrderHighlightObjectForTestResult.model_validate(result)

    async def hide_highlight(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Overlay.hideHighlight",
            params=None,
            session_id=session_id,
        )
        return result

    async def highlight_frame(
        self,
        *,
        frame_id: Page.FrameId,
        content_color: DOM.RGBA | None = None,
        content_outline_color: DOM.RGBA | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = HighlightFrameParams(
            frameId=frame_id,
            contentColor=content_color,
            contentOutlineColor=content_outline_color,
        )

        result = await self._client.send_raw(
            method="Overlay.highlightFrame",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def highlight_node(
        self,
        *,
        highlight_config: HighlightConfig,
        node_id: DOM.NodeId | None = None,
        backend_node_id: DOM.BackendNodeId | None = None,
        object_id: Runtime.RemoteObjectId | None = None,
        selector: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = HighlightNodeParams(
            highlightConfig=highlight_config,
            nodeId=node_id,
            backendNodeId=backend_node_id,
            objectId=object_id,
            selector=selector,
        )

        result = await self._client.send_raw(
            method="Overlay.highlightNode",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def highlight_quad(
        self,
        *,
        quad: DOM.Quad,
        color: DOM.RGBA | None = None,
        outline_color: DOM.RGBA | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = HighlightQuadParams(quad=quad, color=color, outlineColor=outline_color)

        result = await self._client.send_raw(
            method="Overlay.highlightQuad",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def highlight_rect(
        self,
        *,
        x: int,
        y: int,
        width: int,
        height: int,
        color: DOM.RGBA | None = None,
        outline_color: DOM.RGBA | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = HighlightRectParams(
            x=x,
            y=y,
            width=width,
            height=height,
            color=color,
            outlineColor=outline_color,
        )

        result = await self._client.send_raw(
            method="Overlay.highlightRect",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def highlight_source_order(
        self,
        *,
        source_order_config: SourceOrderConfig,
        node_id: DOM.NodeId | None = None,
        backend_node_id: DOM.BackendNodeId | None = None,
        object_id: Runtime.RemoteObjectId | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = HighlightSourceOrderParams(
            sourceOrderConfig=source_order_config,
            nodeId=node_id,
            backendNodeId=backend_node_id,
            objectId=object_id,
        )

        result = await self._client.send_raw(
            method="Overlay.highlightSourceOrder",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_inspect_mode(
        self,
        *,
        mode: InspectMode,
        highlight_config: HighlightConfig | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetInspectModeParams(mode=mode, highlightConfig=highlight_config)

        result = await self._client.send_raw(
            method="Overlay.setInspectMode",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_ad_highlights(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowAdHighlightsParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowAdHighlights",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_paused_in_debugger_message(
        self,
        *,
        message: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetPausedInDebuggerMessageParams(message=message)

        result = await self._client.send_raw(
            method="Overlay.setPausedInDebuggerMessage",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_debug_borders(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowDebugBordersParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowDebugBorders",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_f_p_s_counter(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowFPSCounterParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowFPSCounter",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_grid_overlays(
        self,
        *,
        grid_node_highlight_configs: list[GridNodeHighlightConfig],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowGridOverlaysParams(
            gridNodeHighlightConfigs=grid_node_highlight_configs
        )

        result = await self._client.send_raw(
            method="Overlay.setShowGridOverlays",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_flex_overlays(
        self,
        *,
        flex_node_highlight_configs: list[FlexNodeHighlightConfig],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowFlexOverlaysParams(
            flexNodeHighlightConfigs=flex_node_highlight_configs
        )

        result = await self._client.send_raw(
            method="Overlay.setShowFlexOverlays",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_scroll_snap_overlays(
        self,
        *,
        scroll_snap_highlight_configs: list[ScrollSnapHighlightConfig],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowScrollSnapOverlaysParams(
            scrollSnapHighlightConfigs=scroll_snap_highlight_configs
        )

        result = await self._client.send_raw(
            method="Overlay.setShowScrollSnapOverlays",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_container_query_overlays(
        self,
        *,
        container_query_highlight_configs: list[ContainerQueryHighlightConfig],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowContainerQueryOverlaysParams(
            containerQueryHighlightConfigs=container_query_highlight_configs
        )

        result = await self._client.send_raw(
            method="Overlay.setShowContainerQueryOverlays",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_paint_rects(
        self,
        *,
        result: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowPaintRectsParams(result=result)

        result = await self._client.send_raw(
            method="Overlay.setShowPaintRects",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_layout_shift_regions(
        self,
        *,
        result: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowLayoutShiftRegionsParams(result=result)

        result = await self._client.send_raw(
            method="Overlay.setShowLayoutShiftRegions",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_scroll_bottleneck_rects(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowScrollBottleneckRectsParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowScrollBottleneckRects",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_hit_test_borders(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowHitTestBordersParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowHitTestBorders",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_web_vitals(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowWebVitalsParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowWebVitals",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_viewport_size_on_resize(
        self,
        *,
        show: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowViewportSizeOnResizeParams(show=show)

        result = await self._client.send_raw(
            method="Overlay.setShowViewportSizeOnResize",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_hinge(
        self,
        *,
        hinge_config: HingeConfig | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowHingeParams(hingeConfig=hinge_config)

        result = await self._client.send_raw(
            method="Overlay.setShowHinge",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_isolated_elements(
        self,
        *,
        isolated_element_highlight_configs: list[IsolatedElementHighlightConfig],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowIsolatedElementsParams(
            isolatedElementHighlightConfigs=isolated_element_highlight_configs
        )

        result = await self._client.send_raw(
            method="Overlay.setShowIsolatedElements",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_show_window_controls_overlay(
        self,
        *,
        window_controls_overlay_config: WindowControlsOverlayConfig | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetShowWindowControlsOverlayParams(
            windowControlsOverlayConfig=window_controls_overlay_config
        )

        result = await self._client.send_raw(
            method="Overlay.setShowWindowControlsOverlay",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
