# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Schema Domain."""

from .commands import GetDomainsResult, SchemaCommand
from .domain import Schema
from .types import Domain

__all__ = [
    "Domain",
    "GetDomainsResult",
    "Schema",
    "SchemaCommand",
]
