# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(kw_only=True, slots=True)
class Domain:
    """
    Description of the protocol domain.
    """

    name: str = field(metadata={"cdp_name": "name"})
    version: str = field(metadata={"cdp_name": "version"})
