# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from cdpify.domains import network

"""
Unique request identifier. Note that this does not identify individual HTTP requests
that are part of a network request.
"""
RequestId = str

"""
Stages of the request to handle. Request will intercept before the request is sent.
Response will intercept after the response is received (but before response body is
received).
"""
type RequestStage = Literal["Request", "Response"]


@dataclass(kw_only=True, slots=True)
class RequestPattern:
    url_pattern: str | None = field(default=None, metadata={"cdp_name": "urlPattern"})
    resource_type: network.ResourceType | None = field(
        default=None, metadata={"cdp_name": "resourceType"}
    )
    request_stage: RequestStage | None = field(
        default=None, metadata={"cdp_name": "requestStage"}
    )


@dataclass(kw_only=True, slots=True)
class HeaderEntry:
    """
    Response HTTP header entry
    """

    name: str = field(metadata={"cdp_name": "name"})
    value: str = field(metadata={"cdp_name": "value"})


@dataclass(kw_only=True, slots=True)
class AuthChallenge:
    """
    Authorization challenge for HTTP status code 401 or 407.
    """

    source: Literal["Server", "Proxy"] | None = field(
        default=None, metadata={"cdp_name": "source"}
    )
    origin: str = field(metadata={"cdp_name": "origin"})
    scheme: str = field(metadata={"cdp_name": "scheme"})
    realm: str = field(metadata={"cdp_name": "realm"})


@dataclass(kw_only=True, slots=True)
class AuthChallengeResponse:
    """
    Response to an AuthChallenge.
    """

    response: Literal["Default", "CancelAuth", "ProvideCredentials"] = field(
        metadata={"cdp_name": "response"}
    )
    username: str | None = field(default=None, metadata={"cdp_name": "username"})
    password: str | None = field(default=None, metadata={"cdp_name": "password"})
