# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    AdsCommand,
    GetAdMetricsResult,
    GetAdScriptsResult,
)


class Ads:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def get_ad_metrics(
        self,
        session_id: str | None = None,
    ) -> GetAdMetricsResult:
        """
        Retrieves ad metrics for the current page.
        """
        result = await self._command_sender.send_raw(
            method=AdsCommand.GET_AD_METRICS,
            params=None,
            session_id=session_id,
        )
        return GetAdMetricsResult.from_cdp(result)

    async def get_ad_scripts(
        self,
        session_id: str | None = None,
    ) -> GetAdScriptsResult:
        """
        Retrieves ad scripts for the current page. To minimize payload size, this only
        returns the newly tracked ad scripts since the last call to getAdScripts (i.e.,
        the delta).
        """
        result = await self._command_sender.send_raw(
            method=AdsCommand.GET_AD_SCRIPTS,
            params=None,
            session_id=session_id,
        )
        return GetAdScriptsResult.from_cdp(result)
