# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import Any

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    InspectorCommand,
)


class Inspector:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Disables inspector domain notifications.
        """
        result = await self._command_sender.send_raw(
            method=InspectorCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def enable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Enables inspector domain notifications.
        """
        result = await self._command_sender.send_raw(
            method=InspectorCommand.ENABLE,
            params=None,
            session_id=session_id,
        )
        return result
