# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.executor import CommandExecutor

from .commands import (
    InspectorCommand,
)


class Inspector:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    async def disable(
        self,
    ) -> None:
        """
        Disables inspector domain notifications.
        """
        await self._executor.execute(
            method=InspectorCommand.DISABLE,
            params=None,
        )

    async def enable(
        self,
    ) -> None:
        """
        Enables inspector domain notifications.
        """
        await self._executor.execute(
            method=InspectorCommand.ENABLE,
            params=None,
        )
