# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.shared.models import CDPEvent


class InspectorEvent(StrEnum):
    DETACHED = "Inspector.detached"
    TARGET_CRASHED = "Inspector.targetCrashed"
    TARGET_RELOADED_AFTER_CRASH = "Inspector.targetReloadedAfterCrash"
    WORKER_SCRIPT_LOADED = "Inspector.workerScriptLoaded"


@dataclass(kw_only=True, slots=True)
class DetachedEvent(CDPEvent):
    """
    Fired when remote debugging connection is about to be terminated. Contains detach
    reason.
    """

    reason: str


@dataclass(kw_only=True, slots=True)
class TargetCrashedEvent(CDPEvent):
    """
    Fired when debugging target has crashed
    """

    pass


@dataclass(kw_only=True, slots=True)
class TargetReloadedAfterCrashEvent(CDPEvent):
    """
    Fired when debugging target has reloaded after crash
    """

    pass


@dataclass(kw_only=True, slots=True)
class WorkerScriptLoadedEvent(CDPEvent):
    """
    Fired on worker targets when main worker script and any imported scripts have been
    evaluated.
    """

    pass
