# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Cast Domain."""

from .client import CastClient
from .commands import (
    CastCommand,
    EnableParams,
    SetSinkToUseParams,
    StartDesktopMirroringParams,
    StartTabMirroringParams,
    StopCastingParams,
)
from .events import CastEvent, IssueUpdatedEvent, SinksUpdatedEvent
from .types import Sink

__all__ = [
    "CastClient",
    "CastCommand",
    "CastEvent",
    "EnableParams",
    "IssueUpdatedEvent",
    "SetSinkToUseParams",
    "Sink",
    "SinksUpdatedEvent",
    "StartDesktopMirroringParams",
    "StartTabMirroringParams",
    "StopCastingParams",
]
