# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass

from cdpify.domains import page
from cdpify.shared.models import CDPModel


@dataclass(kw_only=True, slots=True)
class CrashReportContextEntry(CDPModel):
    """
    Key-value pair in CrashReportContext.
    """

    key: str
    value: str
    frame_id: page.FrameId
