# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    FileSystemCommand,
    GetDirectoryParams,
    GetDirectoryResult,
)
from .types import (
    BucketFileSystemLocator,
)


class FileSystemClient:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def get_directory(
        self,
        *,
        bucket_file_system_locator: BucketFileSystemLocator,
        session_id: str | None = None,
    ) -> GetDirectoryResult:
        params = GetDirectoryParams(
            bucket_file_system_locator=bucket_file_system_locator
        )

        result = await self._command_sender.send_raw(
            method=FileSystemCommand.GET_DIRECTORY,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetDirectoryResult.from_cdp(result)
