# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.executor import CommandExecutor

from .commands import (
    FileSystemCommand,
    GetDirectoryParams,
    GetDirectoryResult,
)
from .types import (
    BucketFileSystemLocator,
)


class FileSystem:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    async def get_directory(
        self,
        *,
        bucket_file_system_locator: BucketFileSystemLocator,
    ) -> GetDirectoryResult:
        params = GetDirectoryParams(
            bucket_file_system_locator=bucket_file_system_locator
        )

        result = await self._executor.execute(
            method=FileSystemCommand.GET_DIRECTORY,
            params=encode_cdp(params),
        )
        return decode_cdp(GetDirectoryResult, result)
