# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DeviceAccess Domain."""

from .client import DeviceAccess
from .commands import CancelPromptParams, DeviceAccessCommand, SelectPromptParams
from .events import DeviceAccessEvent, DeviceRequestPromptedEvent
from .types import DeviceId, PromptDevice, RequestId

__all__ = [
    "CancelPromptParams",
    "DeviceAccess",
    "DeviceAccessCommand",
    "DeviceAccessEvent",
    "DeviceId",
    "DeviceRequestPromptedEvent",
    "PromptDevice",
    "RequestId",
    "SelectPromptParams",
]
