# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from .types import (
    DeviceId,
    RequestId,
)


class DeviceAccessCommand(StrEnum):
    ENABLE = "DeviceAccess.enable"
    DISABLE = "DeviceAccess.disable"
    SELECT_PROMPT = "DeviceAccess.selectPrompt"
    CANCEL_PROMPT = "DeviceAccess.cancelPrompt"


@dataclass(kw_only=True, slots=True)
class SelectPromptParams:
    """
    Select a device in response to a DeviceAccess.deviceRequestPrompted event.
    """

    id: RequestId = field(metadata={"cdp_name": "id"})
    device_id: DeviceId = field(metadata={"cdp_name": "deviceId"})


@dataclass(kw_only=True, slots=True)
class CancelPromptParams:
    """
    Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.
    """

    id: RequestId = field(metadata={"cdp_name": "id"})
