# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.shared.models import CDPModel

from .types import (
    DeviceId,
    RequestId,
)


class DeviceAccessCommand(StrEnum):
    ENABLE = "DeviceAccess.enable"
    DISABLE = "DeviceAccess.disable"
    SELECT_PROMPT = "DeviceAccess.selectPrompt"
    CANCEL_PROMPT = "DeviceAccess.cancelPrompt"


@dataclass(kw_only=True, slots=True)
class SelectPromptParams(CDPModel):
    """
    Select a device in response to a DeviceAccess.deviceRequestPrompted event.
    """

    id: RequestId
    device_id: DeviceId


@dataclass(kw_only=True, slots=True)
class CancelPromptParams(CDPModel):
    """
    Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.
    """

    id: RequestId
