# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import Any, Literal, TYPE_CHECKING
from dataclasses import dataclass
from cdpify.shared.models import CDPModel

if TYPE_CHECKING:
    from cdpify.domains import dom, page

"""
Stylesheet type: "injected" for stylesheets injected via extension, "user-agent" for
user-agent stylesheets, "inspector" for stylesheets created by the inspector (i.e. those
holding the "via inspector" rules), "regular" for regular stylesheets.
"""
StyleSheetOrigin = Literal["injected", "user-agent", "inspector", "regular"]


@dataclass(kw_only=True)
class PseudoElementMatches(CDPModel):
    """
    CSS rule collection for a single pseudo style.
    """

    pseudo_type: dom.PseudoType
    pseudo_identifier: str | None = None
<<<<<<< HEAD
    matches: list[Any]
=======
    matches: list[RuleMatch]
>>>>>>> dbc9f52 (Defer typing import)


@dataclass(kw_only=True)
class CSSAnimationStyle(CDPModel):
    """
    CSS style coming from animations with the name of the animation.
    """

    name: str | None = None
    style: CSSStyle


@dataclass(kw_only=True)
class InheritedStyleEntry(CDPModel):
    """
    Inherited CSS rule collection from ancestor node.
    """

    inline_style: CSSStyle | None = None
<<<<<<< HEAD
    matched_css_rules: list[Any]
=======
    matched_css_rules: list[RuleMatch]
>>>>>>> dbc9f52 (Defer typing import)


@dataclass(kw_only=True)
class InheritedAnimatedStyleEntry(CDPModel):
    """
    Inherited CSS style collection for animated styles from ancestor node.
    """

<<<<<<< HEAD
    animation_styles: list[Any] | None = None
=======
    animation_styles: list[CSSAnimationStyle] | None = None
>>>>>>> dbc9f52 (Defer typing import)
    transitions_style: CSSStyle | None = None


@dataclass(kw_only=True)
class InheritedPseudoElementMatches(CDPModel):
    """
    Inherited pseudo element matches from pseudos of an ancestor node.
    """

    pseudo_elements: list[Any]


@dataclass(kw_only=True)
class RuleMatch(CDPModel):
    """
    Match data for a CSS rule.
    """

    rule: CSSRule
    matching_selectors: list[Any]


@dataclass(kw_only=True)
class Value(CDPModel):
    """
    Data for a simple selector (these are delimited by commas in a selector list).
    """

    text: str
    range: SourceRange | None = None
    specificity: Specificity | None = None


@dataclass(kw_only=True)
class Specificity(CDPModel):
    """
    Specificity: https://drafts.csswg.org/selectors/#specificity-rules
    """

    a: int
    b: int
    c: int


@dataclass(kw_only=True)
class SelectorList(CDPModel):
    """
    Selector list data.
    """

    selectors: list[Any]
    text: str


@dataclass(kw_only=True)
class CSSStyleSheetHeader(CDPModel):
    """
    CSS stylesheet metainformation.
    """

    style_sheet_id: dom.StyleSheetId
    frame_id: page.FrameId
    source_url: str
    source_map_url: str | None = None
    origin: StyleSheetOrigin
    title: str
    owner_node: dom.BackendNodeId | None = None
    disabled: bool
    has_source_url: bool | None = None
    is_inline: bool
    is_mutable: bool
    is_constructed: bool
    start_line: float
    start_column: float
    length: float
    end_line: float
    end_column: float
    loading_failed: bool | None = None


@dataclass(kw_only=True)
class CSSRule(CDPModel):
    """
    CSS rule representation.
    """

    style_sheet_id: dom.StyleSheetId | None = None
    selector_list: SelectorList
<<<<<<< HEAD
    nesting_selectors: list[Any] | None = None
    origin: StyleSheetOrigin
    style: CSSStyle
    origin_tree_scope_node_id: dom.BackendNodeId | None = None
    media: list[Any] | None = None
    container_queries: list[Any] | None = None
    supports: list[Any] | None = None
    layers: list[Any] | None = None
    scopes: list[Any] | None = None
    rule_types: list[Any] | None = None
    starting_styles: list[Any] | None = None
    navigations: list[Any] | None = None
=======
    nesting_selectors: list[str] | None = None
    origin: StyleSheetOrigin
    style: CSSStyle
    origin_tree_scope_node_id: dom.BackendNodeId | None = None
    media: list[CSSMedia] | None = None
    container_queries: list[CSSContainerQuery] | None = None
    supports: list[CSSSupports] | None = None
    layers: list[CSSLayer] | None = None
    scopes: list[CSSScope] | None = None
    rule_types: list[CSSRuleType] | None = None
    starting_styles: list[CSSStartingStyle] | None = None
>>>>>>> dbc9f52 (Defer typing import)


"""
Enum indicating the type of a CSS rule, used to represent the order of a style rule's
ancestors. This list only contains rule types that are collected during the ancestor
rule collection.
"""
CSSRuleType = Literal[
    "MediaRule",
    "SupportsRule",
    "ContainerRule",
    "LayerRule",
    "ScopeRule",
    "StyleRule",
    "StartingStyleRule",
    "NavigationRule",
]


@dataclass(kw_only=True)
class RuleUsage(CDPModel):
    """
    CSS coverage information.
    """

    style_sheet_id: dom.StyleSheetId
    start_offset: float
    end_offset: float
    used: bool


@dataclass(kw_only=True)
class SourceRange(CDPModel):
    """
    Text range within a resource. All numbers are zero-based.
    """

    start_line: int
    start_column: int
    end_line: int
    end_column: int


@dataclass(kw_only=True)
class ShorthandEntry(CDPModel):
    name: str
    value: str
    important: bool | None = None


@dataclass(kw_only=True)
class CSSComputedStyleProperty(CDPModel):
    name: str
    value: str


@dataclass(kw_only=True)
class ComputedStyleExtraFields(CDPModel):
    is_appearance_base: bool


@dataclass(kw_only=True)
class CSSStyle(CDPModel):
    """
    CSS style representation.
    """

    style_sheet_id: dom.StyleSheetId | None = None
<<<<<<< HEAD
    css_properties: list[Any]
    shorthand_entries: list[Any]
=======
    css_properties: list[CSSProperty]
    shorthand_entries: list[ShorthandEntry]
>>>>>>> dbc9f52 (Defer typing import)
    css_text: str | None = None
    range: SourceRange | None = None


@dataclass(kw_only=True)
class CSSProperty(CDPModel):
    """
    CSS property declaration data.
    """

    name: str
    value: str
    important: bool | None = None
    implicit: bool | None = None
    text: str | None = None
    parsed_ok: bool | None = None
    disabled: bool | None = None
    range: SourceRange | None = None
<<<<<<< HEAD
    longhand_properties: list[Any] | None = None
=======
    longhand_properties: list[CSSProperty] | None = None
>>>>>>> dbc9f52 (Defer typing import)


@dataclass(kw_only=True)
class CSSMedia(CDPModel):
    """
    CSS media rule descriptor.
    """

    text: str
<<<<<<< HEAD
    source: str
    source_url: str | None = None
    range: SourceRange | None = None
    style_sheet_id: dom.StyleSheetId | None = None
    media_list: list[Any] | None = None
=======
    source: Literal["mediaRule", "importRule", "linkedSheet", "inlineSheet"]
    source_url: str | None = None
    range: SourceRange | None = None
    style_sheet_id: dom.StyleSheetId | None = None
    media_list: list[MediaQuery] | None = None
>>>>>>> dbc9f52 (Defer typing import)


@dataclass(kw_only=True)
class MediaQuery(CDPModel):
    """
    Media query descriptor.
    """

    expressions: list[Any]
    active: bool


@dataclass(kw_only=True)
class MediaQueryExpression(CDPModel):
    """
    Media query expression descriptor.
    """

    value: float
    unit: str
    feature: str
    value_range: SourceRange | None = None
    computed_length: float | None = None


@dataclass(kw_only=True)
class CSSContainerQuery(CDPModel):
    """
    CSS container query rule descriptor.
    """

    text: str
    range: SourceRange | None = None
    style_sheet_id: dom.StyleSheetId | None = None
    name: str | None = None
    physical_axes: dom.PhysicalAxes | None = None
    logical_axes: dom.LogicalAxes | None = None
    queries_scroll_state: bool | None = None
    queries_anchored: bool | None = None


@dataclass(kw_only=True)
class CSSSupports(CDPModel):
    """
    CSS Supports at-rule descriptor.
    """

    text: str
    active: bool
    range: SourceRange | None = None
<<<<<<< HEAD
    style_sheet_id: dom.StyleSheetId | None = None


@dataclass(kw_only=True)
class CSSNavigation(CDPModel):
    """
    CSS Navigation at-rule descriptor.
    """

    text: str
    active: bool | None = None
    range: SourceRange | None = None
=======
>>>>>>> dbc9f52 (Defer typing import)
    style_sheet_id: dom.StyleSheetId | None = None


@dataclass(kw_only=True)
class CSSScope(CDPModel):
    """
    CSS Scope at-rule descriptor.
    """

    text: str
    range: SourceRange | None = None
    style_sheet_id: dom.StyleSheetId | None = None


@dataclass(kw_only=True)
class CSSLayer(CDPModel):
    """
    CSS Layer at-rule descriptor.
    """

    text: str
    range: SourceRange | None = None
    style_sheet_id: dom.StyleSheetId | None = None


@dataclass(kw_only=True)
class CSSStartingStyle(CDPModel):
    """
    CSS Starting Style at-rule descriptor.
    """

    range: SourceRange | None = None
    style_sheet_id: dom.StyleSheetId | None = None


@dataclass(kw_only=True)
class CSSLayerData(CDPModel):
    """
    CSS Layer data.
    """

    name: str
<<<<<<< HEAD
    sub_layers: list[Any] | None = None
=======
    sub_layers: list[CSSLayerData] | None = None
>>>>>>> dbc9f52 (Defer typing import)
    order: float


@dataclass(kw_only=True)
class PlatformFontUsage(CDPModel):
    """
    Information about amount of glyphs that were rendered with given font.
    """

    family_name: str
    post_script_name: str
    is_custom_font: bool
    glyph_count: float


@dataclass(kw_only=True)
class FontVariationAxis(CDPModel):
    """
    Information about font variation axes for variable fonts
    """

    tag: str
    name: str
    min_value: float
    max_value: float
    default_value: float


@dataclass(kw_only=True)
class FontFace(CDPModel):
    """
    Properties of a web font:
    https://www.w3.org/TR/2008/REC-CSS2-20080411/fonts.html#font-descriptions and
    additional information such as platformFontFamily and fontVariationAxes.
    """

    font_family: str
    font_style: str
    font_variant: str
    font_weight: str
    font_stretch: str
    font_display: str
    unicode_range: str
    src: str
    platform_font_family: str
<<<<<<< HEAD
    font_variation_axes: list[Any] | None = None
=======
    font_variation_axes: list[FontVariationAxis] | None = None
>>>>>>> dbc9f52 (Defer typing import)


@dataclass(kw_only=True)
class CSSTryRule(CDPModel):
    """
    CSS try rule representation.
    """

    style_sheet_id: dom.StyleSheetId | None = None
    origin: StyleSheetOrigin
    style: CSSStyle


@dataclass(kw_only=True)
class CSSPositionTryRule(CDPModel):
    """
    CSS @position-try rule representation.
    """

    name: Value
    style_sheet_id: dom.StyleSheetId | None = None
    origin: StyleSheetOrigin
    style: CSSStyle
    active: bool


@dataclass(kw_only=True)
class CSSKeyframesRule(CDPModel):
    """
    CSS keyframes rule representation.
    """

    animation_name: Value
    keyframes: list[Any]


@dataclass(kw_only=True)
class CSSPropertyRegistration(CDPModel):
    """
    Representation of a custom property registration through CSS.registerProperty
    """

    property_name: str
    initial_value: Value | None = None
    inherits: bool
    syntax: str


@dataclass(kw_only=True)
class CSSAtRule(CDPModel):
    """
    CSS generic @rule representation.
    """

<<<<<<< HEAD
    type: str
    subsection: str | None = None
=======
    type: Literal["font-face", "font-feature-values", "font-palette-values"]
    subsection: (
        Literal[
            "swash",
            "annotation",
            "ornaments",
            "stylistic",
            "styleset",
            "character-variant",
        ]
        | None
    ) = None
>>>>>>> dbc9f52 (Defer typing import)
    name: Value | None = None
    style_sheet_id: dom.StyleSheetId | None = None
    origin: StyleSheetOrigin
    style: CSSStyle


@dataclass(kw_only=True)
class CSSPropertyRule(CDPModel):
    """
    CSS property at-rule representation.
    """

    style_sheet_id: dom.StyleSheetId | None = None
    origin: StyleSheetOrigin
    property_name: Value
    style: CSSStyle


@dataclass(kw_only=True)
class CSSFunctionParameter(CDPModel):
    """
    CSS function argument representation.
    """

    name: str
    type: str


@dataclass(kw_only=True)
class CSSFunctionConditionNode(CDPModel):
    """
    CSS function conditional block representation.
    """

    media: CSSMedia | None = None
    container_queries: CSSContainerQuery | None = None
    supports: CSSSupports | None = None
<<<<<<< HEAD
    navigation: CSSNavigation | None = None
    children: list[Any]
=======
    children: list[CSSFunctionNode]
>>>>>>> dbc9f52 (Defer typing import)
    condition_text: str


@dataclass(kw_only=True)
class CSSFunctionNode(CDPModel):
    """
    Section of the body of a CSS function rule.
    """

    condition: CSSFunctionConditionNode | None = None
    style: CSSStyle | None = None


@dataclass(kw_only=True)
class CSSFunctionRule(CDPModel):
    """
    CSS function at-rule representation.
    """

    name: Value
    style_sheet_id: dom.StyleSheetId | None = None
    origin: StyleSheetOrigin
    parameters: list[Any]
    children: list[Any]
    origin_tree_scope_node_id: dom.BackendNodeId | None = None


@dataclass(kw_only=True)
class CSSKeyframeRule(CDPModel):
    """
    CSS keyframe rule representation.
    """

    style_sheet_id: dom.StyleSheetId | None = None
    origin: StyleSheetOrigin
    key_text: Value
    style: CSSStyle


@dataclass(kw_only=True)
class StyleDeclarationEdit(CDPModel):
    """
    A descriptor of operation to mutate style declaration text.
    """

    style_sheet_id: dom.StyleSheetId
    range: SourceRange
    text: str
