# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from cdpify.domains import network, page

"""
Unique DOM node identifier.
"""
NodeId = int

"""
Unique DOM node identifier used to reference a node that may not have been pushed to
the front-end.
"""
BackendNodeId = int

"""
Unique identifier for a CSS stylesheet.
"""
StyleSheetId = str


@dataclass(kw_only=True, slots=True)
class BackendNode:
    """
    Backend node with a friendly name.
    """

    node_type: int = field(metadata={"cdp_name": "nodeType"})
    node_name: str = field(metadata={"cdp_name": "nodeName"})
    backend_node_id: BackendNodeId = field(metadata={"cdp_name": "backendNodeId"})


"""
Pseudo element type.
"""
type PseudoType = Literal[
    "first-line",
    "first-letter",
    "checkmark",
    "before",
    "after",
    "expand-icon",
    "picker-icon",
    "interest-button",
    "marker",
    "backdrop",
    "column",
    "selection",
    "search-text",
    "target-text",
    "spelling-error",
    "grammar-error",
    "highlight",
    "first-line-inherited",
    "scroll-marker",
    "scroll-marker-group",
    "scroll-button",
    "scrollbar",
    "scrollbar-thumb",
    "scrollbar-button",
    "scrollbar-track",
    "scrollbar-track-piece",
    "scrollbar-corner",
    "resizer",
    "input-list-button",
    "view-transition",
    "view-transition-group",
    "view-transition-image-pair",
    "view-transition-group-children",
    "view-transition-old",
    "view-transition-new",
    "placeholder",
    "file-selector-button",
    "details-content",
    "picker",
    "select-listbox",
    "permission-icon",
    "overscroll-area-parent",
    "overscroll-backdrop",
    "skeleton",
]

"""
Shadow root type.
"""
type ShadowRootType = Literal["user-agent", "open", "closed"]

"""
Document compatibility mode.
"""
type CompatibilityMode = Literal["QuirksMode", "LimitedQuirksMode", "NoQuirksMode"]

"""
ContainerSelector physical axes
"""
type PhysicalAxes = Literal["Horizontal", "Vertical", "Both"]

"""
ContainerSelector logical axes
"""
type LogicalAxes = Literal["Inline", "Block", "Both"]

"""
Physical scroll orientation
"""
type ScrollOrientation = Literal["horizontal", "vertical"]


@dataclass(kw_only=True, slots=True)
class Node:
    """
    DOM interaction is implemented in terms of mirror objects that represent the actual
    DOM nodes. DOMNode is a base node mirror type.
    """

    node_id: NodeId = field(metadata={"cdp_name": "nodeId"})
    parent_id: NodeId | None = field(default=None, metadata={"cdp_name": "parentId"})
    backend_node_id: BackendNodeId = field(metadata={"cdp_name": "backendNodeId"})
    node_type: int = field(metadata={"cdp_name": "nodeType"})
    node_name: str = field(metadata={"cdp_name": "nodeName"})
    local_name: str = field(metadata={"cdp_name": "localName"})
    node_value: str = field(metadata={"cdp_name": "nodeValue"})
    child_node_count: int | None = field(
        default=None, metadata={"cdp_name": "childNodeCount"}
    )
    children: list[Node] | None = field(default=None, metadata={"cdp_name": "children"})
    attributes: list[str] | None = field(
        default=None, metadata={"cdp_name": "attributes"}
    )
    document_url: str | None = field(default=None, metadata={"cdp_name": "documentURL"})
    base_url: str | None = field(default=None, metadata={"cdp_name": "baseURL"})
    public_id: str | None = field(default=None, metadata={"cdp_name": "publicId"})
    system_id: str | None = field(default=None, metadata={"cdp_name": "systemId"})
    internal_subset: str | None = field(
        default=None, metadata={"cdp_name": "internalSubset"}
    )
    xml_version: str | None = field(default=None, metadata={"cdp_name": "xmlVersion"})
    name: str | None = field(default=None, metadata={"cdp_name": "name"})
    value: str | None = field(default=None, metadata={"cdp_name": "value"})
    pseudo_type: PseudoType | None = field(
        default=None, metadata={"cdp_name": "pseudoType"}
    )
    pseudo_identifier: str | None = field(
        default=None, metadata={"cdp_name": "pseudoIdentifier"}
    )
    shadow_root_type: ShadowRootType | None = field(
        default=None, metadata={"cdp_name": "shadowRootType"}
    )
    frame_id: page.FrameId | None = field(
        default=None, metadata={"cdp_name": "frameId"}
    )
    content_document: Node | None = field(
        default=None, metadata={"cdp_name": "contentDocument"}
    )
    shadow_roots: list[Node] | None = field(
        default=None, metadata={"cdp_name": "shadowRoots"}
    )
    template_content: Node | None = field(
        default=None, metadata={"cdp_name": "templateContent"}
    )
    pseudo_elements: list[Node] | None = field(
        default=None, metadata={"cdp_name": "pseudoElements"}
    )
    imported_document: Node | None = field(
        default=None, metadata={"cdp_name": "importedDocument"}
    )
    distributed_nodes: list[BackendNode] | None = field(
        default=None, metadata={"cdp_name": "distributedNodes"}
    )
    is_svg: bool | None = field(default=None, metadata={"cdp_name": "isSVG"})
    compatibility_mode: CompatibilityMode | None = field(
        default=None, metadata={"cdp_name": "compatibilityMode"}
    )
    assigned_slot: BackendNode | None = field(
        default=None, metadata={"cdp_name": "assignedSlot"}
    )
    is_scrollable: bool | None = field(
        default=None, metadata={"cdp_name": "isScrollable"}
    )
    affected_by_starting_styles: bool | None = field(
        default=None, metadata={"cdp_name": "affectedByStartingStyles"}
    )
    adopted_style_sheets: list[StyleSheetId] | None = field(
        default=None, metadata={"cdp_name": "adoptedStyleSheets"}
    )
    ad_provenance: network.AdProvenance | None = field(
        default=None, metadata={"cdp_name": "adProvenance"}
    )


@dataclass(kw_only=True, slots=True)
class DetachedElementInfo:
    """
    A structure to hold the top-level node of a detached tree and an array of its
    retained descendants.
    """

    tree_node: Node = field(metadata={"cdp_name": "treeNode"})
    retained_node_ids: list[NodeId] = field(metadata={"cdp_name": "retainedNodeIds"})


@dataclass(kw_only=True, slots=True)
class RGBA:
    """
    A structure holding an RGBA color.
    """

    r: int = field(metadata={"cdp_name": "r"})
    g: int = field(metadata={"cdp_name": "g"})
    b: int = field(metadata={"cdp_name": "b"})
    a: float | None = field(default=None, metadata={"cdp_name": "a"})


"""
An array of quad vertices, x immediately followed by y for each point, points
clock-wise.
"""
Quad = list[Any]


@dataclass(kw_only=True, slots=True)
class BoxModel:
    """
    Box model.
    """

    content: Quad = field(metadata={"cdp_name": "content"})
    padding: Quad = field(metadata={"cdp_name": "padding"})
    border: Quad = field(metadata={"cdp_name": "border"})
    margin: Quad = field(metadata={"cdp_name": "margin"})
    width: int = field(metadata={"cdp_name": "width"})
    height: int = field(metadata={"cdp_name": "height"})
    shape_outside: ShapeOutsideInfo | None = field(
        default=None, metadata={"cdp_name": "shapeOutside"}
    )


@dataclass(kw_only=True, slots=True)
class ShapeOutsideInfo:
    """
    CSS Shape Outside details.
    """

    bounds: Quad = field(metadata={"cdp_name": "bounds"})
    shape: list[Any] = field(metadata={"cdp_name": "shape"})
    margin_shape: list[Any] = field(metadata={"cdp_name": "marginShape"})


@dataclass(kw_only=True, slots=True)
class Rect:
    """
    Rectangle.
    """

    x: float = field(metadata={"cdp_name": "x"})
    y: float = field(metadata={"cdp_name": "y"})
    width: float = field(metadata={"cdp_name": "width"})
    height: float = field(metadata={"cdp_name": "height"})


@dataclass(kw_only=True, slots=True)
class CSSComputedStyleProperty:
    name: str = field(metadata={"cdp_name": "name"})
    value: str = field(metadata={"cdp_name": "value"})
