# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import Any

from cdpify.shared.command_sender import CDPCommandSender

from .commands import (
    DeviceOrientationCommand,
    SetDeviceOrientationOverrideParams,
)


class DeviceOrientationClient:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def clear_device_orientation_override(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Clears the overridden Device Orientation.
        """
        result = await self._command_sender.send_raw(
            method=DeviceOrientationCommand.CLEAR_DEVICE_ORIENTATION_OVERRIDE,
            params=None,
            session_id=session_id,
        )
        return result

    async def set_device_orientation_override(
        self,
        *,
        alpha: float,
        beta: float,
        gamma: float,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Overrides the Device Orientation.
        """
        params = SetDeviceOrientationOverrideParams(alpha=alpha, beta=beta, gamma=gamma)

        result = await self._command_sender.send_raw(
            method=DeviceOrientationCommand.SET_DEVICE_ORIENTATION_OVERRIDE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
