# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Literal

from .types import (
    DragData,
    GestureSourceType,
    MouseButton,
    TimeSinceEpoch,
    TouchPoint,
)


class InputCommand(StrEnum):
    DISPATCH_DRAG_EVENT = "Input.dispatchDragEvent"
    DISPATCH_KEY_EVENT = "Input.dispatchKeyEvent"
    INSERT_TEXT = "Input.insertText"
    IME_SET_COMPOSITION = "Input.imeSetComposition"
    DISPATCH_MOUSE_EVENT = "Input.dispatchMouseEvent"
    DISPATCH_TOUCH_EVENT = "Input.dispatchTouchEvent"
    CANCEL_DRAGGING = "Input.cancelDragging"
    EMULATE_TOUCH_FROM_MOUSE_EVENT = "Input.emulateTouchFromMouseEvent"
    SET_IGNORE_INPUT_EVENTS = "Input.setIgnoreInputEvents"
    SET_INTERCEPT_DRAGS = "Input.setInterceptDrags"
    SYNTHESIZE_PINCH_GESTURE = "Input.synthesizePinchGesture"
    SYNTHESIZE_SCROLL_GESTURE = "Input.synthesizeScrollGesture"
    SYNTHESIZE_TAP_GESTURE = "Input.synthesizeTapGesture"


@dataclass(kw_only=True, slots=True)
class DispatchDragEventParams:
    """
    Dispatches a drag event into the page.
    """

    type: Literal["dragEnter", "dragOver", "drop", "dragCancel"] = field(
        metadata={"cdp_name": "type"}
    )
    x: float = field(metadata={"cdp_name": "x"})
    y: float = field(metadata={"cdp_name": "y"})
    data: DragData = field(metadata={"cdp_name": "data"})
    modifiers: int | None = field(default=None, metadata={"cdp_name": "modifiers"})


@dataclass(kw_only=True, slots=True)
class DispatchKeyEventParams:
    """
    Dispatches a key event to the page.
    """

    type: Literal["keyDown", "keyUp", "rawKeyDown", "char"] = field(
        metadata={"cdp_name": "type"}
    )
    modifiers: int | None = field(default=None, metadata={"cdp_name": "modifiers"})
    timestamp: TimeSinceEpoch | None = field(
        default=None, metadata={"cdp_name": "timestamp"}
    )
    text: str | None = field(default=None, metadata={"cdp_name": "text"})
    unmodified_text: str | None = field(
        default=None, metadata={"cdp_name": "unmodifiedText"}
    )
    key_identifier: str | None = field(
        default=None, metadata={"cdp_name": "keyIdentifier"}
    )
    code: str | None = field(default=None, metadata={"cdp_name": "code"})
    key: str | None = field(default=None, metadata={"cdp_name": "key"})
    windows_virtual_key_code: int | None = field(
        default=None, metadata={"cdp_name": "windowsVirtualKeyCode"}
    )
    native_virtual_key_code: int | None = field(
        default=None, metadata={"cdp_name": "nativeVirtualKeyCode"}
    )
    auto_repeat: bool | None = field(default=None, metadata={"cdp_name": "autoRepeat"})
    is_keypad: bool | None = field(default=None, metadata={"cdp_name": "isKeypad"})
    is_system_key: bool | None = field(
        default=None, metadata={"cdp_name": "isSystemKey"}
    )
    location: int | None = field(default=None, metadata={"cdp_name": "location"})
    commands: list[str] | None = field(default=None, metadata={"cdp_name": "commands"})


@dataclass(kw_only=True, slots=True)
class InsertTextParams:
    """
    This method emulates inserting text that doesn't come from a key press, for example
    an emoji keyboard or an IME.
    """

    text: str = field(metadata={"cdp_name": "text"})


@dataclass(kw_only=True, slots=True)
class ImeSetCompositionParams:
    """
    This method sets the current candidate text for IME. Use imeCommitComposition to
    commit the final text. Use imeSetComposition with empty string as text to cancel
    composition.
    """

    text: str = field(metadata={"cdp_name": "text"})
    selection_start: int = field(metadata={"cdp_name": "selectionStart"})
    selection_end: int = field(metadata={"cdp_name": "selectionEnd"})
    replacement_start: int | None = field(
        default=None, metadata={"cdp_name": "replacementStart"}
    )
    replacement_end: int | None = field(
        default=None, metadata={"cdp_name": "replacementEnd"}
    )


@dataclass(kw_only=True, slots=True)
class DispatchMouseEventParams:
    """
    Dispatches a mouse event to the page.
    """

    type: Literal["mousePressed", "mouseReleased", "mouseMoved", "mouseWheel"] = field(
        metadata={"cdp_name": "type"}
    )
    x: float = field(metadata={"cdp_name": "x"})
    y: float = field(metadata={"cdp_name": "y"})
    modifiers: int | None = field(default=None, metadata={"cdp_name": "modifiers"})
    timestamp: TimeSinceEpoch | None = field(
        default=None, metadata={"cdp_name": "timestamp"}
    )
    button: MouseButton | None = field(default=None, metadata={"cdp_name": "button"})
    buttons: int | None = field(default=None, metadata={"cdp_name": "buttons"})
    click_count: int | None = field(default=None, metadata={"cdp_name": "clickCount"})
    force: float | None = field(default=None, metadata={"cdp_name": "force"})
    tangential_pressure: float | None = field(
        default=None, metadata={"cdp_name": "tangentialPressure"}
    )
    tilt_x: float | None = field(default=None, metadata={"cdp_name": "tiltX"})
    tilt_y: float | None = field(default=None, metadata={"cdp_name": "tiltY"})
    twist: int | None = field(default=None, metadata={"cdp_name": "twist"})
    delta_x: float | None = field(default=None, metadata={"cdp_name": "deltaX"})
    delta_y: float | None = field(default=None, metadata={"cdp_name": "deltaY"})
    pointer_type: Literal["mouse", "pen"] | None = field(
        default=None, metadata={"cdp_name": "pointerType"}
    )


@dataclass(kw_only=True, slots=True)
class DispatchTouchEventParams:
    """
    Dispatches a touch event to the page.
    """

    type: Literal["touchStart", "touchEnd", "touchMove", "touchCancel"] = field(
        metadata={"cdp_name": "type"}
    )
    touch_points: list[TouchPoint] = field(metadata={"cdp_name": "touchPoints"})
    modifiers: int | None = field(default=None, metadata={"cdp_name": "modifiers"})
    timestamp: TimeSinceEpoch | None = field(
        default=None, metadata={"cdp_name": "timestamp"}
    )


@dataclass(kw_only=True, slots=True)
class EmulateTouchFromMouseEventParams:
    """
    Emulates touch event from the mouse event parameters.
    """

    type: Literal["mousePressed", "mouseReleased", "mouseMoved", "mouseWheel"] = field(
        metadata={"cdp_name": "type"}
    )
    x: int = field(metadata={"cdp_name": "x"})
    y: int = field(metadata={"cdp_name": "y"})
    button: MouseButton = field(metadata={"cdp_name": "button"})
    timestamp: TimeSinceEpoch | None = field(
        default=None, metadata={"cdp_name": "timestamp"}
    )
    delta_x: float | None = field(default=None, metadata={"cdp_name": "deltaX"})
    delta_y: float | None = field(default=None, metadata={"cdp_name": "deltaY"})
    modifiers: int | None = field(default=None, metadata={"cdp_name": "modifiers"})
    click_count: int | None = field(default=None, metadata={"cdp_name": "clickCount"})


@dataclass(kw_only=True, slots=True)
class SetIgnoreInputEventsParams:
    """
    Ignores input events (useful while auditing page).
    """

    ignore: bool = field(metadata={"cdp_name": "ignore"})


@dataclass(kw_only=True, slots=True)
class SetInterceptDragsParams:
    """
    Prevents default drag and drop behavior and instead emits `Input.dragIntercepted`
    events. Drag and drop behavior can be directly controlled via
    `Input.dispatchDragEvent`.
    """

    enabled: bool = field(metadata={"cdp_name": "enabled"})


@dataclass(kw_only=True, slots=True)
class SynthesizePinchGestureParams:
    """
    Synthesizes a pinch gesture over a time period by issuing appropriate touch events.
    """

    x: float = field(metadata={"cdp_name": "x"})
    y: float = field(metadata={"cdp_name": "y"})
    scale_factor: float = field(metadata={"cdp_name": "scaleFactor"})
    relative_speed: int | None = field(
        default=None, metadata={"cdp_name": "relativeSpeed"}
    )
    gesture_source_type: GestureSourceType | None = field(
        default=None, metadata={"cdp_name": "gestureSourceType"}
    )


@dataclass(kw_only=True, slots=True)
class SynthesizeScrollGestureParams:
    """
    Synthesizes a scroll gesture over a time period by issuing appropriate touch
    events.
    """

    x: float = field(metadata={"cdp_name": "x"})
    y: float = field(metadata={"cdp_name": "y"})
    x_distance: float | None = field(default=None, metadata={"cdp_name": "xDistance"})
    y_distance: float | None = field(default=None, metadata={"cdp_name": "yDistance"})
    x_overscroll: float | None = field(
        default=None, metadata={"cdp_name": "xOverscroll"}
    )
    y_overscroll: float | None = field(
        default=None, metadata={"cdp_name": "yOverscroll"}
    )
    prevent_fling: bool | None = field(
        default=None, metadata={"cdp_name": "preventFling"}
    )
    speed: int | None = field(default=None, metadata={"cdp_name": "speed"})
    gesture_source_type: GestureSourceType | None = field(
        default=None, metadata={"cdp_name": "gestureSourceType"}
    )
    repeat_count: int | None = field(default=None, metadata={"cdp_name": "repeatCount"})
    repeat_delay_ms: int | None = field(
        default=None, metadata={"cdp_name": "repeatDelayMs"}
    )
    interaction_marker_name: str | None = field(
        default=None, metadata={"cdp_name": "interactionMarkerName"}
    )


@dataclass(kw_only=True, slots=True)
class SynthesizeTapGestureParams:
    """
    Synthesizes a tap gesture over a time period by issuing appropriate touch events.
    """

    x: float = field(metadata={"cdp_name": "x"})
    y: float = field(metadata={"cdp_name": "y"})
    duration: int | None = field(default=None, metadata={"cdp_name": "duration"})
    tap_count: int | None = field(default=None, metadata={"cdp_name": "tapCount"})
    gesture_source_type: GestureSourceType | None = field(
        default=None, metadata={"cdp_name": "gestureSourceType"}
    )
