# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from cdpify.shared.models import CDPModel


@dataclass(kw_only=True, slots=True)
class TouchPoint(CDPModel):
    x: float
    y: float
    radius_x: float | None = None
    radius_y: float | None = None
    rotation_angle: float | None = None
    force: float | None = None
    tangential_pressure: float | None = None
    tilt_x: float | None = None
    tilt_y: float | None = None
    twist: int | None = None
    id: float | None = None


type GestureSourceType = Literal["default", "touch", "mouse"]

type MouseButton = Literal["none", "left", "middle", "right", "back", "forward"]

"""
UTC time in seconds, counted from January 1, 1970.
"""
TimeSinceEpoch = float


@dataclass(kw_only=True, slots=True)
class DragDataItem(CDPModel):
    mime_type: str
    data: str
    title: str | None = None
    base_url: str | None = None


@dataclass(kw_only=True, slots=True)
class DragData(CDPModel):
    items: list[DragDataItem]
    files: list[str] | None = None
    drag_operations_mask: int
