# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import Any

from pydantic_cpd.cdp import dom
from pydantic_cpd.cdp.base import CDPModel

from .types import *


class CompositingReasonsParams(CDPModel):
    """
    Provides the reasons why the given layer was composited.
    """

    layer_id: LayerId


class CompositingReasonsResult(CDPModel):
    compositing_reasons: list[str]
    compositing_reason_ids: list[str]


class LoadSnapshotParams(CDPModel):
    """
    Returns the snapshot identifier.
    """

    tiles: list[PictureTile]


class LoadSnapshotResult(CDPModel):
    snapshot_id: SnapshotId


class MakeSnapshotParams(CDPModel):
    """
    Returns the layer snapshot identifier.
    """

    layer_id: LayerId


class MakeSnapshotResult(CDPModel):
    snapshot_id: SnapshotId


class ProfileSnapshotParams(CDPModel):
    snapshot_id: SnapshotId
    min_repeat_count: int | None = None
    min_duration: float | None = None
    clip_rect: dom.Rect | None = None


class ProfileSnapshotResult(CDPModel):
    timings: list[PaintProfile]


class ReleaseSnapshotParams(CDPModel):
    """
    Releases layer snapshot captured by the back-end.
    """

    snapshot_id: SnapshotId


class ReplaySnapshotParams(CDPModel):
    """
    Replays the layer snapshot and returns the resulting bitmap.
    """

    snapshot_id: SnapshotId
    from_step: int | None = None
    to_step: int | None = None
    scale: float | None = None


class ReplaySnapshotResult(CDPModel):
    data_u_r_l: str


class SnapshotCommandLogParams(CDPModel):
    """
    Replays the layer snapshot and returns canvas log.
    """

    snapshot_id: SnapshotId


class SnapshotCommandLogResult(CDPModel):
    command_log: list[dict[str, Any]]
