# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP WebAudio Domain."""

from .commands import GetRealtimeDataParams, GetRealtimeDataResult, WebAudioCommand
from .domain import WebAudio
from .events import (
    AudioListenerCreatedEvent,
    AudioListenerWillBeDestroyedEvent,
    AudioNodeCreatedEvent,
    AudioNodeWillBeDestroyedEvent,
    AudioParamCreatedEvent,
    AudioParamWillBeDestroyedEvent,
    ContextChangedEvent,
    ContextCreatedEvent,
    ContextWillBeDestroyedEvent,
    NodeParamConnectedEvent,
    NodeParamDisconnectedEvent,
    NodesConnectedEvent,
    NodesDisconnectedEvent,
    WebAudioEvent,
)
from .types import (
    AudioListener,
    AudioNode,
    AudioParam,
    AutomationRate,
    BaseAudioContext,
    ChannelCountMode,
    ChannelInterpretation,
    ContextRealtimeData,
    ContextState,
    ContextType,
    GraphObjectId,
    NodeType,
    ParamType,
)

__all__ = [
    "AudioListener",
    "AudioListenerCreatedEvent",
    "AudioListenerWillBeDestroyedEvent",
    "AudioNode",
    "AudioNodeCreatedEvent",
    "AudioNodeWillBeDestroyedEvent",
    "AudioParam",
    "AudioParamCreatedEvent",
    "AudioParamWillBeDestroyedEvent",
    "AutomationRate",
    "BaseAudioContext",
    "ChannelCountMode",
    "ChannelInterpretation",
    "ContextChangedEvent",
    "ContextCreatedEvent",
    "ContextRealtimeData",
    "ContextState",
    "ContextType",
    "ContextWillBeDestroyedEvent",
    "GetRealtimeDataParams",
    "GetRealtimeDataResult",
    "GraphObjectId",
    "NodeParamConnectedEvent",
    "NodeParamDisconnectedEvent",
    "NodeType",
    "NodesConnectedEvent",
    "NodesDisconnectedEvent",
    "ParamType",
    "WebAudio",
    "WebAudioCommand",
    "WebAudioEvent",
]
