# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from dataclasses import dataclass
from enum import StrEnum

from cdpify.shared.models import CDPEvent

from .types import (
    AudioListener,
    AudioNode,
    AudioParam,
    BaseAudioContext,
    GraphObjectId,
)


class WebAudioEvent(StrEnum):
    CONTEXT_CREATED = "WebAudio.contextCreated"
    CONTEXT_WILL_BE_DESTROYED = "WebAudio.contextWillBeDestroyed"
    CONTEXT_CHANGED = "WebAudio.contextChanged"
    AUDIO_LISTENER_CREATED = "WebAudio.audioListenerCreated"
    AUDIO_LISTENER_WILL_BE_DESTROYED = "WebAudio.audioListenerWillBeDestroyed"
    AUDIO_NODE_CREATED = "WebAudio.audioNodeCreated"
    AUDIO_NODE_WILL_BE_DESTROYED = "WebAudio.audioNodeWillBeDestroyed"
    AUDIO_PARAM_CREATED = "WebAudio.audioParamCreated"
    AUDIO_PARAM_WILL_BE_DESTROYED = "WebAudio.audioParamWillBeDestroyed"
    NODES_CONNECTED = "WebAudio.nodesConnected"
    NODES_DISCONNECTED = "WebAudio.nodesDisconnected"
    NODE_PARAM_CONNECTED = "WebAudio.nodeParamConnected"
    NODE_PARAM_DISCONNECTED = "WebAudio.nodeParamDisconnected"


@dataclass(kw_only=True, slots=True)
class ContextCreatedEvent(CDPEvent):
    """
    Notifies that a new BaseAudioContext has been created.
    """

    context: BaseAudioContext


@dataclass(kw_only=True, slots=True)
class ContextWillBeDestroyedEvent(CDPEvent):
    """
    Notifies that an existing BaseAudioContext will be destroyed.
    """

    context_id: GraphObjectId


@dataclass(kw_only=True, slots=True)
class ContextChangedEvent(CDPEvent):
    """
    Notifies that existing BaseAudioContext has changed some properties (id stays the
    same)..
    """

    context: BaseAudioContext


@dataclass(kw_only=True, slots=True)
class AudioListenerCreatedEvent(CDPEvent):
    """
    Notifies that the construction of an AudioListener has finished.
    """

    listener: AudioListener


@dataclass(kw_only=True, slots=True)
class AudioListenerWillBeDestroyedEvent(CDPEvent):
    """
    Notifies that a new AudioListener has been created.
    """

    context_id: GraphObjectId
    listener_id: GraphObjectId


@dataclass(kw_only=True, slots=True)
class AudioNodeCreatedEvent(CDPEvent):
    """
    Notifies that a new AudioNode has been created.
    """

    node: AudioNode


@dataclass(kw_only=True, slots=True)
class AudioNodeWillBeDestroyedEvent(CDPEvent):
    """
    Notifies that an existing AudioNode has been destroyed.
    """

    context_id: GraphObjectId
    node_id: GraphObjectId


@dataclass(kw_only=True, slots=True)
class AudioParamCreatedEvent(CDPEvent):
    """
    Notifies that a new AudioParam has been created.
    """

    param: AudioParam


@dataclass(kw_only=True, slots=True)
class AudioParamWillBeDestroyedEvent(CDPEvent):
    """
    Notifies that an existing AudioParam has been destroyed.
    """

    context_id: GraphObjectId
    node_id: GraphObjectId
    param_id: GraphObjectId


@dataclass(kw_only=True, slots=True)
class NodesConnectedEvent(CDPEvent):
    """
    Notifies that two AudioNodes are connected.
    """

    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: float | None = None
    destination_input_index: float | None = None


@dataclass(kw_only=True, slots=True)
class NodesDisconnectedEvent(CDPEvent):
    """
    Notifies that AudioNodes are disconnected. The destination can be null, and it
    means all the outgoing connections from the source are disconnected.
    """

    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: float | None = None
    destination_input_index: float | None = None


@dataclass(kw_only=True, slots=True)
class NodeParamConnectedEvent(CDPEvent):
    """
    Notifies that an AudioNode is connected to an AudioParam.
    """

    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: float | None = None


@dataclass(kw_only=True, slots=True)
class NodeParamDisconnectedEvent(CDPEvent):
    """
    Notifies that an AudioNode is disconnected to an AudioParam.
    """

    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: float | None = None
