# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.executor import CommandExecutor
from cdpify.shared.decorators import deprecated

from .commands import (
    CanClearBrowserCacheResult,
    CanClearBrowserCookiesResult,
    CanEmulateNetworkConditionsResult,
    ConfigureDurableMessagesParams,
    DeleteCookiesParams,
    DeleteDeviceBoundSessionParams,
    EmulateNetworkConditionsByRuleParams,
    EmulateNetworkConditionsByRuleResult,
    EmulateNetworkConditionsParams,
    EnableDeviceBoundSessionsParams,
    EnableParams,
    EnableReportingApiParams,
    FetchSchemefulSiteParams,
    FetchSchemefulSiteResult,
    GetAllCookiesResult,
    GetCertificateParams,
    GetCertificateResult,
    GetCookiesParams,
    GetCookiesResult,
    GetRequestPostDataParams,
    GetRequestPostDataResult,
    GetResponseBodyParams,
    GetResponseBodyResult,
    GetSecurityIsolationStatusParams,
    GetSecurityIsolationStatusResult,
    LoadNetworkResourceParams,
    LoadNetworkResourceResult,
    NetworkCommand,
    OverrideNetworkStateParams,
    ReplayXHRParams,
    SearchInResponseBodyParams,
    SearchInResponseBodyResult,
    SetAttachDebugStackParams,
    SetBlockedURLsParams,
    SetBypassServiceWorkerParams,
    SetCacheDisabledParams,
    SetCookieControlsParams,
    SetCookieParams,
    SetCookieResult,
    SetCookiesParams,
    SetExtraHTTPHeadersParams,
    SetUserAgentOverrideParams,
    StreamResourceContentParams,
    StreamResourceContentResult,
)
from .types import (
    BlockPattern,
    ConnectionType,
    CookieParam,
    CookiePartitionKey,
    CookiePriority,
    CookieSameSite,
    CookieSourceScheme,
    DeviceBoundSessionKey,
    Headers,
    LoadNetworkResourceOptions,
    NetworkConditions,
    RequestId,
    TimeSinceEpoch,
)

if TYPE_CHECKING:
    from cdpify.domains import emulation, page


class Network:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    @deprecated()
    async def can_clear_browser_cache(
        self,
    ) -> CanClearBrowserCacheResult:
        """
        Tells whether clearing browser cache is supported.
        """
        result = await self._executor.execute(
            method=NetworkCommand.CAN_CLEAR_BROWSER_CACHE,
            params=None,
        )
        return decode_cdp(CanClearBrowserCacheResult, result)

    @deprecated()
    async def can_clear_browser_cookies(
        self,
    ) -> CanClearBrowserCookiesResult:
        """
        Tells whether clearing browser cookies is supported.
        """
        result = await self._executor.execute(
            method=NetworkCommand.CAN_CLEAR_BROWSER_COOKIES,
            params=None,
        )
        return decode_cdp(CanClearBrowserCookiesResult, result)

    @deprecated()
    async def can_emulate_network_conditions(
        self,
    ) -> CanEmulateNetworkConditionsResult:
        """
        Tells whether emulation of network conditions is supported.
        """
        result = await self._executor.execute(
            method=NetworkCommand.CAN_EMULATE_NETWORK_CONDITIONS,
            params=None,
        )
        return decode_cdp(CanEmulateNetworkConditionsResult, result)

    async def clear_browser_cache(
        self,
    ) -> None:
        """
        Clears browser cache.
        """
        await self._executor.execute(
            method=NetworkCommand.CLEAR_BROWSER_CACHE,
            params=None,
        )

    async def clear_browser_cookies(
        self,
    ) -> None:
        """
        Clears browser cookies.
        """
        await self._executor.execute(
            method=NetworkCommand.CLEAR_BROWSER_COOKIES,
            params=None,
        )

    async def delete_cookies(
        self,
        *,
        name: str,
        url: str | None = None,
        domain: str | None = None,
        path: str | None = None,
        partition_key: CookiePartitionKey | None = None,
    ) -> None:
        """
        Deletes browser cookies with matching name and url or domain/path/partitionKey
        pair.
        """
        params = DeleteCookiesParams(
            name=name, url=url, domain=domain, path=path, partition_key=partition_key
        )

        await self._executor.execute(
            method=NetworkCommand.DELETE_COOKIES,
            params=encode_cdp(params),
        )

    async def disable(
        self,
    ) -> None:
        """
        Disables network tracking, prevents network events from being sent to the
        client.
        """
        await self._executor.execute(
            method=NetworkCommand.DISABLE,
            params=None,
        )

    @deprecated()
    async def emulate_network_conditions(
        self,
        *,
        offline: bool,
        latency: float,
        download_throughput: float,
        upload_throughput: float,
        connection_type: ConnectionType | None = None,
        packet_loss: float | None = None,
        packet_queue_length: int | None = None,
        packet_reordering: bool | None = None,
    ) -> None:
        """
        Activates emulation of network conditions. This command is deprecated in favor
        of the emulateNetworkConditionsByRule and overrideNetworkState commands, which
        can be used together to the same effect.
        """
        params = EmulateNetworkConditionsParams(
            offline=offline,
            latency=latency,
            download_throughput=download_throughput,
            upload_throughput=upload_throughput,
            connection_type=connection_type,
            packet_loss=packet_loss,
            packet_queue_length=packet_queue_length,
            packet_reordering=packet_reordering,
        )

        await self._executor.execute(
            method=NetworkCommand.EMULATE_NETWORK_CONDITIONS,
            params=encode_cdp(params),
        )

    async def emulate_network_conditions_by_rule(
        self,
        *,
        offline: bool | None = None,
        emulate_offline_service_worker: bool | None = None,
        matched_network_conditions: list[NetworkConditions],
    ) -> EmulateNetworkConditionsByRuleResult:
        """
        Activates emulation of network conditions for individual requests using URL
        match patterns. Unlike the deprecated Network.emulateNetworkConditions this
        method does not affect `navigator` state. Use Network.overrideNetworkState to
        explicitly modify `navigator` behavior.
        """
        params = EmulateNetworkConditionsByRuleParams(
            offline=offline,
            emulate_offline_service_worker=emulate_offline_service_worker,
            matched_network_conditions=matched_network_conditions,
        )

        result = await self._executor.execute(
            method=NetworkCommand.EMULATE_NETWORK_CONDITIONS_BY_RULE,
            params=encode_cdp(params),
        )
        return decode_cdp(EmulateNetworkConditionsByRuleResult, result)

    async def override_network_state(
        self,
        *,
        offline: bool,
        latency: float,
        download_throughput: float,
        upload_throughput: float,
        connection_type: ConnectionType | None = None,
    ) -> None:
        """
        Override the state of navigator.onLine and navigator.connection.
        """
        params = OverrideNetworkStateParams(
            offline=offline,
            latency=latency,
            download_throughput=download_throughput,
            upload_throughput=upload_throughput,
            connection_type=connection_type,
        )

        await self._executor.execute(
            method=NetworkCommand.OVERRIDE_NETWORK_STATE,
            params=encode_cdp(params),
        )

    async def enable(
        self,
        *,
        max_total_buffer_size: int | None = None,
        max_resource_buffer_size: int | None = None,
        max_post_data_size: int | None = None,
        report_direct_socket_traffic: bool | None = None,
        enable_durable_messages: bool | None = None,
    ) -> None:
        """
        Enables network tracking, network events will now be delivered to the client.
        """
        params = EnableParams(
            max_total_buffer_size=max_total_buffer_size,
            max_resource_buffer_size=max_resource_buffer_size,
            max_post_data_size=max_post_data_size,
            report_direct_socket_traffic=report_direct_socket_traffic,
            enable_durable_messages=enable_durable_messages,
        )

        await self._executor.execute(
            method=NetworkCommand.ENABLE,
            params=encode_cdp(params),
        )

    async def configure_durable_messages(
        self,
        *,
        max_total_buffer_size: int | None = None,
        max_resource_buffer_size: int | None = None,
    ) -> None:
        """
        Configures storing response bodies outside of renderer, so that these survive a
        cross-process navigation. If maxTotalBufferSize is not set, durable messages are
        disabled.
        """
        params = ConfigureDurableMessagesParams(
            max_total_buffer_size=max_total_buffer_size,
            max_resource_buffer_size=max_resource_buffer_size,
        )

        await self._executor.execute(
            method=NetworkCommand.CONFIGURE_DURABLE_MESSAGES,
            params=encode_cdp(params),
        )

    @deprecated()
    async def get_all_cookies(
        self,
    ) -> GetAllCookiesResult:
        """
        Returns all browser cookies. Depending on the backend support, will return
        detailed cookie information in the `cookies` field. Deprecated. Use
        Storage.getCookies instead.
        """
        result = await self._executor.execute(
            method=NetworkCommand.GET_ALL_COOKIES,
            params=None,
        )
        return decode_cdp(GetAllCookiesResult, result)

    async def get_certificate(
        self,
        *,
        origin: str,
    ) -> GetCertificateResult:
        """
        Returns the DER-encoded certificate.
        """
        params = GetCertificateParams(origin=origin)

        result = await self._executor.execute(
            method=NetworkCommand.GET_CERTIFICATE,
            params=encode_cdp(params),
        )
        return decode_cdp(GetCertificateResult, result)

    async def get_cookies(
        self,
        *,
        urls: list[str] | None = None,
    ) -> GetCookiesResult:
        """
        Returns all browser cookies for the current URL. Depending on the backend
        support, will return detailed cookie information in the `cookies` field.
        """
        params = GetCookiesParams(urls=urls)

        result = await self._executor.execute(
            method=NetworkCommand.GET_COOKIES,
            params=encode_cdp(params),
        )
        return decode_cdp(GetCookiesResult, result)

    async def get_response_body(
        self,
        *,
        request_id: RequestId,
    ) -> GetResponseBodyResult:
        """
        Returns content served for the given request.
        """
        params = GetResponseBodyParams(request_id=request_id)

        result = await self._executor.execute(
            method=NetworkCommand.GET_RESPONSE_BODY,
            params=encode_cdp(params),
        )
        return decode_cdp(GetResponseBodyResult, result)

    async def get_request_post_data(
        self,
        *,
        request_id: RequestId,
    ) -> GetRequestPostDataResult:
        """
        Returns post data sent with the request. Returns an error when no data was sent
        with the request.
        """
        params = GetRequestPostDataParams(request_id=request_id)

        result = await self._executor.execute(
            method=NetworkCommand.GET_REQUEST_POST_DATA,
            params=encode_cdp(params),
        )
        return decode_cdp(GetRequestPostDataResult, result)

    async def replay_xhr(
        self,
        *,
        request_id: RequestId,
    ) -> None:
        """
        This method sends a new XMLHttpRequest which is identical to the original one.
        The following parameters should be identical: method, url, async, request body,
        extra headers, withCredentials attribute, user, password.
        """
        params = ReplayXHRParams(request_id=request_id)

        await self._executor.execute(
            method=NetworkCommand.REPLAY_XHR,
            params=encode_cdp(params),
        )

    async def search_in_response_body(
        self,
        *,
        request_id: RequestId,
        query: str,
        case_sensitive: bool | None = None,
        is_regex: bool | None = None,
    ) -> SearchInResponseBodyResult:
        """
        Searches for given string in response content.
        """
        params = SearchInResponseBodyParams(
            request_id=request_id,
            query=query,
            case_sensitive=case_sensitive,
            is_regex=is_regex,
        )

        result = await self._executor.execute(
            method=NetworkCommand.SEARCH_IN_RESPONSE_BODY,
            params=encode_cdp(params),
        )
        return decode_cdp(SearchInResponseBodyResult, result)

    async def set_blocked_ur_ls(
        self,
        *,
        url_patterns: list[BlockPattern] | None = None,
        urls: list[str] | None = None,
    ) -> None:
        """
        Blocks URLs from loading.
        """
        params = SetBlockedURLsParams(url_patterns=url_patterns, urls=urls)

        await self._executor.execute(
            method=NetworkCommand.SET_BLOCKED_UR_LS,
            params=encode_cdp(params),
        )

    async def set_bypass_service_worker(
        self,
        *,
        bypass: bool,
    ) -> None:
        """
        Toggles ignoring of service worker for each request.
        """
        params = SetBypassServiceWorkerParams(bypass=bypass)

        await self._executor.execute(
            method=NetworkCommand.SET_BYPASS_SERVICE_WORKER,
            params=encode_cdp(params),
        )

    async def set_cache_disabled(
        self,
        *,
        cache_disabled: bool,
    ) -> None:
        """
        Toggles ignoring cache for each request. If `true`, cache will not be used.
        """
        params = SetCacheDisabledParams(cache_disabled=cache_disabled)

        await self._executor.execute(
            method=NetworkCommand.SET_CACHE_DISABLED,
            params=encode_cdp(params),
        )

    async def set_cookie(
        self,
        *,
        name: str,
        value: str,
        url: str | None = None,
        domain: str | None = None,
        path: str | None = None,
        secure: bool | None = None,
        http_only: bool | None = None,
        same_site: CookieSameSite | None = None,
        expires: TimeSinceEpoch | None = None,
        priority: CookiePriority | None = None,
        source_scheme: CookieSourceScheme | None = None,
        source_port: int | None = None,
        partition_key: CookiePartitionKey | None = None,
    ) -> SetCookieResult:
        """
        Sets a cookie with the given cookie data; may overwrite equivalent cookies if
        they exist.
        """
        params = SetCookieParams(
            name=name,
            value=value,
            url=url,
            domain=domain,
            path=path,
            secure=secure,
            http_only=http_only,
            same_site=same_site,
            expires=expires,
            priority=priority,
            source_scheme=source_scheme,
            source_port=source_port,
            partition_key=partition_key,
        )

        result = await self._executor.execute(
            method=NetworkCommand.SET_COOKIE,
            params=encode_cdp(params),
        )
        return decode_cdp(SetCookieResult, result)

    async def set_cookies(
        self,
        *,
        cookies: list[CookieParam],
    ) -> None:
        """
        Sets given cookies.
        """
        params = SetCookiesParams(cookies=cookies)

        await self._executor.execute(
            method=NetworkCommand.SET_COOKIES,
            params=encode_cdp(params),
        )

    async def set_extra_http_headers(
        self,
        *,
        headers: Headers,
    ) -> None:
        """
        Specifies whether to always send extra HTTP headers with the requests from this
        page.
        """
        params = SetExtraHTTPHeadersParams(headers=headers)

        await self._executor.execute(
            method=NetworkCommand.SET_EXTRA_HTTP_HEADERS,
            params=encode_cdp(params),
        )

    async def set_attach_debug_stack(
        self,
        *,
        enabled: bool,
    ) -> None:
        """
        Specifies whether to attach a page script stack id in requests
        """
        params = SetAttachDebugStackParams(enabled=enabled)

        await self._executor.execute(
            method=NetworkCommand.SET_ATTACH_DEBUG_STACK,
            params=encode_cdp(params),
        )

    async def set_user_agent_override(
        self,
        *,
        user_agent: str,
        accept_language: str | None = None,
        platform: str | None = None,
        user_agent_metadata: emulation.UserAgentMetadata | None = None,
    ) -> None:
        """
        Allows overriding user agent with the given string.
        """
        params = SetUserAgentOverrideParams(
            user_agent=user_agent,
            accept_language=accept_language,
            platform=platform,
            user_agent_metadata=user_agent_metadata,
        )

        await self._executor.execute(
            method=NetworkCommand.SET_USER_AGENT_OVERRIDE,
            params=encode_cdp(params),
        )

    async def stream_resource_content(
        self,
        *,
        request_id: RequestId,
    ) -> StreamResourceContentResult:
        """
        Enables streaming of the response for the given requestId. If enabled, the
        dataReceived event contains the data that was received during streaming.
        """
        params = StreamResourceContentParams(request_id=request_id)

        result = await self._executor.execute(
            method=NetworkCommand.STREAM_RESOURCE_CONTENT,
            params=encode_cdp(params),
        )
        return decode_cdp(StreamResourceContentResult, result)

    async def get_security_isolation_status(
        self,
        *,
        frame_id: page.FrameId | None = None,
    ) -> GetSecurityIsolationStatusResult:
        """
        Returns information about the COEP/COOP isolation status.
        """
        params = GetSecurityIsolationStatusParams(frame_id=frame_id)

        result = await self._executor.execute(
            method=NetworkCommand.GET_SECURITY_ISOLATION_STATUS,
            params=encode_cdp(params),
        )
        return decode_cdp(GetSecurityIsolationStatusResult, result)

    async def enable_reporting_api(
        self,
        *,
        enable: bool,
    ) -> None:
        """
        Enables tracking for the Reporting API, events generated by the Reporting API
        will now be delivered to the client. Enabling triggers 'reportingApiReportAdded'
        for all existing reports.
        """
        params = EnableReportingApiParams(enable=enable)

        await self._executor.execute(
            method=NetworkCommand.ENABLE_REPORTING_API,
            params=encode_cdp(params),
        )

    async def enable_device_bound_sessions(
        self,
        *,
        enable: bool,
    ) -> None:
        """
        Sets up tracking device bound sessions and fetching of initial set of sessions.
        """
        params = EnableDeviceBoundSessionsParams(enable=enable)

        await self._executor.execute(
            method=NetworkCommand.ENABLE_DEVICE_BOUND_SESSIONS,
            params=encode_cdp(params),
        )

    async def delete_device_bound_session(
        self,
        *,
        key: DeviceBoundSessionKey,
    ) -> None:
        """
        Deletes a device bound session.
        """
        params = DeleteDeviceBoundSessionParams(key=key)

        await self._executor.execute(
            method=NetworkCommand.DELETE_DEVICE_BOUND_SESSION,
            params=encode_cdp(params),
        )

    async def fetch_schemeful_site(
        self,
        *,
        origin: str,
    ) -> FetchSchemefulSiteResult:
        """
        Fetches the schemeful site for a specific origin.
        """
        params = FetchSchemefulSiteParams(origin=origin)

        result = await self._executor.execute(
            method=NetworkCommand.FETCH_SCHEMEFUL_SITE,
            params=encode_cdp(params),
        )
        return decode_cdp(FetchSchemefulSiteResult, result)

    async def load_network_resource(
        self,
        *,
        frame_id: page.FrameId | None = None,
        url: str,
        options: LoadNetworkResourceOptions,
    ) -> LoadNetworkResourceResult:
        """
        Fetches the resource and returns the content.
        """
        params = LoadNetworkResourceParams(frame_id=frame_id, url=url, options=options)

        result = await self._executor.execute(
            method=NetworkCommand.LOAD_NETWORK_RESOURCE,
            params=encode_cdp(params),
        )
        return decode_cdp(LoadNetworkResourceResult, result)

    async def set_cookie_controls(
        self,
        *,
        enable_third_party_cookie_restriction: bool,
    ) -> None:
        """
        Sets Controls for third-party cookie access Page reload is required before the
        new cookie behavior will be observed
        """
        params = SetCookieControlsParams(
            enable_third_party_cookie_restriction=enable_third_party_cookie_restriction
        )

        await self._executor.execute(
            method=NetworkCommand.SET_COOKIE_CONTROLS,
            params=encode_cdp(params),
        )
