# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Literal

from cdpify.domains import page
from cdpify.shared.models import CDPEvent

from .types import (
    AssociatedCookie,
    AuthChallenge,
    BlockedReason,
    BlockedSetCookieWithReason,
    ChallengeEventDetails,
    ClientSecurityState,
    ConnectTiming,
    CookiePartitionKey,
    CorsErrorStatus,
    CreationEventDetails,
    DeviceBoundSession,
    DeviceBoundSessionEventId,
    DeviceBoundSessionWithUsage,
    DirectTCPSocketOptions,
    DirectUDPMessage,
    DirectUDPSocketOptions,
    ErrorReason,
    ExemptedSetCookieWithReason,
    Headers,
    Initiator,
    InterceptionId,
    IPAddressSpace,
    LoaderId,
    MonotonicTime,
    RefreshEventDetails,
    RenderBlockingBehavior,
    ReportingApiEndpoint,
    ReportingApiReport,
    Request,
    RequestId,
    ResourcePriority,
    ResourceType,
    Response,
    SignedExchangeInfo,
    TerminationEventDetails,
    TimeSinceEpoch,
    TrustTokenOperationType,
    WebSocketFrame,
    WebSocketRequest,
    WebSocketResponse,
)


class NetworkEvent(StrEnum):
    DATA_RECEIVED = "Network.dataReceived"
    EVENT_SOURCE_MESSAGE_RECEIVED = "Network.eventSourceMessageReceived"
    LOADING_FAILED = "Network.loadingFailed"
    LOADING_FINISHED = "Network.loadingFinished"
    REQUEST_INTERCEPTED = "Network.requestIntercepted"
    REQUEST_SERVED_FROM_CACHE = "Network.requestServedFromCache"
    REQUEST_WILL_BE_SENT = "Network.requestWillBeSent"
    RESOURCE_CHANGED_PRIORITY = "Network.resourceChangedPriority"
    SIGNED_EXCHANGE_RECEIVED = "Network.signedExchangeReceived"
    RESPONSE_RECEIVED = "Network.responseReceived"
    WEB_SOCKET_CLOSED = "Network.webSocketClosed"
    WEB_SOCKET_CREATED = "Network.webSocketCreated"
    WEB_SOCKET_FRAME_ERROR = "Network.webSocketFrameError"
    WEB_SOCKET_FRAME_RECEIVED = "Network.webSocketFrameReceived"
    WEB_SOCKET_FRAME_SENT = "Network.webSocketFrameSent"
    WEB_SOCKET_HANDSHAKE_RESPONSE_RECEIVED = (
        "Network.webSocketHandshakeResponseReceived"
    )
    WEB_SOCKET_WILL_SEND_HANDSHAKE_REQUEST = "Network.webSocketWillSendHandshakeRequest"
    WEB_TRANSPORT_CREATED = "Network.webTransportCreated"
    WEB_TRANSPORT_CONNECTION_ESTABLISHED = "Network.webTransportConnectionEstablished"
    WEB_TRANSPORT_CLOSED = "Network.webTransportClosed"
    DIRECT_TCP_SOCKET_CREATED = "Network.directTCPSocketCreated"
    DIRECT_TCP_SOCKET_OPENED = "Network.directTCPSocketOpened"
    DIRECT_TCP_SOCKET_ABORTED = "Network.directTCPSocketAborted"
    DIRECT_TCP_SOCKET_CLOSED = "Network.directTCPSocketClosed"
    DIRECT_TCP_SOCKET_CHUNK_SENT = "Network.directTCPSocketChunkSent"
    DIRECT_TCP_SOCKET_CHUNK_RECEIVED = "Network.directTCPSocketChunkReceived"
    DIRECT_UDP_SOCKET_JOINED_MULTICAST_GROUP = (
        "Network.directUDPSocketJoinedMulticastGroup"
    )
    DIRECT_UDP_SOCKET_LEFT_MULTICAST_GROUP = "Network.directUDPSocketLeftMulticastGroup"
    DIRECT_UDP_SOCKET_CREATED = "Network.directUDPSocketCreated"
    DIRECT_UDP_SOCKET_OPENED = "Network.directUDPSocketOpened"
    DIRECT_UDP_SOCKET_ABORTED = "Network.directUDPSocketAborted"
    DIRECT_UDP_SOCKET_CLOSED = "Network.directUDPSocketClosed"
    DIRECT_UDP_SOCKET_CHUNK_SENT = "Network.directUDPSocketChunkSent"
    DIRECT_UDP_SOCKET_CHUNK_RECEIVED = "Network.directUDPSocketChunkReceived"
    REQUEST_WILL_BE_SENT_EXTRA_INFO = "Network.requestWillBeSentExtraInfo"
    RESPONSE_RECEIVED_EXTRA_INFO = "Network.responseReceivedExtraInfo"
    RESPONSE_RECEIVED_EARLY_HINTS = "Network.responseReceivedEarlyHints"
    TRUST_TOKEN_OPERATION_DONE = "Network.trustTokenOperationDone"
    POLICY_UPDATED = "Network.policyUpdated"
    REPORTING_API_REPORT_ADDED = "Network.reportingApiReportAdded"
    REPORTING_API_REPORT_UPDATED = "Network.reportingApiReportUpdated"
    REPORTING_API_ENDPOINTS_CHANGED_FOR_ORIGIN = (
        "Network.reportingApiEndpointsChangedForOrigin"
    )
    DEVICE_BOUND_SESSIONS_ADDED = "Network.deviceBoundSessionsAdded"
    DEVICE_BOUND_SESSION_EVENT_OCCURRED = "Network.deviceBoundSessionEventOccurred"


@dataclass(kw_only=True, slots=True)
class DataReceivedEvent(CDPEvent):
    """
    Fired when data chunk was received over the network.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    data_length: int
    encoded_data_length: int
    data: str | None = None


@dataclass(kw_only=True, slots=True)
class EventSourceMessageReceivedEvent(CDPEvent):
    """
    Fired when EventSource message is received.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    event_name: str
    event_id: str
    data: str


@dataclass(kw_only=True, slots=True)
class LoadingFailedEvent(CDPEvent):
    """
    Fired when HTTP request has failed to load.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    type: ResourceType
    error_text: str
    canceled: bool | None = None
    blocked_reason: BlockedReason | None = None
    cors_error_status: CorsErrorStatus | None = None


@dataclass(kw_only=True, slots=True)
class LoadingFinishedEvent(CDPEvent):
    """
    Fired when HTTP request has finished loading.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    encoded_data_length: float


@dataclass(kw_only=True, slots=True)
class RequestInterceptedEvent(CDPEvent):
    """
    Details of an intercepted HTTP request, which must be either allowed, blocked,
    modified or mocked. Deprecated, use Fetch.requestPaused instead.
    """

    interception_id: InterceptionId
    request: Request
    frame_id: page.FrameId
    resource_type: ResourceType
    is_navigation_request: bool
    is_download: bool | None = None
    redirect_url: str | None = None
    auth_challenge: AuthChallenge | None = None
    response_error_reason: ErrorReason | None = None
    response_status_code: int | None = None
    response_headers: Headers | None = None
    request_id: RequestId | None = None


@dataclass(kw_only=True, slots=True)
class RequestServedFromCacheEvent(CDPEvent):
    """
    Fired if request ended up loading from cache.
    """

    request_id: RequestId


@dataclass(kw_only=True, slots=True)
class RequestWillBeSentEvent(CDPEvent):
    """
    Fired when page is about to send HTTP request.
    """

    request_id: RequestId
    loader_id: LoaderId
    document_url: str | None = None
    request: Request
    timestamp: MonotonicTime
    wall_time: TimeSinceEpoch
    initiator: Initiator
    redirect_has_extra_info: bool
    redirect_response: Response | None = None
    type: ResourceType | None = None
    frame_id: page.FrameId | None = None
    has_user_gesture: bool | None = None
    render_blocking_behavior: RenderBlockingBehavior | None = None


@dataclass(kw_only=True, slots=True)
class ResourceChangedPriorityEvent(CDPEvent):
    """
    Fired when resource loading priority is changed
    """

    request_id: RequestId
    new_priority: ResourcePriority
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class SignedExchangeReceivedEvent(CDPEvent):
    """
    Fired when a signed exchange was received over the network
    """

    request_id: RequestId
    info: SignedExchangeInfo


@dataclass(kw_only=True, slots=True)
class ResponseReceivedEvent(CDPEvent):
    """
    Fired when HTTP response is available.
    """

    request_id: RequestId
    loader_id: LoaderId
    timestamp: MonotonicTime
    type: ResourceType
    response: Response
    has_extra_info: bool
    frame_id: page.FrameId | None = None


@dataclass(kw_only=True, slots=True)
class WebSocketClosedEvent(CDPEvent):
    """
    Fired when WebSocket is closed.
    """

    request_id: RequestId
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class WebSocketCreatedEvent(CDPEvent):
    """
    Fired upon WebSocket creation.
    """

    request_id: RequestId
    url: str
    initiator: Initiator | None = None


@dataclass(kw_only=True, slots=True)
class WebSocketFrameErrorEvent(CDPEvent):
    """
    Fired when WebSocket message error occurs.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    error_message: str


@dataclass(kw_only=True, slots=True)
class WebSocketFrameReceivedEvent(CDPEvent):
    """
    Fired when WebSocket message is received.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    response: WebSocketFrame


@dataclass(kw_only=True, slots=True)
class WebSocketFrameSentEvent(CDPEvent):
    """
    Fired when WebSocket message is sent.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    response: WebSocketFrame


@dataclass(kw_only=True, slots=True)
class WebSocketHandshakeResponseReceivedEvent(CDPEvent):
    """
    Fired when WebSocket handshake response becomes available.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    response: WebSocketResponse


@dataclass(kw_only=True, slots=True)
class WebSocketWillSendHandshakeRequestEvent(CDPEvent):
    """
    Fired when WebSocket is about to initiate handshake.
    """

    request_id: RequestId
    timestamp: MonotonicTime
    wall_time: TimeSinceEpoch
    request: WebSocketRequest


@dataclass(kw_only=True, slots=True)
class WebTransportCreatedEvent(CDPEvent):
    """
    Fired upon WebTransport creation.
    """

    transport_id: RequestId
    url: str
    timestamp: MonotonicTime
    initiator: Initiator | None = None


@dataclass(kw_only=True, slots=True)
class WebTransportConnectionEstablishedEvent(CDPEvent):
    """
    Fired when WebTransport handshake is finished.
    """

    transport_id: RequestId
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class WebTransportClosedEvent(CDPEvent):
    """
    Fired when WebTransport is disposed.
    """

    transport_id: RequestId
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketCreatedEvent(CDPEvent):
    """
    Fired upon direct_socket.TCPSocket creation.
    """

    identifier: RequestId
    remote_addr: str
    remote_port: int
    options: DirectTCPSocketOptions
    timestamp: MonotonicTime
    initiator: Initiator | None = None


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketOpenedEvent(CDPEvent):
    """
    Fired when direct_socket.TCPSocket connection is opened.
    """

    identifier: RequestId
    remote_addr: str
    remote_port: int
    timestamp: MonotonicTime
    local_addr: str | None = None
    local_port: int | None = None


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketAbortedEvent(CDPEvent):
    """
    Fired when direct_socket.TCPSocket is aborted.
    """

    identifier: RequestId
    error_message: str
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketClosedEvent(CDPEvent):
    """
    Fired when direct_socket.TCPSocket is closed.
    """

    identifier: RequestId
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketChunkSentEvent(CDPEvent):
    """
    Fired when data is sent to tcp direct socket stream.
    """

    identifier: RequestId
    data: str
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketChunkReceivedEvent(CDPEvent):
    """
    Fired when data is received from tcp direct socket stream.
    """

    identifier: RequestId
    data: str
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketJoinedMulticastGroupEvent(CDPEvent):
    identifier: RequestId
    ip_address: str


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketLeftMulticastGroupEvent(CDPEvent):
    identifier: RequestId
    ip_address: str


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketCreatedEvent(CDPEvent):
    """
    Fired upon direct_socket.UDPSocket creation.
    """

    identifier: RequestId
    options: DirectUDPSocketOptions
    timestamp: MonotonicTime
    initiator: Initiator | None = None


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketOpenedEvent(CDPEvent):
    """
    Fired when direct_socket.UDPSocket connection is opened.
    """

    identifier: RequestId
    local_addr: str
    local_port: int
    timestamp: MonotonicTime
    remote_addr: str | None = None
    remote_port: int | None = None


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketAbortedEvent(CDPEvent):
    """
    Fired when direct_socket.UDPSocket is aborted.
    """

    identifier: RequestId
    error_message: str
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketClosedEvent(CDPEvent):
    """
    Fired when direct_socket.UDPSocket is closed.
    """

    identifier: RequestId
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketChunkSentEvent(CDPEvent):
    """
    Fired when message is sent to udp direct socket stream.
    """

    identifier: RequestId
    message: DirectUDPMessage
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketChunkReceivedEvent(CDPEvent):
    """
    Fired when message is received from udp direct socket stream.
    """

    identifier: RequestId
    message: DirectUDPMessage
    timestamp: MonotonicTime


@dataclass(kw_only=True, slots=True)
class RequestWillBeSentExtraInfoEvent(CDPEvent):
    """
    Fired when additional information about a requestWillBeSent event is available from
    the network stack. Not every requestWillBeSent event will have an additional
    requestWillBeSentExtraInfo fired for it, and there is no guarantee whether
    requestWillBeSent or requestWillBeSentExtraInfo will be fired first for the same
    request.
    """

    request_id: RequestId
    associated_cookies: list[AssociatedCookie]
    headers: Headers
    connect_timing: ConnectTiming
    device_bound_session_usages: list[DeviceBoundSessionWithUsage] | None = None
    client_security_state: ClientSecurityState | None = None
    site_has_cookie_in_other_partition: bool | None = None
    applied_network_conditions_id: str | None = None


@dataclass(kw_only=True, slots=True)
class ResponseReceivedExtraInfoEvent(CDPEvent):
    """
    Fired when additional information about a responseReceived event is available from
    the network stack. Not every responseReceived event will have an additional
    responseReceivedExtraInfo for it, and responseReceivedExtraInfo may be fired before
    or after responseReceived.
    """

    request_id: RequestId
    blocked_cookies: list[BlockedSetCookieWithReason]
    headers: Headers
    resource_ip_address_space: IPAddressSpace
    status_code: int
    headers_text: str | None = None
    cookie_partition_key: CookiePartitionKey | None = None
    cookie_partition_key_opaque: bool | None = None
    exempted_cookies: list[ExemptedSetCookieWithReason] | None = None


@dataclass(kw_only=True, slots=True)
class ResponseReceivedEarlyHintsEvent(CDPEvent):
    """
    Fired when 103 Early Hints headers is received in addition to the common response.
    Not every responseReceived event will have an responseReceivedEarlyHints fired. Only
    one responseReceivedEarlyHints may be fired for eached responseReceived event.
    """

    request_id: RequestId
    headers: Headers


@dataclass(kw_only=True, slots=True)
class TrustTokenOperationDoneEvent(CDPEvent):
    """
    Fired exactly once for each Trust Token operation. Depending on the type of the
    operation and whether the operation succeeded or failed, the event is fired before
    the corresponding request was sent or after the response was received.
    """

    status: Literal[
        "Ok",
        "InvalidArgument",
        "MissingIssuerKeys",
        "FailedPrecondition",
        "ResourceExhausted",
        "AlreadyExists",
        "ResourceLimited",
        "Unauthorized",
        "BadResponse",
        "InternalError",
        "UnknownError",
        "FulfilledLocally",
        "SiteIssuerLimit",
    ]
    type: TrustTokenOperationType
    request_id: RequestId
    top_level_origin: str | None = None
    issuer_origin: str | None = None
    issued_token_count: int | None = None


@dataclass(kw_only=True, slots=True)
class PolicyUpdatedEvent(CDPEvent):
    """
    Fired once security policy has been updated.
    """

    pass


@dataclass(kw_only=True, slots=True)
class ReportingApiReportAddedEvent(CDPEvent):
    """
    Is sent whenever a new report is added. And after 'enableReportingApi' for all
    existing reports.
    """

    report: ReportingApiReport


@dataclass(kw_only=True, slots=True)
class ReportingApiReportUpdatedEvent(CDPEvent):
    report: ReportingApiReport


@dataclass(kw_only=True, slots=True)
class ReportingApiEndpointsChangedForOriginEvent(CDPEvent):
    origin: str
    endpoints: list[ReportingApiEndpoint]


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionsAddedEvent(CDPEvent):
    """
    Triggered when the initial set of device bound sessions is added.
    """

    sessions: list[DeviceBoundSession]


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionEventOccurredEvent(CDPEvent):
    """
    Triggered when a device bound session event occurs.
    """

    event_id: DeviceBoundSessionEventId
    site: str
    succeeded: bool
    session_id: str | None = None
    creation_event_details: CreationEventDetails | None = None
    refresh_event_details: RefreshEventDetails | None = None
    termination_event_details: TerminationEventDetails | None = None
    challenge_event_details: ChallengeEventDetails | None = None
