# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from cdpify.domains import io, network, runtime, security

"""
Resource type as it was perceived by the rendering engine.
"""
type ResourceType = Literal[
    "Document",
    "Stylesheet",
    "Image",
    "Media",
    "Font",
    "Script",
    "TextTrack",
    "XHR",
    "Fetch",
    "Prefetch",
    "EventSource",
    "WebSocket",
    "Manifest",
    "SignedExchange",
    "Ping",
    "CSPViolationReport",
    "Preflight",
    "FedCM",
    "Other",
]

"""
Unique loader identifier.
"""
LoaderId = str

"""
Unique network request identifier. Note that this does not identify individual HTTP
requests that are part of a network request.
"""
RequestId = str

"""
Network level fetch failure reason.
"""
type ErrorReason = Literal[
    "Failed",
    "Aborted",
    "TimedOut",
    "AccessDenied",
    "ConnectionClosed",
    "ConnectionReset",
    "ConnectionRefused",
    "ConnectionAborted",
    "ConnectionFailed",
    "NameNotResolved",
    "InternetDisconnected",
    "AddressUnreachable",
    "BlockedByClient",
    "BlockedByResponse",
]

"""
UTC time in seconds, counted from January 1, 1970.
"""
TimeSinceEpoch = float

"""
Monotonically increasing time in seconds since an arbitrary point in the past.
"""
MonotonicTime = float

"""
Request / response headers as keys / values of JSON object.
"""
Headers = dict[str, Any]

"""
The underlying connection technology that the browser is supposedly using.
"""
type ConnectionType = Literal[
    "none",
    "cellular2g",
    "cellular3g",
    "cellular4g",
    "bluetooth",
    "ethernet",
    "wifi",
    "wimax",
    "other",
]

"""
Represents the cookie's 'SameSite' status:
https://tools.ietf.org/html/draft-west-first-party-cookies
"""
type CookieSameSite = Literal["Strict", "Lax", "None"]

"""
Represents the cookie's 'Priority' status:
https://tools.ietf.org/html/draft-west-cookie-priority-00
"""
type CookiePriority = Literal["Low", "Medium", "High"]

"""
Represents the source scheme of the origin that originally set the cookie. A value of
"Unset" allows protocol clients to emulate legacy cookie scope for the scheme. This is a
temporary ability and it will be removed in the future.
"""
type CookieSourceScheme = Literal["Unset", "NonSecure", "Secure"]


@dataclass(kw_only=True, slots=True)
class ResourceTiming:
    """
    Timing information for the request.
    """

    request_time: float = field(metadata={"cdp_name": "requestTime"})
    proxy_start: float = field(metadata={"cdp_name": "proxyStart"})
    proxy_end: float = field(metadata={"cdp_name": "proxyEnd"})
    dns_start: float = field(metadata={"cdp_name": "dnsStart"})
    dns_end: float = field(metadata={"cdp_name": "dnsEnd"})
    connect_start: float = field(metadata={"cdp_name": "connectStart"})
    connect_end: float = field(metadata={"cdp_name": "connectEnd"})
    ssl_start: float = field(metadata={"cdp_name": "sslStart"})
    ssl_end: float = field(metadata={"cdp_name": "sslEnd"})
    worker_start: float = field(metadata={"cdp_name": "workerStart"})
    worker_ready: float = field(metadata={"cdp_name": "workerReady"})
    worker_fetch_start: float = field(metadata={"cdp_name": "workerFetchStart"})
    worker_respond_with_settled: float = field(
        metadata={"cdp_name": "workerRespondWithSettled"}
    )
    worker_router_evaluation_start: float | None = field(
        default=None, metadata={"cdp_name": "workerRouterEvaluationStart"}
    )
    worker_cache_lookup_start: float | None = field(
        default=None, metadata={"cdp_name": "workerCacheLookupStart"}
    )
    send_start: float = field(metadata={"cdp_name": "sendStart"})
    send_end: float = field(metadata={"cdp_name": "sendEnd"})
    push_start: float = field(metadata={"cdp_name": "pushStart"})
    push_end: float = field(metadata={"cdp_name": "pushEnd"})
    receive_headers_start: float = field(metadata={"cdp_name": "receiveHeadersStart"})
    receive_headers_end: float = field(metadata={"cdp_name": "receiveHeadersEnd"})


"""
Loading priority of a resource request.
"""
type ResourcePriority = Literal["VeryLow", "Low", "Medium", "High", "VeryHigh"]

"""
The render-blocking behavior of a resource request.
"""
type RenderBlockingBehavior = Literal[
    "Blocking",
    "InBodyParserBlocking",
    "NonBlocking",
    "NonBlockingDynamic",
    "PotentiallyBlocking",
]


@dataclass(kw_only=True, slots=True)
class PostDataEntry:
    """
    Post data entry for HTTP request
    """

    bytes: str | None = field(default=None, metadata={"cdp_name": "bytes"})


@dataclass(kw_only=True, slots=True)
class Request:
    """
    HTTP request data.
    """

    url: str = field(metadata={"cdp_name": "url"})
    url_fragment: str | None = field(default=None, metadata={"cdp_name": "urlFragment"})
    method: str = field(metadata={"cdp_name": "method"})
    headers: Headers = field(metadata={"cdp_name": "headers"})
    post_data: str | None = field(default=None, metadata={"cdp_name": "postData"})
    has_post_data: bool | None = field(
        default=None, metadata={"cdp_name": "hasPostData"}
    )
    post_data_entries: list[PostDataEntry] | None = field(
        default=None, metadata={"cdp_name": "postDataEntries"}
    )
    mixed_content_type: security.MixedContentType | None = field(
        default=None, metadata={"cdp_name": "mixedContentType"}
    )
    initial_priority: ResourcePriority = field(metadata={"cdp_name": "initialPriority"})
    referrer_policy: Literal[
        "unsafe-url",
        "no-referrer-when-downgrade",
        "no-referrer",
        "origin",
        "origin-when-cross-origin",
        "same-origin",
        "strict-origin",
        "strict-origin-when-cross-origin",
    ] = field(  # noqa: E501
        metadata={"cdp_name": "referrerPolicy"},
    )
    is_link_preload: bool | None = field(
        default=None, metadata={"cdp_name": "isLinkPreload"}
    )
    trust_token_params: TrustTokenParams | None = field(
        default=None, metadata={"cdp_name": "trustTokenParams"}
    )
    is_same_site: bool | None = field(default=None, metadata={"cdp_name": "isSameSite"})
    is_ad_related: bool | None = field(
        default=None, metadata={"cdp_name": "isAdRelated"}
    )


@dataclass(kw_only=True, slots=True)
class SignedCertificateTimestamp:
    """
    Details of a signed certificate timestamp (SCT).
    """

    status: str = field(metadata={"cdp_name": "status"})
    origin: str = field(metadata={"cdp_name": "origin"})
    log_description: str = field(metadata={"cdp_name": "logDescription"})
    log_id: str = field(metadata={"cdp_name": "logId"})
    timestamp: float = field(metadata={"cdp_name": "timestamp"})
    hash_algorithm: str = field(metadata={"cdp_name": "hashAlgorithm"})
    signature_algorithm: str = field(metadata={"cdp_name": "signatureAlgorithm"})
    signature_data: str = field(metadata={"cdp_name": "signatureData"})


@dataclass(kw_only=True, slots=True)
class SecurityDetails:
    """
    Security details about a request.
    """

    protocol: str = field(metadata={"cdp_name": "protocol"})
    key_exchange: str = field(metadata={"cdp_name": "keyExchange"})
    key_exchange_group: str | None = field(
        default=None, metadata={"cdp_name": "keyExchangeGroup"}
    )
    cipher: str = field(metadata={"cdp_name": "cipher"})
    mac: str | None = field(default=None, metadata={"cdp_name": "mac"})
    certificate_id: security.CertificateId = field(
        metadata={"cdp_name": "certificateId"}
    )
    subject_name: str = field(metadata={"cdp_name": "subjectName"})
    san_list: list[str] = field(metadata={"cdp_name": "sanList"})
    issuer: str = field(metadata={"cdp_name": "issuer"})
    valid_from: TimeSinceEpoch = field(metadata={"cdp_name": "validFrom"})
    valid_to: TimeSinceEpoch = field(metadata={"cdp_name": "validTo"})
    signed_certificate_timestamp_list: list[SignedCertificateTimestamp] = field(
        metadata={"cdp_name": "signedCertificateTimestampList"}
    )
    certificate_transparency_compliance: CertificateTransparencyCompliance = field(
        metadata={"cdp_name": "certificateTransparencyCompliance"}
    )
    server_signature_algorithm: int | None = field(
        default=None, metadata={"cdp_name": "serverSignatureAlgorithm"}
    )
    encrypted_client_hello: bool = field(metadata={"cdp_name": "encryptedClientHello"})


"""
Whether the request complied with Certificate Transparency policy.
"""
type CertificateTransparencyCompliance = Literal[
    "unknown", "not-compliant", "compliant"
]

"""
The reason why request was blocked.
"""
type BlockedReason = Literal[
    "other",
    "csp",
    "mixed-content",
    "origin",
    "inspector",
    "integrity",
    "subresource-filter",
    "content-type",
    "coep-frame-resource-needs-coep-header",
    "coop-sandboxed-iframe-cannot-navigate-to-coop-page",
    "corp-not-same-origin",
    "corp-not-same-origin-after-defaulted-to-same-origin-by-coep",
    "corp-not-same-origin-after-defaulted-to-same-origin-by-dip",
    "corp-not-same-origin-after-defaulted-to-same-origin-by-coep-and-dip",
    "corp-not-same-site",
    "sri-message-signature-mismatch",
]

"""
The reason why request was blocked.
"""
type CorsError = Literal[
    "DisallowedByMode",
    "InvalidResponse",
    "WildcardOriginNotAllowed",
    "MissingAllowOriginHeader",
    "MultipleAllowOriginValues",
    "InvalidAllowOriginValue",
    "AllowOriginMismatch",
    "InvalidAllowCredentials",
    "CorsDisabledScheme",
    "PreflightInvalidStatus",
    "PreflightDisallowedRedirect",
    "PreflightWildcardOriginNotAllowed",
    "PreflightMissingAllowOriginHeader",
    "PreflightMultipleAllowOriginValues",
    "PreflightInvalidAllowOriginValue",
    "PreflightAllowOriginMismatch",
    "PreflightInvalidAllowCredentials",
    "PreflightMissingAllowExternal",
    "PreflightInvalidAllowExternal",
    "InvalidAllowMethodsPreflightResponse",
    "InvalidAllowHeadersPreflightResponse",
    "MethodDisallowedByPreflightResponse",
    "HeaderDisallowedByPreflightResponse",
    "RedirectContainsCredentials",
    "InsecureLocalNetwork",
    "InvalidLocalNetworkAccess",
    "NoCorsRedirectModeNotFollow",
    "LocalNetworkAccessPermissionDenied",
]


@dataclass(kw_only=True, slots=True)
class CorsErrorStatus:
    cors_error: CorsError = field(metadata={"cdp_name": "corsError"})
    failed_parameter: str = field(metadata={"cdp_name": "failedParameter"})


"""
Source of serviceworker response.
"""
type ServiceWorkerResponseSource = Literal[
    "cache-storage", "http-cache", "fallback-code", "network"
]


@dataclass(kw_only=True, slots=True)
class TrustTokenParams:
    """
    Determines what type of Trust Token operation is executed and depending on the
    type, some additional parameters. The values are specified in
    third_party/blink/renderer/core/fetch/trust_token.idl.
    """

    operation: TrustTokenOperationType = field(metadata={"cdp_name": "operation"})
    refresh_policy: Literal["UseCached", "Refresh"] = field(
        metadata={"cdp_name": "refreshPolicy"}
    )
    issuers: list[str] | None = field(default=None, metadata={"cdp_name": "issuers"})


type TrustTokenOperationType = Literal["Issuance", "Redemption", "Signing"]

"""
The reason why Chrome uses a specific transport protocol for HTTP semantics.
"""
type AlternateProtocolUsage = Literal[
    "alternativeJobWonWithoutRace",
    "alternativeJobWonRace",
    "mainJobWonRace",
    "mappingMissing",
    "broken",
    "dnsAlpnH3JobWonWithoutRace",
    "dnsAlpnH3JobWonRace",
    "unspecifiedReason",
]

"""
Source of service worker router.
"""
type ServiceWorkerRouterSource = Literal[
    "network",
    "cache",
    "fetch-event",
    "race-network-and-fetch-handler",
    "race-network-and-cache",
]


@dataclass(kw_only=True, slots=True)
class ServiceWorkerRouterInfo:
    rule_id_matched: int | None = field(
        default=None, metadata={"cdp_name": "ruleIdMatched"}
    )
    matched_source_type: ServiceWorkerRouterSource | None = field(
        default=None, metadata={"cdp_name": "matchedSourceType"}
    )
    actual_source_type: ServiceWorkerRouterSource | None = field(
        default=None, metadata={"cdp_name": "actualSourceType"}
    )


@dataclass(kw_only=True, slots=True)
class Response:
    """
    HTTP response data.
    """

    url: str = field(metadata={"cdp_name": "url"})
    status: int = field(metadata={"cdp_name": "status"})
    status_text: str = field(metadata={"cdp_name": "statusText"})
    headers: Headers = field(metadata={"cdp_name": "headers"})
    headers_text: str | None = field(default=None, metadata={"cdp_name": "headersText"})
    mime_type: str = field(metadata={"cdp_name": "mimeType"})
    charset: str = field(metadata={"cdp_name": "charset"})
    request_headers: Headers | None = field(
        default=None, metadata={"cdp_name": "requestHeaders"}
    )
    request_headers_text: str | None = field(
        default=None, metadata={"cdp_name": "requestHeadersText"}
    )
    connection_reused: bool = field(metadata={"cdp_name": "connectionReused"})
    connection_id: float = field(metadata={"cdp_name": "connectionId"})
    remote_ip_address: str | None = field(
        default=None, metadata={"cdp_name": "remoteIPAddress"}
    )
    remote_port: int | None = field(default=None, metadata={"cdp_name": "remotePort"})
    from_disk_cache: bool | None = field(
        default=None, metadata={"cdp_name": "fromDiskCache"}
    )
    from_service_worker: bool | None = field(
        default=None, metadata={"cdp_name": "fromServiceWorker"}
    )
    from_prefetch_cache: bool | None = field(
        default=None, metadata={"cdp_name": "fromPrefetchCache"}
    )
    from_early_hints: bool | None = field(
        default=None, metadata={"cdp_name": "fromEarlyHints"}
    )
    service_worker_router_info: ServiceWorkerRouterInfo | None = field(
        default=None, metadata={"cdp_name": "serviceWorkerRouterInfo"}
    )
    encoded_data_length: float = field(metadata={"cdp_name": "encodedDataLength"})
    timing: ResourceTiming | None = field(default=None, metadata={"cdp_name": "timing"})
    service_worker_response_source: ServiceWorkerResponseSource | None = field(
        default=None, metadata={"cdp_name": "serviceWorkerResponseSource"}
    )
    response_time: TimeSinceEpoch | None = field(
        default=None, metadata={"cdp_name": "responseTime"}
    )
    cache_storage_cache_name: str | None = field(
        default=None, metadata={"cdp_name": "cacheStorageCacheName"}
    )
    protocol: str | None = field(default=None, metadata={"cdp_name": "protocol"})
    alternate_protocol_usage: AlternateProtocolUsage | None = field(
        default=None, metadata={"cdp_name": "alternateProtocolUsage"}
    )
    security_state: security.SecurityState = field(
        metadata={"cdp_name": "securityState"}
    )
    security_details: SecurityDetails | None = field(
        default=None, metadata={"cdp_name": "securityDetails"}
    )


@dataclass(kw_only=True, slots=True)
class WebSocketRequest:
    """
    WebSocket request data.
    """

    headers: Headers = field(metadata={"cdp_name": "headers"})


@dataclass(kw_only=True, slots=True)
class WebSocketResponse:
    """
    WebSocket response data.
    """

    status: int = field(metadata={"cdp_name": "status"})
    status_text: str = field(metadata={"cdp_name": "statusText"})
    headers: Headers = field(metadata={"cdp_name": "headers"})
    headers_text: str | None = field(default=None, metadata={"cdp_name": "headersText"})
    request_headers: Headers | None = field(
        default=None, metadata={"cdp_name": "requestHeaders"}
    )
    request_headers_text: str | None = field(
        default=None, metadata={"cdp_name": "requestHeadersText"}
    )


@dataclass(kw_only=True, slots=True)
class WebSocketFrame:
    """
    WebSocket message data. This represents an entire WebSocket message, not just a
    fragmented frame as the name suggests.
    """

    opcode: float = field(metadata={"cdp_name": "opcode"})
    mask: bool = field(metadata={"cdp_name": "mask"})
    payload_data: str = field(metadata={"cdp_name": "payloadData"})


@dataclass(kw_only=True, slots=True)
class CachedResource:
    """
    Information about the cached resource.
    """

    url: str = field(metadata={"cdp_name": "url"})
    type: ResourceType = field(metadata={"cdp_name": "type"})
    response: Response | None = field(default=None, metadata={"cdp_name": "response"})
    body_size: float = field(metadata={"cdp_name": "bodySize"})


@dataclass(kw_only=True, slots=True)
class Initiator:
    """
    Information about the request initiator.
    """

    type: Literal[
        "parser", "script", "preload", "SignedExchange", "preflight", "FedCM", "other"
    ] = field(  # noqa: E501
        metadata={"cdp_name": "type"},
    )
    stack: runtime.StackTrace | None = field(
        default=None, metadata={"cdp_name": "stack"}
    )
    url: str | None = field(default=None, metadata={"cdp_name": "url"})
    line_number: float | None = field(default=None, metadata={"cdp_name": "lineNumber"})
    column_number: float | None = field(
        default=None, metadata={"cdp_name": "columnNumber"}
    )
    request_id: RequestId | None = field(
        default=None, metadata={"cdp_name": "requestId"}
    )


@dataclass(kw_only=True, slots=True)
class CookiePartitionKey:
    """
    cookiePartitionKey object The representation of the components of the key that are
    created by the cookiePartitionKey class contained in
    net/cookies/cookie_partition_key.h.
    """

    top_level_site: str = field(metadata={"cdp_name": "topLevelSite"})
    has_cross_site_ancestor: bool = field(metadata={"cdp_name": "hasCrossSiteAncestor"})


@dataclass(kw_only=True, slots=True)
class Cookie:
    """
    Cookie object
    """

    name: str = field(metadata={"cdp_name": "name"})
    value: str = field(metadata={"cdp_name": "value"})
    domain: str = field(metadata={"cdp_name": "domain"})
    path: str = field(metadata={"cdp_name": "path"})
    expires: float = field(metadata={"cdp_name": "expires"})
    size: int = field(metadata={"cdp_name": "size"})
    http_only: bool = field(metadata={"cdp_name": "httpOnly"})
    secure: bool = field(metadata={"cdp_name": "secure"})
    session: bool = field(metadata={"cdp_name": "session"})
    same_site: CookieSameSite | None = field(
        default=None, metadata={"cdp_name": "sameSite"}
    )
    priority: CookiePriority = field(metadata={"cdp_name": "priority"})
    source_scheme: CookieSourceScheme = field(metadata={"cdp_name": "sourceScheme"})
    source_port: int = field(metadata={"cdp_name": "sourcePort"})
    partition_key: CookiePartitionKey | None = field(
        default=None, metadata={"cdp_name": "partitionKey"}
    )
    partition_key_opaque: bool | None = field(
        default=None, metadata={"cdp_name": "partitionKeyOpaque"}
    )


"""
Types of reasons why a cookie may not be stored from a response.
"""
type SetCookieBlockedReason = Literal[
    "SecureOnly",
    "SameSiteStrict",
    "SameSiteLax",
    "SameSiteUnspecifiedTreatedAsLax",
    "SameSiteNoneInsecure",
    "UserPreferences",
    "ThirdPartyPhaseout",
    "ThirdPartyBlockedInFirstPartySet",
    "SyntaxError",
    "SchemeNotSupported",
    "OverwriteSecure",
    "InvalidDomain",
    "InvalidPrefix",
    "UnknownError",
    "SchemefulSameSiteStrict",
    "SchemefulSameSiteLax",
    "SchemefulSameSiteUnspecifiedTreatedAsLax",
    "NameValuePairExceedsMaxSize",
    "DisallowedCharacter",
    "NoCookieContent",
]

"""
Types of reasons why a cookie may not be sent with a request.
"""
type CookieBlockedReason = Literal[
    "SecureOnly",
    "NotOnPath",
    "DomainMismatch",
    "SameSiteStrict",
    "SameSiteLax",
    "SameSiteUnspecifiedTreatedAsLax",
    "SameSiteNoneInsecure",
    "UserPreferences",
    "ThirdPartyPhaseout",
    "ThirdPartyBlockedInFirstPartySet",
    "UnknownError",
    "SchemefulSameSiteStrict",
    "SchemefulSameSiteLax",
    "SchemefulSameSiteUnspecifiedTreatedAsLax",
    "NameValuePairExceedsMaxSize",
    "PortMismatch",
    "SchemeMismatch",
    "AnonymousContext",
]

"""
Types of reasons why a cookie should have been blocked by 3PCD but is exempted for the
request.
"""
type CookieExemptionReason = Literal[
    "None",
    "UserSetting",
    "EnterprisePolicy",
    "StorageAccess",
    "TopLevelStorageAccess",
    "Scheme",
    "SameSiteNoneCookiesInSandbox",
]


@dataclass(kw_only=True, slots=True)
class BlockedSetCookieWithReason:
    """
    A cookie which was not stored from a response with the corresponding reason.
    """

    blocked_reasons: list[SetCookieBlockedReason] = field(
        metadata={"cdp_name": "blockedReasons"}
    )
    cookie_line: str = field(metadata={"cdp_name": "cookieLine"})
    cookie: Cookie | None = field(default=None, metadata={"cdp_name": "cookie"})


@dataclass(kw_only=True, slots=True)
class ExemptedSetCookieWithReason:
    """
    A cookie should have been blocked by 3PCD but is exempted and stored from a
    response with the corresponding reason. A cookie could only have at most one
    exemption reason.
    """

    exemption_reason: CookieExemptionReason = field(
        metadata={"cdp_name": "exemptionReason"}
    )
    cookie_line: str = field(metadata={"cdp_name": "cookieLine"})
    cookie: Cookie = field(metadata={"cdp_name": "cookie"})


@dataclass(kw_only=True, slots=True)
class AssociatedCookie:
    """
    A cookie associated with the request which may or may not be sent with it. Includes
    the cookies itself and reasons for blocking or exemption.
    """

    cookie: Cookie = field(metadata={"cdp_name": "cookie"})
    blocked_reasons: list[CookieBlockedReason] = field(
        metadata={"cdp_name": "blockedReasons"}
    )
    exemption_reason: CookieExemptionReason | None = field(
        default=None, metadata={"cdp_name": "exemptionReason"}
    )


@dataclass(kw_only=True, slots=True)
class CookieParam:
    """
    Cookie parameter object
    """

    name: str = field(metadata={"cdp_name": "name"})
    value: str = field(metadata={"cdp_name": "value"})
    url: str | None = field(default=None, metadata={"cdp_name": "url"})
    domain: str | None = field(default=None, metadata={"cdp_name": "domain"})
    path: str | None = field(default=None, metadata={"cdp_name": "path"})
    secure: bool | None = field(default=None, metadata={"cdp_name": "secure"})
    http_only: bool | None = field(default=None, metadata={"cdp_name": "httpOnly"})
    same_site: CookieSameSite | None = field(
        default=None, metadata={"cdp_name": "sameSite"}
    )
    expires: TimeSinceEpoch | None = field(
        default=None, metadata={"cdp_name": "expires"}
    )
    priority: CookiePriority | None = field(
        default=None, metadata={"cdp_name": "priority"}
    )
    source_scheme: CookieSourceScheme | None = field(
        default=None, metadata={"cdp_name": "sourceScheme"}
    )
    source_port: int | None = field(default=None, metadata={"cdp_name": "sourcePort"})
    partition_key: CookiePartitionKey | None = field(
        default=None, metadata={"cdp_name": "partitionKey"}
    )


@dataclass(kw_only=True, slots=True)
class AuthChallenge:
    """
    Authorization challenge for HTTP status code 401 or 407.
    """

    source: Literal["Server", "Proxy"] | None = field(
        default=None, metadata={"cdp_name": "source"}
    )
    origin: str = field(metadata={"cdp_name": "origin"})
    scheme: str = field(metadata={"cdp_name": "scheme"})
    realm: str = field(metadata={"cdp_name": "realm"})


@dataclass(kw_only=True, slots=True)
class AuthChallengeResponse:
    """
    Response to an AuthChallenge.
    """

    response: Literal["Default", "CancelAuth", "ProvideCredentials"] = field(
        metadata={"cdp_name": "response"}
    )
    username: str | None = field(default=None, metadata={"cdp_name": "username"})
    password: str | None = field(default=None, metadata={"cdp_name": "password"})


@dataclass(kw_only=True, slots=True)
class SignedExchangeSignature:
    """
    Information about a signed exchange signature.
    https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#rfc.section.3.1
    """

    label: str = field(metadata={"cdp_name": "label"})
    signature: str = field(metadata={"cdp_name": "signature"})
    integrity: str = field(metadata={"cdp_name": "integrity"})
    cert_url: str | None = field(default=None, metadata={"cdp_name": "certUrl"})
    cert_sha256: str | None = field(default=None, metadata={"cdp_name": "certSha256"})
    validity_url: str = field(metadata={"cdp_name": "validityUrl"})
    date: int = field(metadata={"cdp_name": "date"})
    expires: int = field(metadata={"cdp_name": "expires"})
    certificates: list[str] | None = field(
        default=None, metadata={"cdp_name": "certificates"}
    )


@dataclass(kw_only=True, slots=True)
class SignedExchangeHeader:
    """
    Information about a signed exchange header.
    https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#cbor-representation
    """

    request_url: str = field(metadata={"cdp_name": "requestUrl"})
    response_code: int = field(metadata={"cdp_name": "responseCode"})
    response_headers: Headers = field(metadata={"cdp_name": "responseHeaders"})
    signatures: list[SignedExchangeSignature] = field(
        metadata={"cdp_name": "signatures"}
    )
    header_integrity: str = field(metadata={"cdp_name": "headerIntegrity"})


"""
Field type for a signed exchange related error.
"""
type SignedExchangeErrorField = Literal[
    "signatureSig",
    "signatureIntegrity",
    "signatureCertUrl",
    "signatureCertSha256",
    "signatureValidityUrl",
    "signatureTimestamps",
]


@dataclass(kw_only=True, slots=True)
class SignedExchangeError:
    """
    Information about a signed exchange response.
    """

    message: str = field(metadata={"cdp_name": "message"})
    signature_index: int | None = field(
        default=None, metadata={"cdp_name": "signatureIndex"}
    )
    error_field: SignedExchangeErrorField | None = field(
        default=None, metadata={"cdp_name": "errorField"}
    )


@dataclass(kw_only=True, slots=True)
class SignedExchangeInfo:
    """
    Information about a signed exchange response.
    """

    outer_response: Response = field(metadata={"cdp_name": "outerResponse"})
    has_extra_info: bool = field(metadata={"cdp_name": "hasExtraInfo"})
    header: SignedExchangeHeader | None = field(
        default=None, metadata={"cdp_name": "header"}
    )
    security_details: SecurityDetails | None = field(
        default=None, metadata={"cdp_name": "securityDetails"}
    )
    errors: list[SignedExchangeError] | None = field(
        default=None, metadata={"cdp_name": "errors"}
    )


@dataclass(kw_only=True, slots=True)
class NetworkConditions:
    url_pattern: str = field(metadata={"cdp_name": "urlPattern"})
    latency: float = field(metadata={"cdp_name": "latency"})
    download_throughput: float = field(metadata={"cdp_name": "downloadThroughput"})
    upload_throughput: float = field(metadata={"cdp_name": "uploadThroughput"})
    connection_type: ConnectionType | None = field(
        default=None, metadata={"cdp_name": "connectionType"}
    )
    packet_loss: float | None = field(default=None, metadata={"cdp_name": "packetLoss"})
    packet_queue_length: int | None = field(
        default=None, metadata={"cdp_name": "packetQueueLength"}
    )
    packet_reordering: bool | None = field(
        default=None, metadata={"cdp_name": "packetReordering"}
    )
    offline: bool | None = field(default=None, metadata={"cdp_name": "offline"})


@dataclass(kw_only=True, slots=True)
class BlockPattern:
    url_pattern: str = field(metadata={"cdp_name": "urlPattern"})
    block: bool = field(metadata={"cdp_name": "block"})


type DirectSocketDnsQueryType = Literal["ipv4", "ipv6"]


@dataclass(kw_only=True, slots=True)
class DirectTCPSocketOptions:
    no_delay: bool = field(metadata={"cdp_name": "noDelay"})
    keep_alive_delay: float | None = field(
        default=None, metadata={"cdp_name": "keepAliveDelay"}
    )
    send_buffer_size: float | None = field(
        default=None, metadata={"cdp_name": "sendBufferSize"}
    )
    receive_buffer_size: float | None = field(
        default=None, metadata={"cdp_name": "receiveBufferSize"}
    )
    dns_query_type: DirectSocketDnsQueryType | None = field(
        default=None, metadata={"cdp_name": "dnsQueryType"}
    )


@dataclass(kw_only=True, slots=True)
class DirectUDPSocketOptions:
    remote_addr: str | None = field(default=None, metadata={"cdp_name": "remoteAddr"})
    remote_port: int | None = field(default=None, metadata={"cdp_name": "remotePort"})
    local_addr: str | None = field(default=None, metadata={"cdp_name": "localAddr"})
    local_port: int | None = field(default=None, metadata={"cdp_name": "localPort"})
    dns_query_type: DirectSocketDnsQueryType | None = field(
        default=None, metadata={"cdp_name": "dnsQueryType"}
    )
    send_buffer_size: float | None = field(
        default=None, metadata={"cdp_name": "sendBufferSize"}
    )
    receive_buffer_size: float | None = field(
        default=None, metadata={"cdp_name": "receiveBufferSize"}
    )
    multicast_loopback: bool | None = field(
        default=None, metadata={"cdp_name": "multicastLoopback"}
    )
    multicast_time_to_live: int | None = field(
        default=None, metadata={"cdp_name": "multicastTimeToLive"}
    )
    multicast_allow_address_sharing: bool | None = field(
        default=None, metadata={"cdp_name": "multicastAllowAddressSharing"}
    )


@dataclass(kw_only=True, slots=True)
class DirectUDPMessage:
    data: str = field(metadata={"cdp_name": "data"})
    remote_addr: str | None = field(default=None, metadata={"cdp_name": "remoteAddr"})
    remote_port: int | None = field(default=None, metadata={"cdp_name": "remotePort"})


type LocalNetworkAccessRequestPolicy = Literal[
    "Allow",
    "BlockFromInsecureToMorePrivate",
    "WarnFromInsecureToMorePrivate",
    "PermissionBlock",
    "PermissionWarn",
]

type IPAddressSpace = Literal["Loopback", "Local", "Public", "Unknown"]


@dataclass(kw_only=True, slots=True)
class ConnectTiming:
    request_time: float = field(metadata={"cdp_name": "requestTime"})


@dataclass(kw_only=True, slots=True)
class ClientSecurityState:
    initiator_is_secure_context: bool = field(
        metadata={"cdp_name": "initiatorIsSecureContext"}
    )
    initiator_ip_address_space: IPAddressSpace = field(
        metadata={"cdp_name": "initiatorIPAddressSpace"}
    )
    local_network_access_request_policy: LocalNetworkAccessRequestPolicy = field(
        metadata={"cdp_name": "localNetworkAccessRequestPolicy"}
    )


@dataclass(kw_only=True, slots=True)
class AdScriptIdentifier:
    """
    Identifies the script on the stack that caused a resource or element to be labeled
    as an ad. For resources, this indicates the context that triggered the fetch. For
    elements, this indicates the context that caused the element to be appended to the
    DOM.
    """

    script_id: runtime.ScriptId = field(metadata={"cdp_name": "scriptId"})
    debugger_id: runtime.UniqueDebuggerId = field(metadata={"cdp_name": "debuggerId"})
    name: str = field(metadata={"cdp_name": "name"})


@dataclass(kw_only=True, slots=True)
class AdAncestry:
    """
    Encapsulates the script ancestry and the root script filter list rule that caused
    the resource or element to be labeled as an ad.
    """

    ancestry_chain: list[AdScriptIdentifier] = field(
        metadata={"cdp_name": "ancestryChain"}
    )
    root_script_filterlist_rule: str | None = field(
        default=None, metadata={"cdp_name": "rootScriptFilterlistRule"}
    )


@dataclass(kw_only=True, slots=True)
class AdProvenance:
    """
    Represents the provenance of an ad resource or element. Only one of
    `filterlistRule` or `adScriptAncestry` can be set. If `filterlistRule` is provided,
    the resource URL directly matches a filter list rule. If `adScriptAncestry` is
    provided, an ad script initiated the resource fetch or appended the element to the
    DOM. If neither is provided, the entity is known to be an ad, but provenance
    tracking information is unavailable.
    """

    filterlist_rule: str | None = field(
        default=None, metadata={"cdp_name": "filterlistRule"}
    )
    ad_script_ancestry: AdAncestry | None = field(
        default=None, metadata={"cdp_name": "adScriptAncestry"}
    )


type CrossOriginOpenerPolicyValue = Literal[
    "SameOrigin",
    "SameOriginAllowPopups",
    "RestrictProperties",
    "UnsafeNone",
    "SameOriginPlusCoep",
    "RestrictPropertiesPlusCoep",
    "NoopenerAllowPopups",
]


@dataclass(kw_only=True, slots=True)
class CrossOriginOpenerPolicyStatus:
    value: CrossOriginOpenerPolicyValue = field(metadata={"cdp_name": "value"})
    report_only_value: CrossOriginOpenerPolicyValue = field(
        metadata={"cdp_name": "reportOnlyValue"}
    )
    reporting_endpoint: str | None = field(
        default=None, metadata={"cdp_name": "reportingEndpoint"}
    )
    report_only_reporting_endpoint: str | None = field(
        default=None, metadata={"cdp_name": "reportOnlyReportingEndpoint"}
    )


type CrossOriginEmbedderPolicyValue = Literal["None", "Credentialless", "RequireCorp"]


@dataclass(kw_only=True, slots=True)
class CrossOriginEmbedderPolicyStatus:
    value: CrossOriginEmbedderPolicyValue = field(metadata={"cdp_name": "value"})
    report_only_value: CrossOriginEmbedderPolicyValue = field(
        metadata={"cdp_name": "reportOnlyValue"}
    )
    reporting_endpoint: str | None = field(
        default=None, metadata={"cdp_name": "reportingEndpoint"}
    )
    report_only_reporting_endpoint: str | None = field(
        default=None, metadata={"cdp_name": "reportOnlyReportingEndpoint"}
    )


type ContentSecurityPolicySource = Literal["HTTP", "Meta"]


@dataclass(kw_only=True, slots=True)
class ContentSecurityPolicyStatus:
    effective_directives: str = field(metadata={"cdp_name": "effectiveDirectives"})
    is_enforced: bool = field(metadata={"cdp_name": "isEnforced"})
    source: ContentSecurityPolicySource = field(metadata={"cdp_name": "source"})


@dataclass(kw_only=True, slots=True)
class SecurityIsolationStatus:
    coop: CrossOriginOpenerPolicyStatus | None = field(
        default=None, metadata={"cdp_name": "coop"}
    )
    coep: CrossOriginEmbedderPolicyStatus | None = field(
        default=None, metadata={"cdp_name": "coep"}
    )
    csp: list[ContentSecurityPolicyStatus] | None = field(
        default=None, metadata={"cdp_name": "csp"}
    )


"""
The status of a Reporting API report.
"""
type ReportStatus = Literal["Queued", "Pending", "MarkedForRemoval", "Success"]

ReportId = str


@dataclass(kw_only=True, slots=True)
class ReportingApiReport:
    """
    An object representing a report generated by the Reporting API.
    """

    id: ReportId = field(metadata={"cdp_name": "id"})
    initiator_url: str = field(metadata={"cdp_name": "initiatorUrl"})
    destination: str = field(metadata={"cdp_name": "destination"})
    type: str = field(metadata={"cdp_name": "type"})
    timestamp: network.TimeSinceEpoch = field(metadata={"cdp_name": "timestamp"})
    depth: int = field(metadata={"cdp_name": "depth"})
    completed_attempts: int = field(metadata={"cdp_name": "completedAttempts"})
    body: dict[str, Any] = field(metadata={"cdp_name": "body"})
    status: ReportStatus = field(metadata={"cdp_name": "status"})


@dataclass(kw_only=True, slots=True)
class ReportingApiEndpoint:
    url: str = field(metadata={"cdp_name": "url"})
    group_name: str = field(metadata={"cdp_name": "groupName"})


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionKey:
    """
    Unique identifier for a device bound session.
    """

    site: str = field(metadata={"cdp_name": "site"})
    id: str = field(metadata={"cdp_name": "id"})


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionWithUsage:
    """
    How a device bound session was used during a request.
    """

    session_key: DeviceBoundSessionKey = field(metadata={"cdp_name": "sessionKey"})
    usage: Literal[
        "NotInScope",
        "InScopeRefreshNotYetNeeded",
        "InScopeRefreshNotAllowed",
        "ProactiveRefreshNotPossible",
        "ProactiveRefreshAttempted",
        "Deferred",
    ] = field(  # noqa: E501
        metadata={"cdp_name": "usage"},
    )


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionCookieCraving:
    """
    A device bound session's cookie craving.
    """

    name: str = field(metadata={"cdp_name": "name"})
    domain: str = field(metadata={"cdp_name": "domain"})
    path: str = field(metadata={"cdp_name": "path"})
    secure: bool = field(metadata={"cdp_name": "secure"})
    http_only: bool = field(metadata={"cdp_name": "httpOnly"})
    same_site: CookieSameSite | None = field(
        default=None, metadata={"cdp_name": "sameSite"}
    )


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionUrlRule:
    """
    A device bound session's inclusion URL rule.
    """

    rule_type: Literal["Exclude", "Include"] = field(metadata={"cdp_name": "ruleType"})
    host_pattern: str = field(metadata={"cdp_name": "hostPattern"})
    path_prefix: str = field(metadata={"cdp_name": "pathPrefix"})


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionInclusionRules:
    """
    A device bound session's inclusion rules.
    """

    origin: str = field(metadata={"cdp_name": "origin"})
    include_site: bool = field(metadata={"cdp_name": "includeSite"})
    url_rules: list[DeviceBoundSessionUrlRule] = field(
        metadata={"cdp_name": "urlRules"}
    )


@dataclass(kw_only=True, slots=True)
class DeviceBoundSession:
    """
    A device bound session.
    """

    key: DeviceBoundSessionKey = field(metadata={"cdp_name": "key"})
    refresh_url: str = field(metadata={"cdp_name": "refreshUrl"})
    inclusion_rules: DeviceBoundSessionInclusionRules = field(
        metadata={"cdp_name": "inclusionRules"}
    )
    cookie_cravings: list[DeviceBoundSessionCookieCraving] = field(
        metadata={"cdp_name": "cookieCravings"}
    )
    expiry_date: network.TimeSinceEpoch = field(metadata={"cdp_name": "expiryDate"})
    cached_challenge: str | None = field(
        default=None, metadata={"cdp_name": "cachedChallenge"}
    )
    allowed_refresh_initiators: list[str] = field(
        metadata={"cdp_name": "allowedRefreshInitiators"}
    )


"""
A unique identifier for a device bound session event.
"""
DeviceBoundSessionEventId = str

"""
A fetch result for a device bound session creation or refresh.
LINT.IfChange(DeviceBoundSessionFetchResult)
"""
type DeviceBoundSessionFetchResult = Literal[
    "Success",
    "SigningKeyGenerationError",
    "AttestationKeyGenerationError",
    "SigningError",
    "TransientSigningError",
    "ServerRequestedTermination",
    "InvalidSessionId",
    "InvalidChallenge",
    "TooManyChallenges",
    "InvalidFetcherUrl",
    "InvalidRefreshUrl",
    "TransientHttpError",
    "ScopeOriginSameSiteMismatch",
    "RefreshUrlSameSiteMismatch",
    "MismatchedSessionId",
    "MissingScope",
    "NoCredentials",
    "SubdomainRegistrationWellKnownUnavailable",
    "SubdomainRegistrationUnauthorized",
    "SubdomainRegistrationWellKnownMalformed",
    "SessionProviderWellKnownUnavailable",
    "RelyingPartyWellKnownUnavailable",
    "FederatedKeyThumbprintMismatch",
    "InvalidFederatedSessionUrl",
    "InvalidFederatedKey",
    "TooManyRelyingOriginLabels",
    "BoundCookieSetForbidden",
    "NetError",
    "ProxyError",
    "EmptySessionConfig",
    "InvalidCredentialsConfig",
    "InvalidCredentialsType",
    "InvalidCredentialsEmptyName",
    "InvalidCredentialsCookie",
    "PersistentHttpError",
    "RegistrationAttemptedChallenge",
    "InvalidScopeOrigin",
    "ScopeOriginContainsPath",
    "RefreshInitiatorNotString",
    "RefreshInitiatorInvalidHostPattern",
    "InvalidScopeSpecification",
    "MissingScopeSpecificationType",
    "EmptyScopeSpecificationDomain",
    "EmptyScopeSpecificationPath",
    "InvalidScopeSpecificationType",
    "InvalidScopeIncludeSite",
    "MissingScopeIncludeSite",
    "FederatedNotAuthorizedByProvider",
    "FederatedNotAuthorizedByRelyingParty",
    "SessionProviderWellKnownMalformed",
    "SessionProviderWellKnownHasProviderOrigin",
    "RelyingPartyWellKnownMalformed",
    "RelyingPartyWellKnownHasRelyingOrigins",
    "InvalidFederatedSessionProviderSessionMissing",
    "InvalidFederatedSessionWrongProviderOrigin",
    "InvalidCredentialsCookieCreationTime",
    "InvalidCredentialsCookieName",
    "InvalidCredentialsCookieParsing",
    "InvalidCredentialsCookieUnpermittedAttribute",
    "InvalidCredentialsCookieInvalidDomain",
    "InvalidCredentialsCookiePrefix",
    "InvalidScopeRulePath",
    "InvalidScopeRuleHostPattern",
    "ScopeRuleOriginScopedHostPatternMismatch",
    "ScopeRuleSiteScopedHostPatternMismatch",
    "SigningQuotaExceeded",
    "InvalidConfigJson",
    "InvalidFederatedSessionProviderFailedToRestoreKey",
    "FailedToUnwrapKey",
    "SessionDeletedDuringRefresh",
    "CrossOriginRegistrationSiteNotIncluded",
    "InvalidPreProvisionedKeyInitiatorMissing",
    "PreProvisionedKeyAccessNotGranted",
    "PreProvisionedKeyNotFound",
    "AttestationCertificationError",
    "AttestationSigningError",
]


@dataclass(kw_only=True, slots=True)
class DeviceBoundSessionFailedRequest:
    """
    Details about a failed device bound session network request.
    """

    request_url: str = field(metadata={"cdp_name": "requestUrl"})
    net_error: str | None = field(default=None, metadata={"cdp_name": "netError"})
    response_error: int | None = field(
        default=None, metadata={"cdp_name": "responseError"}
    )
    response_error_body: str | None = field(
        default=None, metadata={"cdp_name": "responseErrorBody"}
    )


@dataclass(kw_only=True, slots=True)
class CreationEventDetails:
    """
    Session event details specific to creation.
    """

    fetch_result: DeviceBoundSessionFetchResult = field(
        metadata={"cdp_name": "fetchResult"}
    )
    new_session: DeviceBoundSession | None = field(
        default=None, metadata={"cdp_name": "newSession"}
    )
    failed_request: DeviceBoundSessionFailedRequest | None = field(
        default=None, metadata={"cdp_name": "failedRequest"}
    )


@dataclass(kw_only=True, slots=True)
class RefreshEventDetails:
    """
    Session event details specific to refresh.
    """

    refresh_result: Literal[
        "Refreshed",
        "InitializedService",
        "Unreachable",
        "ServerError",
        "FatalError",
        "SigningQuotaExceeded",
        "RefreshedAsWaiter",
        "TransientSigningError",
        "InScopeRefreshNotYetNeeded",
    ] = field(  # noqa: E501
        metadata={"cdp_name": "refreshResult"},
    )
    fetch_result: DeviceBoundSessionFetchResult | None = field(
        default=None, metadata={"cdp_name": "fetchResult"}
    )
    new_session: DeviceBoundSession | None = field(
        default=None, metadata={"cdp_name": "newSession"}
    )
    was_fully_proactive_refresh: bool = field(
        metadata={"cdp_name": "wasFullyProactiveRefresh"}
    )
    failed_request: DeviceBoundSessionFailedRequest | None = field(
        default=None, metadata={"cdp_name": "failedRequest"}
    )


@dataclass(kw_only=True, slots=True)
class TerminationEventDetails:
    """
    Session event details specific to termination.
    """

    deletion_reason: Literal[
        "Expired",
        "FailedToRestoreKey",
        "FailedToUnwrapKey",
        "StoragePartitionCleared",
        "ClearBrowsingData",
        "ServerRequested",
        "InvalidSessionParams",
        "RefreshFatalError",
        "DevTools",
    ] = field(  # noqa: E501
        metadata={"cdp_name": "deletionReason"},
    )


@dataclass(kw_only=True, slots=True)
class ChallengeEventDetails:
    """
    Session event details specific to challenges.
    """

    challenge_result: Literal[
        "Success", "NoSessionId", "NoSessionMatch", "CantSetBoundCookie"
    ] = field(  # noqa: E501
        metadata={"cdp_name": "challengeResult"},
    )
    challenge: str = field(metadata={"cdp_name": "challenge"})


@dataclass(kw_only=True, slots=True)
class LoadNetworkResourcePageResult:
    """
    An object providing the result of a network resource load.
    """

    success: bool = field(metadata={"cdp_name": "success"})
    net_error: float | None = field(default=None, metadata={"cdp_name": "netError"})
    net_error_name: str | None = field(
        default=None, metadata={"cdp_name": "netErrorName"}
    )
    http_status_code: float | None = field(
        default=None, metadata={"cdp_name": "httpStatusCode"}
    )
    stream: io.StreamHandle | None = field(
        default=None, metadata={"cdp_name": "stream"}
    )
    headers: network.Headers | None = field(
        default=None, metadata={"cdp_name": "headers"}
    )


@dataclass(kw_only=True, slots=True)
class LoadNetworkResourceOptions:
    """
    An options object that may be extended later to better support CORS, CORB and
    streaming.
    """

    disable_cache: bool = field(metadata={"cdp_name": "disableCache"})
    include_credentials: bool = field(metadata={"cdp_name": "includeCredentials"})
