# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import TYPE_CHECKING, Literal

from pydantic_cpd.cdp.base import CDPModel

if TYPE_CHECKING:
    from pydantic_cpd.cdp import network

"""
Unique request identifier. Note that this does not identify individual HTTP requests
that are part of a network request.
"""
RequestId = str

"""
Stages of the request to handle. Request will intercept before the request is sent.
Response will intercept after the response is received (but before response body is
received).
"""
RequestStage = Literal["Request", "Response"]


class RequestPattern(CDPModel):
    url_pattern: str | None = None
    resource_type: network.ResourceType | None = None
    request_stage: RequestStage | None = None


class HeaderEntry(CDPModel):
    """
    Response HTTP header entry
    """

    name: str
    value: str


class AuthChallenge(CDPModel):
    """
    Authorization challenge for HTTP status code 401 or 407.
    """

    source: Literal["Server", "Proxy"] | None = None
    origin: str
    scheme: str
    realm: str


class AuthChallengeResponse(CDPModel):
    """
    Response to an AuthChallenge.
    """

    response: Literal["Default", "CancelAuth", "ProvideCredentials"]
    username: str | None = None
    password: str | None = None
