# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Preload Domain."""

from .client import PreloadClient
from .commands import PreloadCommand
from .events import (
    PrefetchStatusUpdatedEvent,
    PreloadEnabledStateUpdatedEvent,
    PreloadEvent,
    PreloadingAttemptSourcesUpdatedEvent,
    PrerenderStatusUpdatedEvent,
    RuleSetRemovedEvent,
    RuleSetUpdatedEvent,
)
from .types import (
    PrefetchStatus,
    PreloadingAttemptKey,
    PreloadingAttemptSource,
    PreloadingStatus,
    PreloadPipelineId,
    PrerenderFinalStatus,
    PrerenderMismatchedHeaders,
    RuleSet,
    RuleSetErrorType,
    RuleSetId,
    SpeculationAction,
    SpeculationTargetHint,
)

__all__ = [
    "PrefetchStatus",
    "PrefetchStatusUpdatedEvent",
    "PreloadClient",
    "PreloadCommand",
    "PreloadEnabledStateUpdatedEvent",
    "PreloadEvent",
    "PreloadPipelineId",
    "PreloadingAttemptKey",
    "PreloadingAttemptSource",
    "PreloadingAttemptSourcesUpdatedEvent",
    "PreloadingStatus",
    "PrerenderFinalStatus",
    "PrerenderMismatchedHeaders",
    "PrerenderStatusUpdatedEvent",
    "RuleSet",
    "RuleSetErrorType",
    "RuleSetId",
    "RuleSetRemovedEvent",
    "RuleSetUpdatedEvent",
    "SpeculationAction",
    "SpeculationTargetHint",
]
