# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from cdpify.domains import dom, network

"""
Unique id
"""
RuleSetId = str


@dataclass(kw_only=True, slots=True)
class RuleSet:
    """
    Corresponds to SpeculationRuleSet
    """

    id: RuleSetId = field(metadata={"cdp_name": "id"})
    loader_id: network.LoaderId = field(metadata={"cdp_name": "loaderId"})
    source_text: str = field(metadata={"cdp_name": "sourceText"})
    backend_node_id: dom.BackendNodeId | None = field(
        default=None, metadata={"cdp_name": "backendNodeId"}
    )
    url: str | None = field(default=None, metadata={"cdp_name": "url"})
    request_id: network.RequestId | None = field(
        default=None, metadata={"cdp_name": "requestId"}
    )
    error_type: RuleSetErrorType | None = field(
        default=None, metadata={"cdp_name": "errorType"}
    )
    error_message: str | None = field(
        default=None, metadata={"cdp_name": "errorMessage"}
    )
    tag: str | None = field(default=None, metadata={"cdp_name": "tag"})


type RuleSetErrorType = Literal[
    "SourceIsNotJsonObject", "InvalidRulesSkipped", "InvalidRulesetLevelTag"
]

"""
The type of preloading attempted. It corresponds to mojom::SpeculationAction (although
PrefetchWithSubresources is omitted as it isn't being used by clients).
"""
type SpeculationAction = Literal["Prefetch", "Prerender", "PrerenderUntilScript"]

"""
Corresponds to mojom::SpeculationTargetHint. See
https://github.com/WICG/nav-speculation/blob/main/triggers.md#window-name-targeting-hints
"""
type SpeculationTargetHint = Literal["Blank", "Self"]


@dataclass(kw_only=True, slots=True)
class PreloadingAttemptKey:
    """
    A key that identifies a preloading attempt. The url used is the url specified by
    the trigger (i.e. the initial URL), and not the final url that is navigated to. For
    example, prerendering allows same-origin main frame navigations during the attempt,
    but the attempt is still keyed with the initial URL.
    """

    loader_id: network.LoaderId = field(metadata={"cdp_name": "loaderId"})
    action: SpeculationAction = field(metadata={"cdp_name": "action"})
    url: str = field(metadata={"cdp_name": "url"})
    form_submission: bool | None = field(
        default=None, metadata={"cdp_name": "formSubmission"}
    )
    target_hint: SpeculationTargetHint | None = field(
        default=None, metadata={"cdp_name": "targetHint"}
    )


@dataclass(kw_only=True, slots=True)
class PreloadingAttemptSource:
    """
    Lists sources for a preloading attempt, specifically the ids of rule sets that had
    a speculation rule that triggered the attempt, and the BackendNodeIds of <a href> or
    <area href> elements that triggered the attempt (in the case of attempts triggered
    by a document rule). It is possible for multiple rule sets and links to trigger a
    single attempt.
    """

    key: PreloadingAttemptKey = field(metadata={"cdp_name": "key"})
    rule_set_ids: list[RuleSetId] = field(metadata={"cdp_name": "ruleSetIds"})
    node_ids: list[dom.BackendNodeId] = field(metadata={"cdp_name": "nodeIds"})


"""
Chrome manages different types of preloads together using a concept of preloading
pipeline. For example, if a site uses a SpeculationRules for prerender, Chrome first
starts a prefetch and then upgrades it to prerender. CDP events for them are emitted
separately but they share `PreloadPipelineId`.
"""
PreloadPipelineId = str

"""
List of FinalStatus reasons for Prerender2.
"""
type PrerenderFinalStatus = Literal[
    "Activated",
    "Destroyed",
    "LowEndDevice",
    "InvalidSchemeRedirect",
    "InvalidSchemeNavigation",
    "NavigationRequestBlockedByCsp",
    "MojoBinderPolicy",
    "RendererProcessCrashed",
    "RendererProcessKilled",
    "Download",
    "TriggerDestroyed",
    "NavigationNotCommitted",
    "NavigationBadHttpStatus",
    "ClientCertRequested",
    "NavigationRequestNetworkError",
    "CancelAllHostsForTesting",
    "DidFailLoad",
    "Stop",
    "SslCertificateError",
    "LoginAuthRequested",
    "UaChangeRequiresReload",
    "BlockedByClient",
    "AudioOutputDeviceRequested",
    "MixedContent",
    "TriggerBackgrounded",
    "MemoryLimitExceeded",
    "DataSaverEnabled",
    "TriggerUrlHasEffectiveUrl",
    "ActivatedBeforeStarted",
    "InactivePageRestriction",
    "StartFailed",
    "TimeoutBackgrounded",
    "CrossSiteRedirectInInitialNavigation",
    "CrossSiteNavigationInInitialNavigation",
    "SameSiteCrossOriginRedirectNotOptInInInitialNavigation",
    "SameSiteCrossOriginNavigationNotOptInInInitialNavigation",
    "ActivationNavigationParameterMismatch",
    "ActivatedInBackground",
    "EmbedderHostDisallowed",
    "ActivationNavigationDestroyedBeforeSuccess",
    "TabClosedByUserGesture",
    "TabClosedWithoutUserGesture",
    "PrimaryMainFrameRendererProcessCrashed",
    "PrimaryMainFrameRendererProcessKilled",
    "ActivationFramePolicyNotCompatible",
    "PreloadingDisabled",
    "BatterySaverEnabled",
    "ActivatedDuringMainFrameNavigation",
    "PreloadingUnsupportedByWebContents",
    "CrossSiteRedirectInMainFrameNavigation",
    "CrossSiteNavigationInMainFrameNavigation",
    "SameSiteCrossOriginRedirectNotOptInInMainFrameNavigation",
    "SameSiteCrossOriginNavigationNotOptInInMainFrameNavigation",
    "MemoryPressureOnTrigger",
    "MemoryPressureAfterTriggered",
    "PrerenderingDisabledByDevTools",
    "SpeculationRuleRemoved",
    "ActivatedWithAuxiliaryBrowsingContexts",
    "MaxNumOfRunningEagerPrerendersExceeded",
    "MaxNumOfRunningNonEagerPrerendersExceeded",
    "MaxNumOfRunningEmbedderPrerendersExceeded",
    "PrerenderingUrlHasEffectiveUrl",
    "RedirectedPrerenderingUrlHasEffectiveUrl",
    "ActivationUrlHasEffectiveUrl",
    "JavaScriptInterfaceAdded",
    "JavaScriptInterfaceRemoved",
    "AllPrerenderingCanceled",
    "WindowClosed",
    "SlowNetwork",
    "OtherPrerenderedPageActivated",
    "V8OptimizerDisabled",
    "PrerenderFailedDuringPrefetch",
    "BrowsingDataRemoved",
    "PrerenderHostReused",
    "FormSubmitWhenPrerendering",
    "CrossDocumentRestart",
]

"""
Preloading status values, see also PreloadingTriggeringOutcome. This status is shared
by prefetchStatusUpdated and prerenderStatusUpdated.
"""
type PreloadingStatus = Literal[
    "Pending", "Running", "Ready", "Success", "Failure", "NotSupported"
]

"""
TODO(https://crbug.com/1384419): revisit the list of PrefetchStatus and filter out the
ones that aren't necessary to the developers.
"""
type PrefetchStatus = Literal[
    "PrefetchAllowed",
    "PrefetchFailedIneligibleRedirect",
    "PrefetchFailedInvalidRedirect",
    "PrefetchFailedMIMENotSupported",
    "PrefetchFailedNetError",
    "PrefetchFailedNon2XX",
    "PrefetchEvictedAfterBrowsingDataRemoved",
    "PrefetchEvictedAfterCandidateRemoved",
    "PrefetchEvictedForNewerPrefetch",
    "PrefetchHeldback",
    "PrefetchIneligibleRetryAfter",
    "PrefetchIsPrivacyDecoy",
    "PrefetchIsStale",
    "PrefetchNotEligibleBlockedByConnectionAllowlist",
    "PrefetchNotEligibleBrowserContextOffTheRecord",
    "PrefetchNotEligibleCrossOrigin",
    "PrefetchNotEligibleDataSaverEnabled",
    "PrefetchNotEligibleExistingProxy",
    "PrefetchNotEligibleHostIsNonUnique",
    "PrefetchNotEligibleNonDefaultStoragePartition",
    "PrefetchNotEligibleSameSiteCrossOriginPrefetchRequiredProxy",
    "PrefetchNotEligibleSchemeIsNotHttps",
    "PrefetchNotEligibleUserHasCookies",
    "PrefetchNotEligibleUserHasServiceWorker",
    "PrefetchNotEligibleUserHasServiceWorkerNoFetchHandler",
    "PrefetchNotEligibleRedirectFromServiceWorker",
    "PrefetchNotEligibleRedirectToServiceWorker",
    "PrefetchNotEligibleBatterySaverEnabled",
    "PrefetchNotEligiblePreloadingDisabled",
    "PrefetchNotFinishedInTime",
    "PrefetchNotStarted",
    "PrefetchNotUsedCookiesChanged",
    "PrefetchProxyNotAvailable",
    "PrefetchResponseUsed",
    "PrefetchSuccessfulButNotUsed",
    "PrefetchNotUsedProbeFailed",
    "PrefetchCancelledOnUserNavigation",
]


@dataclass(kw_only=True, slots=True)
class PrerenderMismatchedHeaders:
    """
    Information of headers to be displayed when the header mismatch occurred.
    """

    header_name: str = field(metadata={"cdp_name": "headerName"})
    initial_value: str | None = field(
        default=None, metadata={"cdp_name": "initialValue"}
    )
    activation_value: str | None = field(
        default=None, metadata={"cdp_name": "activationValue"}
    )
