# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.shared.command_sender import CDPCommandSender
from cdpify.shared.decorators import deprecated

from .commands import (
    DOMDebuggerCommand,
    GetEventListenersParams,
    GetEventListenersResult,
    RemoveDOMBreakpointParams,
    RemoveEventListenerBreakpointParams,
    RemoveInstrumentationBreakpointParams,
    RemoveXHRBreakpointParams,
    SetBreakOnCSPViolationParams,
    SetDOMBreakpointParams,
    SetEventListenerBreakpointParams,
    SetInstrumentationBreakpointParams,
    SetXHRBreakpointParams,
)
from .types import (
    CSPViolationType,
    DOMBreakpointType,
)

if TYPE_CHECKING:
    from cdpify.domains import dom, runtime


class DOMDebugger:
    def __init__(self, command_sender: CDPCommandSender) -> None:
        self._command_sender = command_sender

    async def get_event_listeners(
        self,
        *,
        object_id: runtime.RemoteObjectId,
        depth: int | None = None,
        pierce: bool | None = None,
        session_id: str | None = None,
    ) -> GetEventListenersResult:
        """
        Returns event listeners of the given object.
        """
        params = GetEventListenersParams(
            object_id=object_id, depth=depth, pierce=pierce
        )

        result = await self._command_sender.send_raw(
            method=DOMDebuggerCommand.GET_EVENT_LISTENERS,
            params=encode_cdp(params),
            session_id=session_id,
        )
        return decode_cdp(GetEventListenersResult, result)

    async def remove_dom_breakpoint(
        self,
        *,
        node_id: dom.NodeId,
        type: DOMBreakpointType,
        session_id: str | None = None,
    ) -> None:
        """
        Removes DOM breakpoint that was set using `setDOMBreakpoint`.
        """
        params = RemoveDOMBreakpointParams(node_id=node_id, type=type)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.REMOVE_DOM_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def remove_event_listener_breakpoint(
        self,
        *,
        event_name: str,
        target_name: str | None = None,
        session_id: str | None = None,
    ) -> None:
        """
        Removes breakpoint on particular DOM event.
        """
        params = RemoveEventListenerBreakpointParams(
            event_name=event_name, target_name=target_name
        )

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.REMOVE_EVENT_LISTENER_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    @deprecated()
    async def remove_instrumentation_breakpoint(
        self,
        *,
        event_name: str,
        session_id: str | None = None,
    ) -> None:
        """
        Removes breakpoint on particular native event.
        """
        params = RemoveInstrumentationBreakpointParams(event_name=event_name)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.REMOVE_INSTRUMENTATION_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def remove_xhr_breakpoint(
        self,
        *,
        url: str,
        session_id: str | None = None,
    ) -> None:
        """
        Removes breakpoint from XMLHttpRequest.
        """
        params = RemoveXHRBreakpointParams(url=url)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.REMOVE_XHR_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def set_break_on_csp_violation(
        self,
        *,
        violation_types: list[CSPViolationType],
        session_id: str | None = None,
    ) -> None:
        """
        Sets breakpoint on particular CSP violations.
        """
        params = SetBreakOnCSPViolationParams(violation_types=violation_types)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.SET_BREAK_ON_CSP_VIOLATION,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def set_dom_breakpoint(
        self,
        *,
        node_id: dom.NodeId,
        type: DOMBreakpointType,
        session_id: str | None = None,
    ) -> None:
        """
        Sets breakpoint on particular operation with DOM.
        """
        params = SetDOMBreakpointParams(node_id=node_id, type=type)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.SET_DOM_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def set_event_listener_breakpoint(
        self,
        *,
        event_name: str,
        target_name: str | None = None,
        session_id: str | None = None,
    ) -> None:
        """
        Sets breakpoint on particular DOM event.
        """
        params = SetEventListenerBreakpointParams(
            event_name=event_name, target_name=target_name
        )

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.SET_EVENT_LISTENER_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    @deprecated()
    async def set_instrumentation_breakpoint(
        self,
        *,
        event_name: str,
        session_id: str | None = None,
    ) -> None:
        """
        Sets breakpoint on particular native event.
        """
        params = SetInstrumentationBreakpointParams(event_name=event_name)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.SET_INSTRUMENTATION_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def set_xhr_breakpoint(
        self,
        *,
        url: str,
        session_id: str | None = None,
    ) -> None:
        """
        Sets breakpoint on XMLHttpRequest.
        """
        params = SetXHRBreakpointParams(url=url)

        await self._command_sender.send_raw(
            method=DOMDebuggerCommand.SET_XHR_BREAKPOINT,
            params=encode_cdp(params),
            session_id=session_id,
        )
