# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pydantic_cpd.client import CDPClient

from .commands import (
    EnableParams,
    SetSinkToUseParams,
    StartDesktopMirroringParams,
    StartTabMirroringParams,
    StopCastingParams,
)


class CastClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def enable(
        self,
        *,
        presentation_url: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EnableParams(presentationUrl=presentation_url)

        result = await self._client.send_raw(
            method="Cast.enable",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method="Cast.disable",
            params=None,
            session_id=session_id,
        )
        return result

    async def set_sink_to_use(
        self,
        *,
        sink_name: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetSinkToUseParams(sinkName=sink_name)

        result = await self._client.send_raw(
            method="Cast.setSinkToUse",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def start_desktop_mirroring(
        self,
        *,
        sink_name: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = StartDesktopMirroringParams(sinkName=sink_name)

        result = await self._client.send_raw(
            method="Cast.startDesktopMirroring",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def start_tab_mirroring(
        self,
        *,
        sink_name: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = StartTabMirroringParams(sinkName=sink_name)

        result = await self._client.send_raw(
            method="Cast.startTabMirroring",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def stop_casting(
        self,
        *,
        sink_name: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = StopCastingParams(sinkName=sink_name)

        result = await self._client.send_raw(
            method="Cast.stopCasting",
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
