# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP PerformanceTimeline Domain."""

from .client import PerformanceTimelineClient
from .commands import EnableParams, PerformanceTimelineCommand
from .events import PerformanceTimelineEvent, TimelineEventAddedEvent
from .types import (
    LargestContentfulPaint,
    LayoutShift,
    LayoutShiftAttribution,
    TimelineEvent,
)

__all__ = [
    "EnableParams",
    "LargestContentfulPaint",
    "LayoutShift",
    "LayoutShiftAttribution",
    "PerformanceTimelineClient",
    "PerformanceTimelineCommand",
    "PerformanceTimelineEvent",
    "TimelineEvent",
    "TimelineEventAddedEvent",
]
