# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class EnableParams(CDPModel):
    """
    Enable the WebAuthn domain and start intercepting credential storage and retrieval
    with a virtual authenticator.
    """

    enable_u_i: bool | None = None


class AddVirtualAuthenticatorParams(CDPModel):
    """
    Creates and adds a virtual authenticator.
    """

    options: VirtualAuthenticatorOptions


class AddVirtualAuthenticatorResult(CDPModel):
    authenticator_id: AuthenticatorId


class SetResponseOverrideBitsParams(CDPModel):
    """
    Resets parameters isBogusSignature, isBadUV, isBadUP to false if they are not
    present.
    """

    authenticator_id: AuthenticatorId
    is_bogus_signature: bool | None = None
    is_bad_u_v: bool | None = None
    is_bad_u_p: bool | None = None


class RemoveVirtualAuthenticatorParams(CDPModel):
    """
    Removes the given authenticator.
    """

    authenticator_id: AuthenticatorId


class AddCredentialParams(CDPModel):
    """
    Adds the credential to the specified authenticator.
    """

    authenticator_id: AuthenticatorId
    credential: Credential


class GetCredentialParams(CDPModel):
    """
    Returns a single credential stored in the given virtual authenticator that matches
    the credential ID.
    """

    authenticator_id: AuthenticatorId
    credential_id: str


class GetCredentialResult(CDPModel):
    credential: Credential


class GetCredentialsParams(CDPModel):
    """
    Returns all the credentials stored in the given virtual authenticator.
    """

    authenticator_id: AuthenticatorId


class GetCredentialsResult(CDPModel):
    credentials: list[Credential]


class RemoveCredentialParams(CDPModel):
    """
    Removes a credential from the authenticator.
    """

    authenticator_id: AuthenticatorId
    credential_id: str


class ClearCredentialsParams(CDPModel):
    """
    Clears all the credentials from the specified device.
    """

    authenticator_id: AuthenticatorId


class SetUserVerifiedParams(CDPModel):
    """
    Sets whether User Verification succeeds or fails for an authenticator. The default
    is true.
    """

    authenticator_id: AuthenticatorId
    is_user_verified: bool


class SetAutomaticPresenceSimulationParams(CDPModel):
    """
    Sets whether tests of user presence will succeed immediately (if true) or fail to
    resolve (if false) for an authenticator. The default is true.
    """

    authenticator_id: AuthenticatorId
    enabled: bool


class SetCredentialPropertiesParams(CDPModel):
    """
    Allows setting credential properties.
    https://w3c.github.io/webauthn/#sctn-automation-set-credential-properties
    """

    authenticator_id: AuthenticatorId
    credential_id: str
    backup_eligibility: bool | None = None
    backup_state: bool | None = None
