# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Console Domain."""

from .client import Console
from .commands import ConsoleCommand
from .events import ConsoleEvent, MessageAddedEvent
from .types import ConsoleMessage

__all__ = [
    "Console",
    "ConsoleCommand",
    "ConsoleEvent",
    "ConsoleMessage",
    "MessageAddedEvent",
]
