# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from enum import StrEnum


class ConsoleCommand(StrEnum):
    CLEAR_MESSAGES = "Console.clearMessages"
    DISABLE = "Console.disable"
    ENABLE = "Console.enable"


# No commands defined
