# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from cdpify.transport import Transport

from .commands import (
    ConsoleCommand,
)


class Console:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def clear_messages(
        self,
        session_id: str | None = None,
    ) -> None:
        """
        Does nothing.
        """
        await self._transport.execute(
            method=ConsoleCommand.CLEAR_MESSAGES,
            params=None,
            session_id=session_id,
        )

    async def disable(
        self,
        session_id: str | None = None,
    ) -> None:
        """
        Disables console domain, prevents further console messages from being reported
        to the client.
        """
        await self._transport.execute(
            method=ConsoleCommand.DISABLE,
            params=None,
            session_id=session_id,
        )

    async def enable(
        self,
        session_id: str | None = None,
    ) -> None:
        """
        Enables console domain, sends the messages collected so far to the client by
        means of the `messageAdded` notification.
        """
        await self._transport.execute(
            method=ConsoleCommand.ENABLE,
            params=None,
            session_id=session_id,
        )
