# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.transport import Transport

from .commands import (
    CacheStorageCommand,
    DeleteCacheParams,
    DeleteEntryParams,
    RequestCachedResponseParams,
    RequestCachedResponseResult,
    RequestCacheNamesParams,
    RequestCacheNamesResult,
    RequestEntriesParams,
    RequestEntriesResult,
)
from .types import (
    CacheId,
    Header,
)

if TYPE_CHECKING:
    from cdpify.domains import storage


class CacheStorage:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def delete_cache(
        self,
        *,
        cache_id: CacheId,
        session_id: str | None = None,
    ) -> None:
        """
        Deletes a cache.
        """
        params = DeleteCacheParams(cache_id=cache_id)

        await self._transport.execute(
            method=CacheStorageCommand.DELETE_CACHE,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def delete_entry(
        self,
        *,
        cache_id: CacheId,
        request: str,
        session_id: str | None = None,
    ) -> None:
        """
        Deletes a cache entry.
        """
        params = DeleteEntryParams(cache_id=cache_id, request=request)

        await self._transport.execute(
            method=CacheStorageCommand.DELETE_ENTRY,
            params=encode_cdp(params),
            session_id=session_id,
        )

    async def request_cache_names(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        session_id: str | None = None,
    ) -> RequestCacheNamesResult:
        """
        Requests cache names.
        """
        params = RequestCacheNamesParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
        )

        result = await self._transport.execute(
            method=CacheStorageCommand.REQUEST_CACHE_NAMES,
            params=encode_cdp(params),
            session_id=session_id,
        )
        return decode_cdp(RequestCacheNamesResult, result)

    async def request_cached_response(
        self,
        *,
        cache_id: CacheId,
        request_url: str,
        request_headers: list[Header],
        session_id: str | None = None,
    ) -> RequestCachedResponseResult:
        """
        Fetches cache entry.
        """
        params = RequestCachedResponseParams(
            cache_id=cache_id, request_url=request_url, request_headers=request_headers
        )

        result = await self._transport.execute(
            method=CacheStorageCommand.REQUEST_CACHED_RESPONSE,
            params=encode_cdp(params),
            session_id=session_id,
        )
        return decode_cdp(RequestCachedResponseResult, result)

    async def request_entries(
        self,
        *,
        cache_id: CacheId,
        skip_count: int | None = None,
        page_size: int | None = None,
        path_filter: str | None = None,
        session_id: str | None = None,
    ) -> RequestEntriesResult:
        """
        Requests data from cache.
        """
        params = RequestEntriesParams(
            cache_id=cache_id,
            skip_count=skip_count,
            page_size=page_size,
            path_filter=path_filter,
        )

        result = await self._transport.execute(
            method=CacheStorageCommand.REQUEST_ENTRIES,
            params=encode_cdp(params),
            session_id=session_id,
        )
        return decode_cdp(RequestEntriesResult, result)
