# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from typing import TYPE_CHECKING, Literal

from pydantic_cpd.domains.base import CDPModel

from .types import *

if TYPE_CHECKING:
    from pydantic_cpd.cdp import dom, network, runtime


class PageEvent(StrEnum):
    DOM_CONTENT_EVENT_FIRED = "Page.domContentEventFired"
    FILE_CHOOSER_OPENED = "Page.fileChooserOpened"
    FRAME_ATTACHED = "Page.frameAttached"
    FRAME_CLEARED_SCHEDULED_NAVIGATION = "Page.frameClearedScheduledNavigation"
    FRAME_DETACHED = "Page.frameDetached"
    FRAME_SUBTREE_WILL_BE_DETACHED = "Page.frameSubtreeWillBeDetached"
    FRAME_NAVIGATED = "Page.frameNavigated"
    DOCUMENT_OPENED = "Page.documentOpened"
    FRAME_RESIZED = "Page.frameResized"
    FRAME_STARTED_NAVIGATING = "Page.frameStartedNavigating"
    FRAME_REQUESTED_NAVIGATION = "Page.frameRequestedNavigation"
    FRAME_SCHEDULED_NAVIGATION = "Page.frameScheduledNavigation"
    FRAME_STARTED_LOADING = "Page.frameStartedLoading"
    FRAME_STOPPED_LOADING = "Page.frameStoppedLoading"
    DOWNLOAD_WILL_BEGIN = "Page.downloadWillBegin"
    DOWNLOAD_PROGRESS = "Page.downloadProgress"
    INTERSTITIAL_HIDDEN = "Page.interstitialHidden"
    INTERSTITIAL_SHOWN = "Page.interstitialShown"
    JAVASCRIPT_DIALOG_CLOSED = "Page.javascriptDialogClosed"
    JAVASCRIPT_DIALOG_OPENING = "Page.javascriptDialogOpening"
    LIFECYCLE_EVENT = "Page.lifecycleEvent"
    BACK_FORWARD_CACHE_NOT_USED = "Page.backForwardCacheNotUsed"
    LOAD_EVENT_FIRED = "Page.loadEventFired"
    NAVIGATED_WITHIN_DOCUMENT = "Page.navigatedWithinDocument"
    SCREENCAST_FRAME = "Page.screencastFrame"
    SCREENCAST_VISIBILITY_CHANGED = "Page.screencastVisibilityChanged"
    WINDOW_OPEN = "Page.windowOpen"
    COMPILATION_CACHE_PRODUCED = "Page.compilationCacheProduced"


class DomContentEventFiredEvent(CDPModel):
    timestamp: network.MonotonicTime


class FileChooserOpenedEvent(CDPModel):
    """
    Emitted only when `page.interceptFileChooser` is enabled.
    """

    frame_id: FrameId
    mode: Literal["selectSingle", "selectMultiple"]
    backend_node_id: dom.BackendNodeId | None = None


class FrameAttachedEvent(CDPModel):
    """
    Fired when frame has been attached to its parent.
    """

    frame_id: FrameId
    parent_frame_id: FrameId
    stack: runtime.StackTrace | None = None


class FrameClearedScheduledNavigationEvent(CDPModel):
    """
    Fired when frame no longer has a scheduled navigation.
    """

    frame_id: FrameId


class FrameDetachedEvent(CDPModel):
    """
    Fired when frame has been detached from its parent.
    """

    frame_id: FrameId
    reason: Literal["remove", "swap"]


class FrameSubtreeWillBeDetachedEvent(CDPModel):
    """
    Fired before frame subtree is detached. Emitted before any frame of the subtree is
    actually detached.
    """

    frame_id: FrameId


class FrameNavigatedEvent(CDPModel):
    """
    Fired once navigation of the frame has completed. Frame is now associated with the
    new loader.
    """

    frame: Frame
    type: NavigationType


class DocumentOpenedEvent(CDPModel):
    """
    Fired when opening document to write to.
    """

    frame: Frame


class FrameResizedEvent(CDPModel):
    pass


class FrameStartedNavigatingEvent(CDPModel):
    """
    Fired when a navigation starts. This event is fired for both renderer-initiated and
    browser-initiated navigations. For renderer-initiated navigations, the event is
    fired after `frameRequestedNavigation`. Navigation may still be cancelled after the
    event is issued. Multiple events can be fired for a single navigation, for example,
    when a same-document navigation becomes a cross-document navigation (such as in the
    case of a frameset).
    """

    frame_id: FrameId
    url: str
    loader_id: network.LoaderId
    navigation_type: Literal[
        "reload",
        "reloadBypassingCache",
        "restore",
        "restoreWithPost",
        "historySameDocument",
        "historyDifferentDocument",
        "sameDocument",
        "differentDocument",
    ]


class FrameRequestedNavigationEvent(CDPModel):
    """
    Fired when a renderer-initiated navigation is requested. Navigation may still be
    cancelled after the event is issued.
    """

    frame_id: FrameId
    reason: ClientNavigationReason
    url: str
    disposition: ClientNavigationDisposition


class FrameScheduledNavigationEvent(CDPModel):
    """
    Fired when frame schedules a potential navigation.
    """

    frame_id: FrameId
    delay: float
    reason: ClientNavigationReason
    url: str


class FrameStartedLoadingEvent(CDPModel):
    """
    Fired when frame has started loading.
    """

    frame_id: FrameId


class FrameStoppedLoadingEvent(CDPModel):
    """
    Fired when frame has stopped loading.
    """

    frame_id: FrameId


class DownloadWillBeginEvent(CDPModel):
    """
    Fired when page is about to start a download. Deprecated. Use
    Browser.downloadWillBegin instead.
    """

    frame_id: FrameId
    guid: str
    url: str
    suggested_filename: str


class DownloadProgressEvent(CDPModel):
    """
    Fired when download makes progress. Last call has |done| == true. Deprecated. Use
    Browser.downloadProgress instead.
    """

    guid: str
    total_bytes: float
    received_bytes: float
    state: Literal["inProgress", "completed", "canceled"]


class InterstitialHiddenEvent(CDPModel):
    """
    Fired when interstitial page was hidden
    """

    pass


class InterstitialShownEvent(CDPModel):
    """
    Fired when interstitial page was shown
    """

    pass


class JavascriptDialogClosedEvent(CDPModel):
    """
    Fired when a JavaScript initiated dialog (alert, confirm, prompt, or
    onbeforeunload) has been closed.
    """

    frame_id: FrameId
    result: bool
    user_input: str


class JavascriptDialogOpeningEvent(CDPModel):
    """
    Fired when a JavaScript initiated dialog (alert, confirm, prompt, or
    onbeforeunload) is about to open.
    """

    url: str
    frame_id: FrameId
    message: str
    type: DialogType
    has_browser_handler: bool
    default_prompt: str | None = None


class LifecycleEventEvent(CDPModel):
    """
    Fired for lifecycle events (navigation, load, paint, etc) in the current target
    (including local frames).
    """

    frame_id: FrameId
    loader_id: network.LoaderId
    name: str
    timestamp: network.MonotonicTime


class BackForwardCacheNotUsedEvent(CDPModel):
    """
    Fired for failed bfcache history navigations if BackForwardCache feature is
    enabled. Do not assume any ordering with the Page.frameNavigated event. This event
    is fired only for main-frame history navigation where the document changes
    (non-same-document navigations), when bfcache navigation fails.
    """

    loader_id: network.LoaderId
    frame_id: FrameId
    not_restored_explanations: list[BackForwardCacheNotRestoredExplanation]
    not_restored_explanations_tree: (
        BackForwardCacheNotRestoredExplanationTree | None
    ) = None


class LoadEventFiredEvent(CDPModel):
    timestamp: network.MonotonicTime


class NavigatedWithinDocumentEvent(CDPModel):
    """
    Fired when same-document navigation happens, e.g. due to history API usage or
    anchor navigation.
    """

    frame_id: FrameId
    url: str
    navigation_type: Literal["fragment", "historyApi", "other"]


class ScreencastFrameEvent(CDPModel):
    """
    Compressed image data requested by the `startScreencast`.
    """

    data: str
    metadata: ScreencastFrameMetadata
    session_id: int


class ScreencastVisibilityChangedEvent(CDPModel):
    """
    Fired when the page with currently enabled screencast was shown or hidden `.
    """

    visible: bool


class WindowOpenEvent(CDPModel):
    """
    Fired when a new window is going to be opened, via window.open(), link click, form
    submission, etc.
    """

    url: str
    window_name: str
    window_features: list[str]
    user_gesture: bool


class CompilationCacheProducedEvent(CDPModel):
    """
    Issued for every compilation cache generated.
    """

    url: str
    data: str
