# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP BackgroundService Domain."""

from .client import BackgroundServiceClient
from .commands import (
    BackgroundServiceCommand,
    ClearEventsParams,
    SetRecordingParams,
    StartObservingParams,
    StopObservingParams,
)
from .events import (
    BackgroundServiceEvent as BackgroundServiceEventName,
)
from .events import (
    BackgroundServiceEventReceivedEvent,
    RecordingStateChangedEvent,
)
from .types import BackgroundServiceEvent, EventMetadata, ServiceName

__all__ = [
    "BackgroundServiceClient",
    "BackgroundServiceCommand",
    "BackgroundServiceEvent",
    "BackgroundServiceEventName",
    "BackgroundServiceEventReceivedEvent",
    "ClearEventsParams",
    "EventMetadata",
    "RecordingStateChangedEvent",
    "ServiceName",
    "SetRecordingParams",
    "StartObservingParams",
    "StopObservingParams",
]
