# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from cdpify.domains import network, serviceworker

"""
The Background Service that will be associated with the commands/events. Every
Background Service operates independently, but they share the same API.
"""
type ServiceName = Literal[
    "backgroundFetch",
    "backgroundSync",
    "pushMessaging",
    "notifications",
    "paymentHandler",
    "periodicBackgroundSync",
]


@dataclass(kw_only=True, slots=True)
class EventMetadata:
    """
    A key-value pair for additional event information to pass along.
    """

    key: str = field(metadata={"cdp_name": "key"})
    value: str = field(metadata={"cdp_name": "value"})


@dataclass(kw_only=True, slots=True)
class BackgroundServiceEvent:
    timestamp: network.TimeSinceEpoch = field(metadata={"cdp_name": "timestamp"})
    origin: str = field(metadata={"cdp_name": "origin"})
    service_worker_registration_id: serviceworker.RegistrationID = field(
        metadata={"cdp_name": "serviceWorkerRegistrationId"}
    )
    service: ServiceName = field(metadata={"cdp_name": "service"})
    event_name: str = field(metadata={"cdp_name": "eventName"})
    instance_id: str = field(metadata={"cdp_name": "instanceId"})
    event_metadata: list[EventMetadata] = field(metadata={"cdp_name": "eventMetadata"})
    storage_key: str = field(metadata={"cdp_name": "storageKey"})
