# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from cdpify.shared.models import CDPEvent

from .types import (
    AXNode,
)


class AccessibilityEvent(StrEnum):
    LOAD_COMPLETE = "Accessibility.loadComplete"
    NODES_UPDATED = "Accessibility.nodesUpdated"


@dataclass(kw_only=True, slots=True)
class LoadCompleteEvent(CDPEvent):
    """
    The loadComplete event mirrors the load complete event sent by the browser to
    assistive technology when the web page has finished loading.
    """

    root: AXNode


@dataclass(kw_only=True, slots=True)
class NodesUpdatedEvent(CDPEvent):
    """
    The nodesUpdated event is sent every time a previously requested node has changed
    the in tree.
    """

    nodes: list[AXNode]
