# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING

from cdpify.codec import decode_cdp, encode_cdp
from cdpify.executor import CommandExecutor

from .commands import (
    CloseParams,
    IOCommand,
    ReadParams,
    ReadResult,
    ResolveBlobParams,
    ResolveBlobResult,
)
from .types import (
    StreamHandle,
)

if TYPE_CHECKING:
    from cdpify.domains import runtime


class IO:
    def __init__(self, executor: CommandExecutor) -> None:
        self._executor = executor

    async def close(
        self,
        *,
        handle: StreamHandle,
    ) -> None:
        """
        Close the stream, discard any temporary backing storage.
        """
        params = CloseParams(handle=handle)

        await self._executor.execute(
            method=IOCommand.CLOSE,
            params=encode_cdp(params),
        )

    async def read(
        self,
        *,
        handle: StreamHandle,
        offset: int | None = None,
        size: int | None = None,
    ) -> ReadResult:
        """
        Read a chunk of the stream
        """
        params = ReadParams(handle=handle, offset=offset, size=size)

        result = await self._executor.execute(
            method=IOCommand.READ,
            params=encode_cdp(params),
        )
        return decode_cdp(ReadResult, result)

    async def resolve_blob(
        self,
        *,
        object_id: runtime.RemoteObjectId,
    ) -> ResolveBlobResult:
        """
        Return UUID of Blob object specified by a remote object id.
        """
        params = ResolveBlobParams(object_id=object_id)

        result = await self._executor.execute(
            method=IOCommand.RESOLVE_BLOB,
            params=encode_cdp(params),
        )
        return decode_cdp(ResolveBlobResult, result)
